### ISSUE TITLE
牛逼plus呀 支持下

### ISSUE THREAD

**Issue by qxwo** [troyeguo/koodo-reader#10]
使用建议：
(多端进度同步(安卓IOS)
码头安装
多格式:如pdf，mobi，AW3(版权问题？)
登录验证
仅个人主观建议.

**Comment by troyeguo** [comment]
您好！

1）后续会考虑支持安卓和IOS的
2）不太明白码头安装是什么安装方式
3）目前没有支持更多格式的计划，主要是因为没有比较好的JavaScript库提供解析支持
4）登陆验证功能需要服务器支持，这对于一个开源项目来说，成本太高，无法保证长期稳定

感谢您提供的建议，祝您生活愉快

**Comment by Wcdaren** [comment]
牛逼呀!大佬!我也要来看代码,到时做点贡献

**Comment by troyeguo** [comment]
> 牛逼呀!大佬!我也要来看代码,到时做点贡献

欢迎欢迎

**Comment by waahaa** [comment]
> 您好！
> 
> 1）后续会考虑支持安卓和IOS的
> 2）不太明白码头安装是什么安装方式
> 3）后续会考虑支持更多格式的
> 4）登陆验证功能需要服务器支持，这对于一个开源项目来说，成本太高，无法保证长期稳定
> 
> 感谢您提供的建议，祝您生活愉快

他想说的应该是docker安装
