### ISSUE TITLE
云同步把win的文件路径同步到mac，导致打不开任何书

### ISSUE THREAD

**Issue by xiaoao19** [troyeguo/koodo-reader#100]
我是基于缓存目录，云同步win和mac两台电脑
最近发现mac的书全部打不开
去设置一看 发现缓存目录显示是win的（居然有c盘）
单击一下那个窗口
又变成mac的缓存目录了
希望能想办法区分一下
谢谢！
（1.2.2和1.2.3都遇到）

## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |           |
| App Version (应用版本)      |           |

---

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本解决这个问题

**Comment by troyeguo** [comment]
您需要先备份所有数据，然后清空windows和macos的数据，再使用最新版 Koodo 恢复数据，并且不要修改数据存储位置，这样应该就行了
