### ISSUE TITLE
中文PDF文件乱码

### ISSUE THREAD

**Issue by simonecho** [troyeguo/koodo-reader#101]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System |  Windows 10 家庭中文版     20H2    |
| App Version (应用版本)      |      1.2.3     |

---

## 部分中文PDF乱码
![乱码](https://user-images.githubusercontent.com/12640565/111404411-afdec600-8709-11eb-9940-6a4d86bec53f.jpg)

**Comment by troyeguo** [comment]
您好，可以提供一下这个文件吗？我这边暂时没有遇到过这个问题。

**Comment by simonecho** [comment]
> 您好，可以提供一下这个文件吗？我这边暂时没有遇到过这个问题。
知网下载年代久远一点的PDF似乎都有这个问题
链接: https://pan.baidu.com/s/1bqEplwL3FgdA-bX3LuSpEA 提取码: 53sd

**Comment by troyeguo** [comment]
感谢您提供的文件，会在后续版本中修复这个问题的

**Comment by simonecho** [comment]
> 感谢您提供的文件，会在后续版本中修复这个问题的

期待！
