### ISSUE TITLE
epub目录完全错误

### ISSUE THREAD

**Issue by zxp1314gch** [troyeguo/koodo-reader#102]
<img width="1629" alt="截屏2021-03-18 上午10 11 51" src="https://user-images.githubusercontent.com/56782560/111563159-5f7f6b00-87d2-11eb-9a38-ffcb41c599e9.png">

**Comment by troyeguo** [comment]
您好，可以提供一下图书文件吗？

**Comment by zxp1314gch** [comment]
https://n802.com/file/16058819-367543781

**Comment by troyeguo** [comment]
您好，这可能是图书本身的问题，我在手机上用多看阅读也只能解析出这些目录![Screenshot_2021-03-18-12-03-46-330_com.duokan.reader.jpg](https://user-images.githubusercontent.com/13820674/111571712-2ea73200-87e2-11eb-8f69-a8cbcee37929.jpg)
