### ISSUE TITLE
Docker 安装如何配置【卷】的信息

### ISSUE THREAD

**Issue by valuex** [troyeguo/koodo-reader#108]
docker-hub上面以及github上关于docker安装的信息都很少，【卷】和【端口】怎么配置，请详细指点下，谢谢。

docker-compose.yml 中没有关于【卷】，即文件存储目录的信息。

version: "3"
services:
  koodo:
    build: .
    ports:
      - "80:80"

在群晖中搜索koodo-reader，只找到了下面这个镜像，是官方的么？
https://registry.hub.docker.com/r/fatelight/koodo-reader/

**Comment by troyeguo** [comment]
Docker 的代码是其他用户提交的pull request合并过来的，我对Docker也不太熟悉，您可以咨询 PR 提交者：https://github.com/troyeguo/koodo-reader/pull/82

**Comment by troyeguo** [comment]
这个镜像是其他用户上传的，我也是第一次知道
