### ISSUE TITLE
希望网页版的电子书内文能够被浏览器的Diigo插件标注

### ISSUE THREAD

**Issue by lovelystrange** [troyeguo/koodo-reader#110]
## Brief Introduction (介绍)
Diigo插件（以及ios、android上的diigo客户端，能够在几乎任何网页上选中文本后加以标注（highlight），并为标注位置提供一个标准的url。
我希望使用Koodo Reader 网页版把电子书转为具有固定地址的网页，进而使用Diigo的标注功能，由此建立起对电子书和网页的“通用引用流程”。
目前遇到的问题是，Koodo Reader阅读界面中选中的文本，无法被Diigo识别，因此无法标注。

**Comment by troyeguo** [comment]
您好，感谢您的建议，目前Koodo Reader的电子书已经是具有固定网址的网页，但是这个网址只能在导入该电子书的浏览器使用，您所有的数据都保存在了本地，Koodo Reader自身不提供图书同步服务，但与第三方集成的同步服务还在开发中。Diigo的标注需要监听网页的selected事件，这与Koodo Reader 自带的标注功能相互冲突，所以暂时没办法支持。

**Comment by lovelystrange** [comment]
感谢您的讲解。我有一些衍生想法希望供您参看：
1， 如果不能够做到“不同的浏览器中都能看到用户上传的同一本书”，那么能否通过识别epub/mobi等文件的MD5数据，实现“给每本书一个独一无二的类似DOI的编号”，这样即使本地没有某本书的文件实体，那么只需要同步、上传这本书，之前生成的URL仍然可以正常导向同一本书？
2，能否把URL的标记颗粒度进一步细化，使得URL可以指向具体的章节甚至段落，而不只是某本书。
3，如果能够实现2，那么我们甚至可以不再标注（不论是内置标注功能还是Diigo等外部功能）。
4，网页版目前不支持mobi，这一点在未来是可以解决的吗？

**Comment by troyeguo** [comment]
> 感谢您的讲解。我有一些衍生想法希望供您参看：
> 1， 如果不能够做到“不同的浏览器中都能看到用户上传的同一本书”，那么能否通过识别epub/mobi等文件的MD5数据，实现“给每本书一个独一无二的类似DOI的编号”，这样即使本地没有某本书的文件实体，那么只需要同步、上传这本书，之前生成的URL仍然可以正常导向同一本书？
> 2，能否把URL的标记颗粒度进一步细化，使得URL可以指向具体的章节甚至段落，而不只是某本书。
> 3，如果能够实现2，那么我们甚至可以不再标注（不论是内置标注功能还是Diigo等外部功能）。
> 4，网页版目前不支持mobi，这一点在未来是可以解决的吗？

1，这个功能依赖于Koodo Reader 自建一个电子书库，不仅需要存储md5值，还需要存储电子书，存在一定的法律风险，并且成本太高，并且Koodo Reader未来都没有自建服务器，提供同步功能的打算
2，技术上可以实现，但在第一点不能实现的前提下，没有这样做的意义
3，同2
4，理论上实现不了，可能的技术方案还在探索中

**Comment by lovelystrange** [comment]
1 这个功能其实不需要Koodo Reader持有电子书实体。只需要某个用户（我）在本地有电子书，即可在本地生成MD5，此后，我在web端运行Koodo Reader时，Koodo Reader需要保存的只是这个MD5信息——而web端给每本书分配的URL都是基于这个MD5信息计算所得的。
1.1 这个设计的用处是，无论我把一本书用Koodo Reader web端（自建）上传、移除多少次，只要文件本身MD5相同，生成的URL就一定是固定的。这对长期保存引用信息很有帮助。
1.2 上述想法的核心是：可跨设备、跨平台引用的且长期稳定的索引信息，在现在的资源条件下，比电子书文件本身更宝贵。这样做是没有任何法律风险的。

**Comment by lovelystrange** [comment]
我再补充一下1.2：

我们对纸本书的引用方式，是基于”同一个出版社，同一个版本，同一个印刷批次，则指定页码，所对应的内容一定相同“这个假设，不论这个批次的书籍有多少本，在您手上、在我手上、在图书馆，这样的引用都是等效的。

我希望实现的效果是，对于一个特定MD5的电子书文件来说，不论它储存在何处，曾经被上传到哪一个Web服务端（URL的域名部分是什么），在域名之后的那部分URL始终都是不变的。那么我们使用Diigo也好，直接在笔记中粘贴URL也好，只要还能够重新部署Koodo Reader，就一定能够通过这个URL打开同一本书的同一个位置。

可能您会觉得，既然这样，为什么不直接像传统纸书那样直接引用 电子书书名+章节名呢？因为那样的引用方式，会让每一次查阅出处都花费大量的”检索文件+打开+翻目录“劳动，更不用说电子书文件名可能会在保存、移动过程中变化。

而使用前述方案1，即使在一个新的工作环境中，我需要重新上传一次自己的本地书库，但完成这个动作后，在同一台设备上，我通过URL访问书籍就不会再有任何障碍了。

**Comment by troyeguo** [comment]
我明白您的意思，您是希望在另一台电脑上如果上传了同一本书也能通过同一个链接访问这本书，但目前Koodo Reader的备份恢复功能某种程度上已经可以实现这个需求了，将一台电脑上的数据备份，然后在另一台电脑上恢复，阅读时访问的链接也是一样的。您的需求主要建立在您使用diigo进行URL跨平台同步的基础上，但对于大部分用户来说，使用备份恢复或同步更加具有普适性，也能保证用户体验的一致性

**Comment by lovelystrange** [comment]
以目前Koodo Reader的设计思路而言，我非常期待在近期能够用到web版本的”备份、恢复“功能。那时，我们能够实现更细颗粒度的文本定位吗？

**Comment by troyeguo** [comment]
> 以目前Koodo Reader的设计思路而言，我非常期待在近期能够用到web版本的”备份、恢复“功能。那时，我们能够实现更细颗粒度的文本定位吗？

网页版已经支持备份恢复功能了，在右上角，笔记书摘已经实现文本的定位功能了，在阅读界面选中文字，添加笔记或者书摘，退出阅读就可以在我的笔记或我的书摘中看到，然后点击笔记下方的在显示笔记出处，就可以直接跳转到该笔记在书中的位置
