### ISSUE TITLE
希望改善软件性能，导入600w字的txt文件，切换视图，切换全屏要等半天

### ISSUE THREAD

**Issue by seeyou-github** [troyeguo/koodo-reader#1116]
### I've searched the issue list, there are no similar features.

- [X] Yes

### I've installed the latest developer version, still can't find this feature.

- [X] Yes

### If you have more than one feature, please open multiple issues.

- [X] Yes

### Brief Introduction

导入600w字的txt文件，切换视图，切换全屏要等半天
打开一本mobi也是要等半天。

软件是否全部读取了文件，每次切换都要重新读取全部文件？
是否可以部分读取？

### Details

软件是否全部读取了文件，每次切换都要重新读取全部文件？
是否可以部分读取？

**Comment by troyeguo** [comment]
不建议导入大体积的图书，后续增加文件大小限制
