### ISSUE TITLE
EPUB文件打开错误

### ISSUE THREAD

**Issue by simonecho** [troyeguo/koodo-reader#112]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |     Windows 10 家庭中文版 20H2      |
| App Version (应用版本)      |     1.2.3      |

---

## EPUB文件Adobe Digital Edition打开正常，导入软件后导航栏可见但无法，文件显示异常无法正常翻页
PS.其他EPUB文件正常打开
![image](https://user-images.githubusercontent.com/12640565/114151071-5310ad00-994f-11eb-9b18-3a28960378c7.png)
![image](https://user-images.githubusercontent.com/12640565/114151106-5c017e80-994f-11eb-9f3e-e6dffabf8ae7.png)
Adobe Digital Edition打开正常
![image](https://user-images.githubusercontent.com/12640565/114151135-64f25000-994f-11eb-9826-b7b7c9e97ec1.png)
软件导入正常
![image](https://user-images.githubusercontent.com/12640565/114151223-7d626a80-994f-11eb-9198-1738a88086aa.png)
文件显示异常
![image](https://user-images.githubusercontent.com/12640565/114151176-6face500-994f-11eb-9083-cd3b2b510ee3.png)
导航栏无法跳转

文件链接如下：
链接：https://pan.baidu.com/s/1cp-Lj16VvcQN0KiDV-hnwQ 
提取码：01ue 
-->

**Comment by troyeguo** [comment]
百度网盘下载时提示下载的内容包含违规信息，您可以用其他方式再分享一下吗？我的邮箱是 guo362429@gmail.com

**Comment by simonecho** [comment]
> 百度网盘下载时提示下载的内容包含违规信息，您可以用其他方式再分享一下吗？我的邮箱是 [guo362429@gmail.com](mailto:guo362429@gmail.com)

已发到邮箱，麻烦留意查收，谢谢！

**Comment by troyeguo** [comment]
感谢您提供的文件，这个问题 Koodo Reader 可能暂时没办法解决，这个软件依赖Epub.js库解析epub文件，我尝试了多个依赖epub.js的软件，都存在同样的问题。您可以前往epub.js的Github仓库提交issue: https://github.com/futurepress/epub.js

**Comment by simonecho** [comment]
> 感谢您提供的文件，这个问题 Koodo Reader 可能暂时没办法解决，这个软件依赖Epub.js库解析epub文件，我尝试了多个依赖epub.js的软件，都存在同样的问题。您可以前往epub.js的Github仓库提交issue: https://github.com/futurepress/epub.js

那估计是文件本身的问题吧，放弃了，准备换个格式再试试
