### ISSUE TITLE
打开PDF文件使用的是浏览器界面

### ISSUE THREAD

**Issue by XUPTLiYipeng** [troyeguo/koodo-reader#113]
_首先表达我对开发者的敬意，感谢开发出界面如此友善的Epub/Mobi阅读器_
但是有一点 还是美中不足：
PDF文件打开，好像还是浏览器的界面。我用koodo打开pdf居然和和火狐浏览器打开pdf界面是一样的
所以是koodo对于PDF目前直接调用浏览器的吗？

**Comment by troyeguo** [comment]
您好，Koodo 的pdf阅读器的代码是直接从火狐官方仓库那里直接复制粘贴过来的，虽然外观一样，但并没有调用浏览器，还是用Koodo Reader打开的文件，代码来源：https://github.com/mozilla/pdfjs-dist
这个软件主要是针对Epub阅读开发的，pdf阅读不是重点功能，所以没有自己开发
