### ISSUE TITLE
macbook M1 芯片  安装arm版后显示已损坏，无法打开

### ISSUE THREAD

**Issue by Jinl-k** [troyeguo/koodo-reader#115]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |       macos big sur 11.3beta版    |
| App Version (应用版本)      |      1.2.4     |

---

## Bug details (具体描述)

![image](https://user-images.githubusercontent.com/39037760/114305300-2f459680-9b0a-11eb-811d-862940033708.png)

**Comment by troyeguo** [comment]
我没在macos上做过测试，这里有一些我百度到的解决办法，你可以试一下，如果没用我也没办法了。

https://www.jianshu.com/p/05c46eea19bf
https://www.macdo.cn/925.html
https://zhuanlan.zhihu.com/p/114919138

**Comment by Wink233** [comment]
> 我没在macos上做过测试，这里有一些我百度到的解决办法，你可以试一下，如果没用我也没办法了。
> 
> https://www.jianshu.com/p/05c46eea19bf
> https://www.macdo.cn/925.html
> https://zhuanlan.zhihu.com/p/114919138

果然好了  谢谢大佬👍

**Comment by Wink233** [comment]
> 我没在macos上做过测试，这里有一些我百度到的解决办法，你可以试一下，如果没用我也没办法了。
> 
> https://www.jianshu.com/p/05c46eea19bf
> https://www.macdo.cn/925.html
> https://zhuanlan.zhihu.com/p/114919138

还有一个小bug，勾选记住窗口打开大小后，并没有记住窗口大小。
这是我使用的窗口大小
![image](https://user-images.githubusercontent.com/39037760/114306693-34f1ab00-9b0f-11eb-98b6-549bc00cc584.png)
这是我重新打开后的窗口大小
![image](https://user-images.githubusercontent.com/39037760/114306651-01168580-9b0f-11eb-8ed3-0dc0bb603bae.png)

**Comment by troyeguo** [comment]
记住窗口大小需要点击顶部的退出阅读才能生效，直接叉掉窗口不会生效

**Comment by Wink233** [comment]
> 记住窗口大小需要点击顶部的退出阅读才能生效，直接叉掉窗口不会生效
解决了  感谢感谢。
