### ISSUE TITLE
mac版进入全屏幕页面会跳转到桌面而非停留在打开的书籍页面上

### ISSUE THREAD

**Issue by hzqqy** [troyeguo/koodo-reader#116]
ps：cmd+w关闭当前打开的书页后书架还是无法弹出，是否可以再设置留一个书架常驻的选项

**Comment by troyeguo** [comment]
请使用bug report issue 模板重新提交，并提供截图或录像等相关描述，另外koodo暂不支持快捷键操作，退出阅读建议点击退出阅读按钮
