### ISSUE TITLE
打开每本书都有闪屏现象

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#118]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |           |
| App Version (应用版本)      |           |

---

## Bug details (具体描述)

版本 macos 11.2.3 

打开每本书的时候,书籍会打开关闭一下,类似于闪屏,很不舒服,希望能解决,谢谢

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题的
