### ISSUE TITLE
希望UI界面能够美化提升

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#119]
## Details (解释)

作为设计师,非常喜爱这个软件,能够提升UI视觉体验将会更好,我有如下几点建议:

1.app的icon标识立体化,而且更加突出书籍的感觉,现在类似脑图
2.收起侧边栏按钮应该作为设置选项,不应该常驻
3.侧边栏icon和文字间距离过远,而且icon和文字还有不水平居中对齐的情况,而且侧边栏几行的间距过大
4.app上面使用的是线条的icon,但是侧边栏又使用色块icon,不统一
5.搜索,排序,我的书架,卡片模式应为一组,同步,导入,备份恢复为一组,非常用的设置应单独为一组,现在感觉逻辑有点乱
6.颜色上,主色选用了灰白,但是侧边栏图标确实黑色,而且顶部菜单栏的灰又和主色的灰色不一致
7.侧边栏和按钮使用的大圆角矩形,但是我的书架又使用的是小圆角矩形,且文字不居中,空白多,并且我的回收里面"清空所有图书"又不是圆角
8.整体是扁平风格,但是书籍显示有时阴影写实,建议书籍外套细灰色边框,取消阴影
9.文字字号种类太多,建议差不多大小的字号统一一下
10.右上角卡片模式的两个icon和文字也是不是水平居中

以上是我个人的一些不成熟看法,有用的地方你们可以看情况采纳,谢谢

**Comment by troyeguo** [comment]
感谢您提供的专业的建议，这个软件主要是按照我自己的审美，基本上是边开发边设计的，没有过多考虑字号，icon，设计风格统一的问题，并且开发过程中要考虑汉语，英语，俄语的排版问题， icon设计，我没有太多的经验，当初主要考虑的是辨识度的问题，欢迎提交您喜爱的设计图标；侧边栏设计主要参考了 Google Keep，其他的问题也会根据您的建议做相应的调整的。

**Comment by pxz666** [comment]
希望着重改变图书阴影美化的问题,现在白框+大阴影的方式,不好看。
建议可以参考苹果ibook的方式,不要白框,阴影大小缩小。
<img width="181" alt="截屏2021-04-18 15 48 10" src="https://user-images.githubusercontent.com/16777825/115138231-81803d80-a05d-11eb-8926-c4f6e72eb4ed.png">

**Comment by troyeguo** [comment]
感谢的您的建议，审美的问题比较主观，现在的阴影大小为10px，主要是为了突出图书，这个数值经过多次测试，个人觉得目前的数值比较合适
