### ISSUE TITLE
手机浏览器适配

### ISSUE THREAD

**Issue by necoic** [troyeguo/koodo-reader#12]
大佬啥时候能让网页版适配手机浏览器阿 好东西 喜欢的不要不要的

**Comment by troyeguo** [comment]
您好！感谢您的建议
这个项目适配手机浏览器难度有点大，因为功能和页面比较复杂，不过后续可能会开发移动端App
最后感谢您的建议，祝您生活愉快

**Comment by 0x01x0** [comment]
哎妈呀 你这个语气好像大公司客服 难道是可道云的新项目?

**Comment by troyeguo** [comment]
哈哈，只是想表示的礼貌一点，专业一点，我现在还在上学。

**Comment by lzhga-tx** [comment]
求大佬适配手机
