### ISSUE TITLE
非PDF格式书籍封面美化问题

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#120]
## Details (解释)

非PDF格式书籍封面是一堆文字,非常影响观感
希望能自动提取标题,生成简单封面

**Comment by troyeguo** [comment]
感谢您的反馈，会考虑在后续版本增加这个功能

**Comment by pxz666** [comment]
非PDF格式书籍封面有没有可能搜刮豆瓣图片自动生成?

**Comment by pxz666** [comment]
应该是所有书都能搜刮豆瓣封面,软件的美观性可以提升一个档次

**Comment by troyeguo** [comment]
豆瓣不提供公开的api，暂时没有这个打算
