### ISSUE TITLE
M1芯片1.2.5版本可以安装，无法打开。

### ISSUE THREAD

**Issue by alasion** [troyeguo/koodo-reader#122]
系统版本：macOS Big Sur 11.2.3
打开报错文件已损坏，无法打开。

**Comment by troyeguo** [comment]
这个问题帮助文档里有的
https://www.notion.so/troyeguo/e9c4e5755d564b0db6340eeba6d9ece9?v=7c8fcbed9adf4592ada95cfd593868c9

**Comment by alasion** [comment]
> 这个问题帮助文档里有的
> https://www.notion.so/troyeguo/e9c4e5755d564b0db6340eeba6d9ece9?v=7c8fcbed9adf4592ada95cfd593868c9

三种方法都试了，还是不行啊

**Comment by troyeguo** [comment]
我没在mac系统上测试过，之前也有人反映过这个问题，根据他的说法是可以解决的。还是不行的话您可以选择使用网页版或者使用其他同类软件。
https://github.com/troyeguo/koodo-reader/issues/115

**Comment by troyeguo** [comment]
这个方法你试过吗？看看可不可以
https://www.macdo.cn/925.html

**Comment by polofish84** [comment]
> 这个方法你试过吗？看看可不可以
> https://www.macdo.cn/925.html

xattr -cr /文件位置（直接将应用拖进去即可）

然后再次执行如下指令即可：

codesign --force --deep --sign - /文件位置（直接将应用拖进去即可）

亲测：MacBook pro m1 macos 11.3 这个办法可以！不过目前就是这个版本是这样的，前一个版本可以正常使用！

**Comment by troyeguo** [comment]
> > 这个方法你试过吗？看看可不可以
> > https://www.macdo.cn/925.html
> 
> xattr -cr /文件位置（直接将应用拖进去即可）
> 
> 然后再次执行如下指令即可：
> 
> codesign --force --deep --sign - /文件位置（直接将应用拖进去即可）
> 
> 亲测：MacBook pro m1 macos 11.3 这个办法可以！不过目前就是这个版本是这样的，前一个版本可以正常使用！
> 

会不会是您升级过MacOS导致的，理论上1.2.5相比1.2.4只是外观和软件操作方面的更新，是不会导致软件签名机制发生改变的

**Comment by polofish84** [comment]
> > > 这个方法你试过吗？看看可不可以
> > > https://www.macdo.cn/925.html
> > 
> > 
> > xattr -cr /文件位置（直接将应用拖进去即可）
> > 然后再次执行如下指令即可：
> > codesign --force --deep --sign - /文件位置（直接将应用拖进去即可）
> > 亲测：MacBook pro m1 macos 11.3 这个办法可以！不过目前就是这个版本是这样的，前一个版本可以正常使用！
> 
> 会不会是您升级过MacOS导致的，理论上1.2.5相比1.2.4只是外观和软件操作方面的更新，是不会导致软件签名机制发生改变的

很有可能是big sur 11.3的锅！因为11.3的时候，我用1.2.4没有任何问题，而更新1.2.5就出现这个问题了！所以估计是11.3修改了签名机制导致的！

**Comment by alasion** [comment]
> > 这个方法你试过吗？看看可不可以
> > https://www.macdo.cn/925.html
> 
> xattr -cr /文件位置（直接将应用拖进去即可）
> 
> 然后再次执行如下指令即可：
> 
> codesign --force --deep --sign - /文件位置（直接将应用拖进去即可）
> 
> 亲测：MacBook pro m1 macos 11.3 这个办法可以！不过目前就是这个版本是这样的，前一个版本可以正常使用！

按照这个方法搞定了，多谢
