### ISSUE TITLE
The book default to open in windowed full screen

### ISSUE THREAD

**Issue by J-Siu** [troyeguo/koodo-reader#124]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) | MacOS          |
| App Version (应用版本)      |  1.2.5         |

---

## Bug details (具体描述)

1. Run Koodo Reader
2. Drag a mobi format book to Koodo Reader
3. The book default to open in windowed full screen

It should not open to full screen, or there should be an option.

**Comment by troyeguo** [comment]
Thanks for your feedback, you can turn on the remember window's size option in the setting to avoid opening book in full screen.

**Comment by J-Siu** [comment]
I kind of figure that out, but before that, it was quite annoying, LOL!

**Comment by troyeguo** [comment]
Thanks for the feedback, we will turn this option on as default in the next version.
