### ISSUE TITLE
Ebook content disapper after resizing window height

### ISSUE THREAD

**Issue by J-Siu** [troyeguo/koodo-reader#125]
## Enviroment (操作环境)

Key(名称)|Value(值)|
---|---
Operating System (操作系统)|MacOS 11.3
App Version (应用版本)|1.2.5

---

## Bug details (具体描述)

1. Import a mobi book into Koodo
2. Open the book
3. Resize window height

Before resizing:

![Screen Shot 2021-04-26 at 10 40 51 PM](https://user-images.githubusercontent.com/3171920/116177002-14b21680-a6e1-11eb-9272-11b8e106beb4.png)

After resizing height content disappeared:
![Screen Shot 2021-04-26 at 10 41 04 PM](https://user-images.githubusercontent.com/3171920/116177047-25fb2300-a6e1-11eb-817d-18af957b9c6c.png)

**Comment by troyeguo** [comment]
Thanks for your feedback, we will resolve this issue in the next version.
