### ISSUE TITLE
Where does Koodo sync to?

### ISSUE THREAD

**Issue by J-Siu** [troyeguo/koodo-reader#126]
Where does Koodo sync to?

Currently when I click the sync icon it said "synced successfully" at the bottom. But there is no setting for sync.

**Comment by troyeguo** [comment]
You need to manually change the storage location to the same sync folder of your Onedrive or Dropbox on different computers.  You need to click the sync button to sync your data, Koodo Reader will automatically upload or download the data according the timestamp. So basically sync is based on third-party cloud drive services. This function is still in beta phase.

**Comment by troyeguo** [comment]
Currently it syncs to the location specified in the setting

**Comment by J-Siu** [comment]
hmm, it is very unclear with the current screen. Maybe hide it till the feature + ui is more ready.

**Comment by troyeguo** [comment]
We will show some tips to the user about this function in the upcoming version.
