### ISSUE TITLE
Why we need backup?

### ISSUE THREAD

**Issue by J-Siu** [troyeguo/koodo-reader#127]
I just installed Koodo and the way I use ebook reader is either open via file finder dialog or drop the book into the reader. I did the later with Koodo.

So I am curious what the backup is for.

**Comment by troyeguo** [comment]
It's to prevent data loss and help you easily transfer your data between different computers.

**Comment by J-Siu** [comment]
hmm, this is like the sync function, the UI is very unclear what it is doing.

**Comment by troyeguo** [comment]
Backup function will backup all your data into a zip file. so you can have different version of data and easily share it, but the data file can be heavy depending on your library and may take some time to upload to your cloud drive.
