### ISSUE TITLE
Resize window width has no effect on content

### ISSUE THREAD

**Issue by J-Siu** [troyeguo/koodo-reader#128]
## Envirment (操作环境)

Key(名称)|Value(值)|
---|---
Operating System (操作系统)|MacOS 11.3
App Version (应用版本)|1.2.5

---

## Bug details (具体描述)

1. Import a mobi book into Koodo
2. Open the book
3. Resize window width

Before resize width:

![Screen Shot 2021-04-26 at 10 53 50 PM](https://user-images.githubusercontent.com/3171920/116177760-64451200-a6e2-11eb-9774-fdd89308c925.png)

After resize width

![Screen Shot 2021-04-26 at 10 53 56 PM](https://user-images.githubusercontent.com/3171920/116177775-6c04b680-a6e2-11eb-978b-5fc71a521719.png)

**Comment by troyeguo** [comment]
You need to change page scale to resize the content. This option can be found on right panel.

**Comment by J-Siu** [comment]
My question is unclear. It can be divided into 2 things:

1. Zoom page wide to window width, so basically everything is bigger in the page
2. Page width increase, text site don't change, so more text per line. like web page

I am interested in 2. However, I can't do 1 either, because seems every control on the right panel will close the book. Basically not usable now.

**Comment by troyeguo** [comment]
Increasing page scale seems to already fit what you described in 2. This bug happens when koodo trys to refresh the page, all the changes have been saved and will take into effect when you reopen the book.
