### ISSUE TITLE
Click flow icon will close book

### ISSUE THREAD

**Issue by J-Siu** [troyeguo/koodo-reader#129]
## Envirment (操作环境)

Key(名称)|Value(值)|
---|---
Operating System (操作系统)|MacOS 11.3
App Version (应用版本)|1.2.5

---

## Bug details (具体描述)

1. Import a mobi book into Koodo
2. Open the book
3. Click the icon circled in red below will close the book

![Screen Shot 2021-04-26 at 10 55 57 PM](https://user-images.githubusercontent.com/3171920/116177959-c0a83180-a6e2-11eb-9cb9-51db7a7d9f82.png)

**Comment by troyeguo** [comment]
Thanks for your feedback, we will resolve this issue in the next version.
