### ISSUE TITLE
意外发现了这个，支持下！

### ISSUE THREAD

**Issue by gears233** [troyeguo/koodo-reader#13]
不过有几点操作方面的问题，仅作为个人用户提下建议。（以下内容均基于网页版）

1.  翻页功能，目前试了下。支持的是鼠标滚轮和方向键翻页，不知道有没有支持鼠标点击翻页 或者 干脆滚轮一滚到底的打算 ?

2.  个人的任务栏是位于桌面右侧的，如果要调节字体大小等就容易误触发任务栏，感觉侧栏触发的边距可以放大一些。

不过总体还是很不错的，之前一直用的 https://www.neat-reader.cn  网页版看epub ，现在感觉可以用 koodo reader替代了。

**Comment by troyeguo** [comment]
您好！感谢您的建议：
1）鼠标点击容易和选择文字相互冲突，权衡之下当初就放弃了鼠标点击翻页的方案
2）不太明白滚轮一滚到底这个翻页方案，您可以再说详细一点吗？
3）后续版本会增大侧栏触发的边距的

**Comment by gears233** [comment]
> 您好！感谢您的建议：
> 1）鼠标点击容易和选择文字相互冲突，权衡之下当初就放弃了鼠标点击翻页的方案
> 2）不太明白滚轮一滚到底这个翻页方案，您可以再说详细一点吗？
> 3）后续版本会增大侧栏触发的边距的

嗯，是我描述的不太详细。滚动的这个需求主要考虑的是正常网页浏览时候，人的视线能较长时间保持在屏幕中间左右的位置。
您可以想象您正在阅读一篇很长很长的新闻稿，正常网页浏览的时候肯定是随着阅读进度，鼠标一直往下滚动，滚动到页面底部，这篇新闻稿就读完了。
不过考虑到章节长度等，可以考虑按章节切割页面，就是单次滚动到底的操作能完成一个章节的阅读。

**Comment by troyeguo** [comment]
好的，明白了，会考虑在后续的版本中添加这个功能的
