### ISSUE TITLE
ubuntu20.04 不能全屏，最大化与最小化按钮也是灰的，点不了

### ISSUE THREAD

**Issue by braddw1** [troyeguo/koodo-reader#130]
点了进入全屏后，文字就跑右边去了，但是阅读的窗口并没有全屏
![image](https://user-images.githubusercontent.com/31195709/116241820-e3e0e880-a797-11eb-8168-240f5b4d9a8c.png)
最大化按钮也不能点击
![image](https://user-images.githubusercontent.com/31195709/116241880-f3603180-a797-11eb-9f96-1a31f12255b6.png)

**Comment by troyeguo** [comment]
我没在Linux上做过测试，暂时也没办法调试Linux上的问题，这个看起来更像是Electron与Ubuntu的兼容性问题造成的，可以试一下其他格式的安装包，看看是不是也有这个问题。
