### ISSUE TITLE
单栏模式下，文章宽度太小，浏览起来不太方便。

### ISSUE THREAD

**Issue by seggp** [troyeguo/koodo-reader#131]
希望增加，单栏模式，宽度设置，能调到适合自己阅读的宽度。
不知道在设置里的页边距是不是这个设置。
但是我设置后，页面并没有反应。
系统：
![image](https://user-images.githubusercontent.com/69777591/116344345-a8d2c980-a818-11eb-9b35-326e85610806.png)

**Comment by troyeguo** [comment]
您好，单栏模式的选项在左侧菜单栏的顶部，有三种阅读模式可供选择，可以调整页面缩放这个选项来修改宽度
