### ISSUE TITLE
有人使用该开源软件盈利!

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#132]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |           |
| App Version (应用版本)      |           |

---

## Bug details (具体描述)

盗版地址
https://ereader.link/?utm_source=github&utm_medium=github&utm_campaign=github
mac简版

**Comment by troyeguo** [comment]
感谢您的反馈，正在和作者交涉中

**Comment by troyeguo** [comment]
感谢您的反馈，已经和作者交涉过了，他的软件是基于1.2.2的版本开发的，该版本的Koodo Reader使用MIT授权，因此是允许的闭源开发付费软件的，所以算不上是侵权，但从1.2.5版本开始，Koodo Reader开始使用 Creative Commons Attribution-NonCommercial License，这个协议不再允许商用，原则上就不再允许使用本软件牟利了。最后感谢您对Koodo Reader的支持。
