### ISSUE TITLE
Built-In Updater And/Or Auto-Update

### ISSUE THREAD

**Issue by drkui** [troyeguo/koodo-reader#134]
## Brief Introduction (介绍)

Please include a built-in updater feature and/or auto-update.

## Details (解释)

This would make it simple to update without having to download the setup exe every time there is an update.

**Comment by troyeguo** [comment]
Thanks for your advice, we will add this feature in the future.

**Comment by troyeguo** [comment]
Auto update requires signature certificate to work properly，which costs a lot of money，so we are not planning to support it in the foreseeable future.
