### ISSUE TITLE
mobi格式排版有问题

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#135]
mobi格式排版有问题
<img width="1680" alt="截屏2021-05-04 10 37 28" src="https://user-images.githubusercontent.com/16777825/116955327-d14d3e80-acc4-11eb-8a38-44869179f72d.png">

mac bigsur

**Comment by troyeguo** [comment]
感谢您的反馈，可以麻烦您发一下mobi格式的源文件吗？

**Comment by pxz666** [comment]
不支持这个格式的上传,我可以通过邮箱发给你

**Comment by troyeguo** [comment]
邮箱：guo362429@gmail.com
