### ISSUE TITLE
使用体验反馈 希望改进

### ISSUE THREAD

**Issue by Insvl1129** [troyeguo/koodo-reader#136]
- 设置能多一些
- 
- 左右侧边栏锁定,锁定阅读
- 
- 增加一个显示或隐藏书名的选项
- 
- 开放翻页设置，增加翻页快捷键
- 
- 默认搜索引擎写着谷歌实际是百度
- 
- 打开超链接希望能关闭弹窗或增加可选项
- 
- 打开书籍的时候,主程序界面能最小化到系统托盘,只保留阅读界面,目前关闭主界面,阅读界面会自动退出

**Comment by Insvl1129** [comment]
6. 希望能锁定阅读模式,左右侧边栏锁定.

7.开放翻页设置,增加翻页快捷键

**Comment by troyeguo** [comment]
您好，侧边栏可以锁定，菜单栏顶部有上锁按钮，左边侧边栏最下面有隐藏页眉页脚的选项，可以隐藏书名，可以通过上下左右方向键翻书，搜索引擎设置在设置弹窗中的最下面，超链接的这个需求没太明白您的意思，可以主程序可以最小化，阅读界面可以保留
