### ISSUE TITLE
CBZ/CBR/CB7/CBT, FB2, DjVU, and MarkDown support

### ISSUE THREAD

**Issue by BrandonKMLee** [troyeguo/koodo-reader#137]
Brief Introduction: There are other formats of ebooks that exists out there, for Comics, it is CB*, and for serious documents, DjVU or MarkDown.

Details:

**Comment by troyeguo** [comment]
Thanks for your advice, we will consider supporting these formats in the future.

**Comment by BrandonKMLee** [comment]
Also for reference: https://github.com/sumatrapdfreader/sumatrapdf

**Comment by troyeguo** [comment]
Thanks for the reference, but i want to remind you that Koodo is built on Electron and Javascript which are technically different from these projects. We are still not sure whether supporting to these formats is achievable in Koodo. But it's definitely on our list.

**Comment by BrandonKMLee** [comment]
- https://github.com/RussCoder/djvujs
- https://github.com/markedjs/marked
- https://github.com/afzafri/Web-Comic-Reader https://github.com/codedread/kthoom (since CBZ is based on ZIP files of comic panels)

**Comment by BrandonKMLee** [comment]
@troyeguo could you show me the repos responsible for MOBI and DJVU?
I am looking into https://github.com/troyeguo/koodo-reader/issues/146
