### ISSUE TITLE
Open ebook by Koodo

### ISSUE THREAD

**Issue by BrandonKMLee** [troyeguo/koodo-reader#139]
Operating System: Windows 10

App Version: 1.2.5

Bug details: Launch unimported Ebook on the App does not work.

**Comment by troyeguo** [comment]
Double click to open a book only works when Koodo is not running in the background. This is something we are still trying to resolve.

**Comment by BrandonKMLee** [comment]
@troyeguo does not work when it is not running in the background (no tray icon or tab).

**Comment by troyeguo** [comment]
Have you set Koodo Reader as the default reader for your books? It works fine on my computer. You should see a orange icon for your epub file if you have set Koodo as the default.
<img width="603" alt="捕获" src="https://user-images.githubusercontent.com/13820674/117577336-f524e000-b11b-11eb-8f23-1be72545bdb7.PNG">

**Comment by BrandonKMLee** [comment]
yep, I did, the app launched but it refused to show the contents. so there is a response but not a "proper" one

**Comment by troyeguo** [comment]
Have you seen an loading animation showing characters jumping. Some screenshot or video would help me better navigate the problem. If you do, then probably problem is with the book you're opening. 

Here are some demo books  you can test with: https://www.dropbox.com/sh/md6fcpitaosj52p/AACGQLNdC9XsJu57uO1HWnf_a?dl=0

**Comment by BrandonKMLee** [comment]
@troyeguo first the spinner/loading screen pops up, then it pops back to the main catalog screen, there is no reader screen to speak of.

**Comment by BrandonKMLee** [comment]
@troyeguo tested both the test EPUB and personal EPUBs. same result of double click => launch => loading => goes to main screen "books" page

**Comment by troyeguo** [comment]
I've record a video to show how double click to open a book works on my computer. Does all the books get successfully imported after double click. If not, maybe it has something to do with your computer. 

https://user-images.githubusercontent.com/13820674/117648914-5c737c00-b17e-11eb-9ede-fe9656b4d739.mp4

**Comment by BrandonKMLee** [comment]
It refused to import.
