### ISSUE TITLE
win10版本操作卡顿

### ISSUE THREAD

**Issue by Jasonfranchise** [troyeguo/koodo-reader#14]
真的感谢作者的努力，让我对于epub文件有了很好的阅读体验也离开了WPS的疯狂弹窗，但对于win10版本的卡顿是显而易见的。加油啊，star奉上了。

**Comment by troyeguo** [comment]
您好！
请问卡顿是整个软件都很卡顿还是部分操作卡顿，您可以提供一下您的电脑配置吗？由于这个软件是基于Electron开发的，所以是会比一般的软件占用更多的内存。我的电脑64位，4g内存，i3处理器运行还是比较流畅的。

**Comment by wxlovesis** [comment]
我使用的是其它软件打包的EPUB，用你的软件或者网页版打开之后，封面处一直灰色闪烁没有响应
[我使用的是其它软件打包的EPUB，用你的软件或者网页版打开之后，封面处一直灰色闪烁没有响应](url)

**Comment by troyeguo** [comment]
如果不是标准的epub文件，确实会出现这种问题，暂时没有很好的解决办法，后续的版本中我会增加对这个问题的提示，目前的话，您下载这个文件 https://ws28.cn/f/3askcf95qal，然后使用备份恢复功能，用这个文件覆盖你本地的数据来解决这个问题，给您带来的不便敬请谅解。

**Comment by troyeguo** [comment]
> 我使用的是其它软件打包的EPUB，用你的软件或者网页版打开之后，封面处一直灰色闪烁没有响应
> [https://ftp.bmp.ovh/imgs/2020/08/ff166c0fc2d3ef9c.png](url)

如果不是标准的epub文件，确实会出现这种问题，暂时没有很好的解决办法，后续的版本中我会增加对这个问题的提示，目前的话，您下载这个文件 https://ws28.cn/f/3askcf95qal   然后使用备份恢复功能，用这个文件覆盖你本地的数据来解决这个问题，给您带来的不便敬请谅解。

**Comment by wxlovesis** [comment]
> > 我使用的是其他软件打包的EPUB，用你的软件或者网页版本打开之后，封面处一直灰色闪烁没有响应
> > [https://ftp.bmp.ovh/imgs/2020/08/ff166c0fc2d3ef9c.png](url)
> 
> 如果不是标准的epub文件，确实会出现这种问题，暂时没有很好的解决方法，后续的版本中我会增加对这个问题的提示，目前的话，您下载这个文件[https://ws28.cn/ f / 3askcf95qal](https://ws28.cn/f/3askcf95qal) 然后使用备份恢复功能，用这个文件覆盖你本地的数据来解决这个问题，给您带来的不便敬请谅解。

感谢，已经下载新版本解决了，另外能不能增加在阅读界面可以用回车键返回至目录页或是主页

**Comment by troyeguo** [comment]
> > > 我使用的是其他软件打包的EPUB，用你的软件或者网页版本打开之后，封面处一直灰色闪烁没有响应
> > > [https://ftp.bmp.ovh/imgs/2020/08/ff166c0fc2d3ef9c.png](url)
> > 
> > 
> > 如果不是标准的epub文件，确实会出现这种问题，暂时没有很好的解决方法，后续的版本中我会增加对这个问题的提示，目前的话，您下载这个文件[https://ws28.cn/ f / 3askcf95qal](https://ws28.cn/f/3askcf95qal) 然后使用备份恢复功能，用这个文件覆盖你本地的数据来解决这个问题，给您带来的不便敬请谅解。
> 
> 感谢，已经下载新版本解决了，另外能不能增加在阅读界面可以用回车键返回至目录页或是主页

好的，感谢您的建议，会在下个版本中增加这个功能的
