### ISSUE TITLE
书摘

### ISSUE THREAD

**Issue by Kevinzgithub** [troyeguo/koodo-reader#140]
我的操作系统是：window10

Koodo Reader 的版本是：最新版本

我遇到的问题是：点选文字，点书摘后，在黑夜模式下，所选文字反白无法辨别文字，另外还自动退回到主界面，而不是正在阅读的界面。

截图或录像(可选)：

图书的下载链接(可选)：

**Comment by troyeguo** [comment]
书摘高亮的颜色是可以选择的，选择蓝色的话情况会好一些，退回主界面这个问题会在下个版本中修复

**Comment by Kevinzgithub** [comment]
明白了，非常感谢！

Zhao LiQing
Be adventurous, be bold, be careful, be a star !

     On Thursday, May 13, 2021, 09:40:39 AM GMT+8, Troye Guo ***@***.***> wrote:  
 
 


书摘高亮的颜色是可以选择的，选择蓝色的话情况会好一些，退回主界面这个问题会在下个版本中修复
