### ISSUE TITLE
颜色无法读取

### ISSUE THREAD

**Issue by tybha** [troyeguo/koodo-reader#147]
我的操作系统是：windows10

Koodo Reader 的版本是：1.2.6

我遇到的问题是：背景颜色的数值无法读取,它不会在点击时移动到相应的数值,因此既不能将这种颜色根据rgb使用在别的地方,也不能进行微调

截图或录像(可选)：

图书的下载链接(可选)：

**Comment by troyeguo** [comment]
您好，可以提供一下您操作时的录像吗，我这边测试是正常的。

**Comment by tybha** [comment]
> 

https://user-images.githubusercontent.com/84333145/118650482-16ba5180-b817-11eb-9ebd-9a19d8e6d64b.mp4

**Comment by troyeguo** [comment]
您是说读取Koodo自带的背景颜色的数值吗？这个没法通过色板来读取，您可以使用取色软件，这里有rgba的值供您参考
export const backgroundList = [
  "rgba(255,255,255,1)",
  "rgba(44,47,49,1)",
  "rgba(233, 216, 188,1)",
  "rgba(197, 231, 207,1)",
];

**Comment by troyeguo** [comment]
后面会增加在现有背景颜色基础上调节的功能

**Comment by tybha** [comment]
谢谢
