### ISSUE TITLE
“进入全屏”BUG

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#148]
Operating System:
Windows10
App Version:
1.2.6

全屏后未显示全屏，依旧提示“进入全屏”
![image](https://user-images.githubusercontent.com/57058325/118620317-f7f89280-b7f7-11eb-9c1a-c23678b7f97f.png)

**Comment by actforjason** [comment]
点击目录条目好像也不太灵

**Comment by troyeguo** [comment]
全屏确实存在这个问题，会在下一个版本修复的，点击目录可能是您的图书的问题，您可以使用测试文件测试一下
https://wwa.lanzoui.com/b0c91w2yb
密码:1234

**Comment by actforjason** [comment]
我已经回退至1.2.5版本:smile:，目录没问题就行
