### ISSUE TITLE
windows版，怎么翻页啊？

### ISSUE THREAD

**Issue by teraStars** [troyeguo/koodo-reader#15]
鼠标单击，双击，右击，都没法翻页。
键盘pagedown也没法翻页

想看看帮助，发现没有帮助。

**Comment by troyeguo** [comment]
您好，
正常情况下，是可以通过鼠标滚轮和键盘上的上下左右键都可以实现翻页。因为不太清楚您这边的具体情况，我这边测试是没问题，给您带来的不便敬请谅解。

**Comment by teraStars** [comment]
> 您好，
> 正常情况下，是可以通过鼠标滚轮和键盘上的上下左右键都可以实现翻页。首次启动应用时的欢迎页中包括了阅读器的基本使用方法，因为不太清楚您这边的具体情况，我这边测试是没问题，给您带来的不便敬请谅解。

总算搞明白是这么翻页的，你这个翻页和其它程序都不一样，是不是应该专门写下来？最好和现在手机上的阅读软件习惯一致。

**Comment by kafuuchino-s** [comment]
请问可以支持一下surface点击屏幕翻页吗

**Comment by troyeguo** [comment]
@kafuuchino-s 
您好，
感谢您的建议，后续会增加专门的翻页按钮的
