### ISSUE TITLE
APP图标不美观

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#150]
简单介绍：
mac bigsur

细节描述：

APP图标不美观,希望能根据主流设计优化一下
![image](https://user-images.githubusercontent.com/16777825/118629068-cf749680-b7ff-11eb-8b90-38a426b6c60c.png)

**Comment by troyeguo** [comment]
您好，请问您是使用最新版的Koodo Reader吗？1.2.6的图标应该是圆角矩形的。
<img width="333" alt="捕获" src="https://user-images.githubusercontent.com/13820674/118632832-642cc380-b803-11eb-9df0-93a649537c81.PNG">

**Comment by pxz666** [comment]
是最新的
![image](https://user-images.githubusercontent.com/16777825/118633366-fb921680-b803-11eb-86a5-4fbc2a97fc7f.png)

**Comment by troyeguo** [comment]
可能是big sur的问题，会在后续版本修复的

**Comment by troyeguo** [comment]
您好，我在big sur上测试了一下，图标是正常的，您可以再尝试卸载重装一下，看看能不能解决，记得备份数据
