### ISSUE TITLE
搜索我的书库功能不能用

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#151]
我的操作系统是：

mac bigsur 

Koodo Reader 的版本是：

最新

我遇到的问题是：

搜索我的书库没有作用,显示空白

截图或录像(可选)：
![image](https://user-images.githubusercontent.com/16777825/118630564-33e42580-b801-11eb-8299-f57af2a4c535.png)

图书的下载链接(可选)：

**Comment by troyeguo** [comment]
感谢您的反馈，确实存在这个问题，会在后续版本中修复的
