### ISSUE TITLE
希望能增加书籍标签功能

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#152]
简单介绍：

如今社会信息量太大,很多书可能只是阅读一部分,或者只是暂时存放,书籍管理成为高效阅读的重要部分。
书籍分类不应该仅依赖大类来区分,也可以使用标签来帮助管理。

另外我认为软件不应该局限于阅读器,阅读是手段,更加有效低摩擦的吸收知识才是目标,希望软件中带有有效阅读理念的思考,从更高的层次思考这款软件,例如FLOMO这个app就给了我一些新的启发。

谢谢,仅个人意见供参考,纯属瞎说。

细节描述：

**Comment by troyeguo** [comment]
感谢您的建议，图书标签功能已经在开发计划中了
https://www.notion.so/troyeguo/215baeda57804fd29dbb0e91d1e6a021?v=360c00183d944b598668f34c255edfd7
