### ISSUE TITLE
书籍堆栈功能

### ISSUE THREAD

**Issue by pxz666** [troyeguo/koodo-reader#153]
简单介绍：

细节描述：
有些书籍是一个套装,但下载下来确实一本一本的,如果能实现堆栈功能,将套装图书合并在一起,将会简化书架信息量,提升体验。

**Comment by troyeguo** [comment]
您可以使用书架功能来整理图书，这个功能实现起来比较难，如果后续有比较多人有这个需求的话，会考虑添加的
