### ISSUE TITLE
关于翻译框偶尔想逃出屏幕的问题

### ISSUE THREAD

**Issue by AntaresShao** [troyeguo/koodo-reader#155]
我的操作系统是：
`Windows 10 20H2` <br/>
Koodo Reader 的版本是：
`Koodo-Reader-1.2.6-Portable.exe` <br/>
我遇到的问题是：
- 那个翻译功能不能完全保留在屏幕里，如果翻译的内容在边上的话翻译框有一部分就出去了。

截图或录像(可选)：<br/>
- 随便选了一本书的一句演示一下。<br/>

<img width="395" alt="Snipaste_2021-05-19_21-29-55" src="https://user-images.githubusercontent.com/79731222/118821925-471ef000-b8ea-11eb-8335-0aa486cef912.png">

图书的下载链接(可选)：
- 和是哪本书并没有关系hhhh

**Comment by troyeguo** [comment]
感谢您的反馈，如果选的文字靠近边缘，就会发生这样的情况，会在后续版本解决这个问题的
