### ISSUE TITLE
关于翻译只能被限制在一段以内的问题

### ISSUE THREAD

**Issue by AntaresShao** [troyeguo/koodo-reader#157]
是的又是我，又是和翻译相关的问题。（我的上一个问题→#155） 
我的操作系统是：
`Windows 10 20H2`
Koodo Reader 的版本是：
`1.2.6-Portable`
我遇到的问题是：
一旦翻译的范围跨越了一段，翻译就会出错。
截图或录像(可选)：
这里翻译一段是可以的：
![不跨段](https://i.loli.net/2021/05/22/YqchxBTmng7sfur.png)

然后一旦越过段分隔：
![出错了](https://i.loli.net/2021/05/22/OrtekcK3EpSlYLi.png)
上面这是两段。

![又出错辽](https://i.loli.net/2021/05/22/NoqrYCtRMmcPhsy.png)
这个是三段。

图书的下载链接(可选)：
啊，依旧莫得关系hhhh

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复这个问题
