### ISSUE TITLE
Need to resize window, everytime i open book.

### ISSUE THREAD

**Issue by HGqK8aekLaPfGB** [troyeguo/koodo-reader#161]
Operating System: fedora 34 , gnome 40

App Version: latest

Bug details: Need to resize window every time to fit screen (full screen doesn't automatic maximize window i manually need to adjust it).

full screen work in browser version.

Screenshot or video (Optional):

![Screenshot from 2021-05-28 23-07-22](https://user-images.githubusercontent.com/84371950/120004830-ceb2e000-c009-11eb-81e4-2c77fee910cc.png)

**Comment by troyeguo** [comment]
Thanks for the feedback, this bug seems to be operating system related. Ubuntu users reported similar bug before, we will  look into it.
