### ISSUE TITLE
Unable to open large books

### ISSUE THREAD

**Issue by BrandonKMLee** [troyeguo/koodo-reader#162]
Operating System: Win10

App Version: 1.2.6

Bug details: Trying to launch this book, but the viewer would crash while the catalog screen is still up. https://github.com/KeithAnyan/NeoreactionaryCanon.epub
Other books with less page counts currently work.

Screenshot or video (Optional):

Download link to the ebook (Optional):

**Comment by troyeguo** [comment]
I try to open this book with some other epub readers like Sumatra, Thorium. They can't open this book either. I guess this book is broken already.

**Comment by BrandonKMLee** [comment]
Try doing a wide spectrum test on https://github.com/KeithAnyan
[epub.zip](https://github.com/troyeguo/koodo-reader/files/6592614/epub.zip)

**Comment by troyeguo** [comment]
i did some test on these books, the largest one still has the same issue on some readers，but i did manage to open it with moon+ reader on my phone. This is most likely a parsing problem from upstream library of Epub.js not Koodo itself.
