### ISSUE TITLE
Open Sourec Natural-Sounding TTS

### ISSUE THREAD

**Issue by BrandonKMLee** [troyeguo/koodo-reader#163]
Brief Introduction: There are better natural sounding Text to Speech program out there that can make the experience better

Details of singular models:
https://github.com/mozilla/DeepSpeech and https://github.com/mozilla/TTS
https://github.com/r9y9/deepvoice3_pytorch and https://github.com/r9y9/gantts
https://github.com/Kyubyong/tacotron
https://github.com/NVIDIA/flowtron
https://github.com/descriptinc/melgan-neurips
https://github.com/ming024/FastSpeech2
https://github.com/jaywalnut310/glow-tts
https://github.com/snakers4/silero-models

Details of benchmarks and toolkits:
https://github.com/Picovoice/speech-to-text-benchmark and https://github.com/Picovoice/cheetah
https://github.com/PaddlePaddle/Parakeet

**Comment by troyeguo** [comment]
Thanks for the advice, these projects seem to be all developed with Python. We're not sure whether it will be likely to integrate with Koodo.

**Comment by BrandonKMLee** [comment]
Consider that Mozilla/Firefox is involved there should be a way of executing this for JS.

**Comment by iclementine** [comment]
Thanks for your advise. We are currently working on better voice quality and faster synthesis. Integration with JS will be considerd in the future but now we are not working on it.
