### ISSUE TITLE
书籍打开时/点目录跳转时/跳转下一章时，有时页面空白无反应，需要关闭书籍再次打开

### ISSUE THREAD

**Issue by Breeze-WQ** [troyeguo/koodo-reader#168]
我的操作系统是：win7

Koodo Reader 的版本是：1.2.6

我遇到的问题是：书籍打开时/点目录跳转时/跳转下一章时，有时页面空白无反应，需要关闭书籍再次打开

截图或录像(可选)：

图书的下载链接(可选)：

**Comment by troyeguo** [comment]
最新版中修复了这个问题，您可以更新一下。
