### ISSUE TITLE
👍 好应用，已收录，感谢开发者！

### ISSUE THREAD

**Issue by macwkcom** [troyeguo/koodo-reader#169]
![image](https://user-images.githubusercontent.com/53843550/122954023-ab354800-d3b1-11eb-9ab3-f20268458e41.png)

[收录地址](https://www.macwk.com/soft/koodo-reader)

因为并不是多有开发者都需要被宣传，如果开发者觉得不合适，回复我一下，我把它下掉。🥰

**Comment by troyeguo** [comment]
真的很感谢您的宣传，每次更新之后，增加的访问量基本都是来自您的网站。有更多人用，我才有动力一直维护更新下去。

**Comment by macwkcom** [comment]
> 真的很感谢您的宣传，每次更新之后，增加的访问量基本都是来自您的网站。有更多人用，我才有动力一直维护更新下去。

OK，辛苦辛苦。
