### ISSUE TITLE
网页版排版问题

### ISSUE THREAD

**Issue by steley** [troyeguo/koodo-reader#17]
非全屏状态下排版存在问题
![Selection_038.png](https://i.loli.net/2020/08/30/mIwBNuixej6qL4p.png)

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，这主要是epub文件解析的问题，目前正在进行代码重构以适配最新版的epub解析插件，这个问题预计会在下一个版本更新中解决。

**Comment by steley** [comment]
大佬辛苦了，搭了个网页版用起来挺方便的
