### ISSUE TITLE
Opening EPUB By Double Clicking

### ISSUE THREAD

**Issue by drkui** [troyeguo/koodo-reader#177]
Operating System: Windows 10 Pro x64

App Version: 1.2.7

Bug details: I used to be able to double click on a .epub file and start reading. Now, when I double click an .epub file, I have to first import the book, then I can read. This makes it more inconvenient and being able to quickly read a .epub was one of the features I really liked about Koodo,

Screenshot or video (Optional):

Download link to the ebook (Optional):

**Comment by troyeguo** [comment]
Thanks for your feedback, double clicking to open epub is still working but only under limited circumstance, like when Koodo is running in the background. We are still trying to find out how to work around this.
