### ISSUE TITLE
图书打不开

### ISSUE THREAD

**Issue by lcrazyl** [troyeguo/koodo-reader#178]
我的操作系统是：
Windows10
Koodo Reader 的版本是：
Koodo-Reader-1.2.9.exe
我遇到的问题是：
图书打不开，点击图书后不显示，只有在任务栏预览里可以看到是未加载出来白色的框框
截图或录像(可选)：

图书的下载链接(可选)：

**Comment by troyeguo** [comment]
帮助文档里有这个问题的解决办法
https://www.notion.so/troyeguo/e9c4e5755d564b0db6340eeba6d9ece9?v=7c8fcbed9adf4592ada95cfd593868c9

**Comment by lcrazyl** [comment]
已解决，感谢

**Comment by 275ysys** [comment]
打不开azw3格式文件

**Comment by wajika** [comment]
根据文档提示，清理本地数据。
C:\Users\你的用户名\AppData\Roaming\koodo-reader

好像和安装过程的某个选择有关系
![Uploading wenti.png…]()

**Comment by troyeguo** [comment]
> 根据文档提示，清理本地数据。
> C:\Users\你的用户名\AppData\Roaming\koodo-reader
> 
> 好像和安装过程的某个选择有关系
> ![wenti](https://user-images.githubusercontent.com/17058349/130566742-38c1ee7e-3a49-45c8-b97a-8814e1e3a34b.png)

您好，是因为您在安装过程中选择了为使用这台电脑的任何人安装，所以才出现了图书打不开的问题吗？默认选项是仅为我安装吗？

**Comment by troyeguo** [comment]
> 根据文档提示，清理本地数据。
> C:\Users\你的用户名\AppData\Roaming\koodo-reader
> 
> 好像和安装过程的某个选择有关系
> ![wenti](https://user-images.githubusercontent.com/17058349/130566742-38c1ee7e-3a49-45c8-b97a-8814e1e3a34b.png)

您好，请问默认选择的是仅为我安装吗？

**Comment by VIjinxx** [comment]
![image](https://user-images.githubusercontent.com/38981824/132953736-7cf089dc-167f-49d6-9797-16a2c77cfc8c.png)
试了上面的方法没用，重新安装了也没用，不知道啥情况，昨天还用着好好的。

**Comment by VIjinxx** [comment]
可能是某个设置的问题，我不恢复备份，重新导入书籍还是能打开的，恢复了就不能打开了

**Comment by troyeguo** [comment]
> 可能是某个设置的问题，我不恢复备份，重新导入书籍还是能打开的，恢复了就不能打开了

这个问题在最新的开发版中已经修复，请前往Release下载
