### ISSUE TITLE
css 文件解析

### ISSUE THREAD

**Issue by liuyug** [troyeguo/koodo-reader#18]
试用 https://reader.960960.xyz/

发现不能解析 epub 自带的 css 文件，格式全乱了。

链接: https://pan.baidu.com/s/1DB-qXTvKnK3p7cvLZ_Jedg 提取码: gdmu

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，已经定位到问题的原因了，这个问题预计会在下个版本更新中解决。
