### ISSUE TITLE
Does the WebDav work with Moon Reader?

### ISSUE THREAD

**Issue by Ruthalas** [troyeguo/koodo-reader#180]
[Moon Reader](https://moondownload.com/) is an android app that can save reading location via WebDav.

I'd love to sync between this app and that app, but I am not sure if the way that data is stored is standardized, or if it is unique to each app.

Is there a standard for that such that these apps would inter-operate?

**Comment by troyeguo** [comment]
We are on the process of developing our own android app, Koodo has its own unique way to store data, we're not considering to change that to accommodate other apps.

**Comment by Ruthalas** [comment]
Understood, thank you for the response!

**Comment by muava12** [comment]
> We are on the process of developing our own android app, Koodo has its own unique way to store data, we're not considering to change that to accommodate other apps.

any update on android app?

**Comment by jeekkd** [comment]
> > We are on the process of developing our own android app, Koodo has its own unique way to store data, we're not considering to change that to accommodate other apps.
> 
> any update on android app?


I'm posting to express much interest in an Android app.

Thank you for the wonderful project!
