### ISSUE TITLE
双页阅读却显示单页

### ISSUE THREAD

**Issue by lvzhenbo** [troyeguo/koodo-reader#181]
Operating System:win10 v21H1

App Version:1.2.9

Bug details:双页阅读却显示单页

Screenshot or video (Optional):
![image](https://user-images.githubusercontent.com/32427677/128643438-6e381339-5807-4496-a741-f46647bf4f8e.png)

Download link to the ebook (Optional):所有都是

**Comment by troyeguo** [comment]
双页模式需要窗口满足一定的宽度要求，大概是700多像素，小于这个宽度就只会显示成单页模式

**Comment by lvzhenbo** [comment]
那最好添加一下最小窗口，或者记住打开窗口的大小，每次打开都要调整也太烦了

**Comment by lvzhenbo** [comment]
还有这个问题可能和我的缩放有关，我默认是125%的缩放。
PS：希望软件功能和细节更加完善，差不多能够和calibre或者NeatReader比肩的时候，我应该就能够向几个大的轻小说网站推荐了

**Comment by troyeguo** [comment]
Koodo 默认会记忆窗口大小

**Comment by lvzhenbo** [comment]
额。。。我这边不知道怎么回事，并不会记住窗口大小，无论我怎么拉伸窗口重新打开还是之前大小。而且我认为既然有单双页之分，那么双页情况下就不要出现单页。

**Comment by lvzhenbo** [comment]
![动画](https://user-images.githubusercontent.com/32427677/128809008-91c0db6e-40ca-44c0-9620-3373727528e0.gif)

**Comment by troyeguo** [comment]
这个功能有一个小bug，就是每次关闭之后再打开就会比之前的窗口小一点，你可以把长宽调整的幅度再大一点就可以看到记忆的效果了。预计会在下一个版本中修复这个问题。

**Comment by troyeguo** [comment]
如果您日常使用的窗口大小都小于700像素，建议您切换为单页模式使用

**Comment by lvzhenbo** [comment]
> 这个功能有一个小bug，就是每次关闭之后再打开就会比之前的窗口小一点，你可以把长宽调整的幅度再大一点就可以看到记忆的效果了。预计会在下一个版本中修复这个问题。

好的，谢谢，希望能够尽快修复，毕竟这个还是挺影响使用的

**Comment by CrBoysen** [comment]
在修复了1.3.2无法使用双页模式的问题[https://github.com/troyeguo/koodo-reader/issues/239](url)后的1.3.4的版本中，这个问题又出现了，现在的1.3.6版本问题仍然存在，无论如何调整窗口，最后都是双页的背景，单页的文字，感觉跟宽度无关，因为最大化和全屏也是这样
![image](https://user-images.githubusercontent.com/15997865/144069850-fefa9b91-cd09-4f37-bd51-488c1592f545.png)

**Comment by troyeguo** [comment]
> 在修复了1.3.2无法使用双页模式的问题[https://github.com/troyeguo/koodo-reader/issues/239](url)后的1.3.4的版本中，这个问题又出现了，现在的1.3.6版本问题仍然存在，无论如何调整窗口，最后都是双页的背景，单页的文字，感觉跟宽度无关，因为最大化和全屏也是这样 ![image](https://user-images.githubusercontent.com/15997865/144069850-fefa9b91-cd09-4f37-bd51-488c1592f545.png)

请问您的显示器分辨率是多少，是什么格式的电子书。

**Comment by CrBoysen** [comment]
> > 在修复了1.3.2无法使用双页模式的问题[https://github.com/troyeguo/koodo-reader/issues/239](url)后的1.3.4的版本中，这个问题又出现了，现在的1.3.6版本问题仍然存在，无论如何调整窗口，最后都是双页的背景，单页的文字，感觉跟宽度无关，因为最大化和全屏也是这样 ![image](https://user-images.githubusercontent.com/15997865/144069850-fefa9b91-cd09-4f37-bd51-488c1592f545.png)
> 
> 请问您的显示器分辨率是多少，缩放比是多少，是什么格式的电子书。

破案了，是缩放比的问题，我的显示器是2k分辨率，自定义110%缩放比，看见你的回复我就还原成100%试了下，现在确实没有问题了

**Comment by t828** [comment]
同上
![正常2](https://github.com/koodo-reader/koodo-reader/assets/40261941/041f217b-038e-4008-a077-99f8db9fd4b3)
这个是正常比例（1920*1080），双页正常
![异常2](https://github.com/koodo-reader/koodo-reader/assets/40261941/303897f8-fcc0-40c9-94e5-e6e53b5b3105)
这个是缩放之后，双页强制单页了，这个要怎么调整
我用的是1.6.3版本修改的布局

> > > 在修复了1.3.2无法使用双页模式的问题[https://github.com/troyeguo/koodo-reader/issues/239](url)后的1.3.4的版本中，这个问题又出现了，现在的1.3.6版本问题仍然存在，无论如何调整窗口，最后都是双页的背景，单页的文字，感觉跟宽度无关，因为最大化和全屏也是这样 ![image](https://user-images.githubusercontent.com/15997865/144069850-fefa9b91-cd09-4f37-bd51-488c1592f545.png)
> > 
> > 
> > 请问您的显示器分辨率是多少，缩放比是多少，是什么格式的电子书。
> 
> 破案了，是缩放比的问题，我的显示器是2k分辨率，自定义110%缩放比，看见你的回复我就还原成100%试了下，现在确实没有问题了（ps：电子书是txt）

**Comment by t828** [comment]
> 同上 ![正常2](https://private-user-images.githubusercontent.com/40261941/307653813-041f217b-038e-4008-a077-99f8db9fd4b3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTc4NTQsIm5iZiI6MTcwODk5NzU1NCwicGF0aCI6Ii80MDI2MTk0MS8zMDc2NTM4MTMtMDQxZjIxN2ItMDM4ZS00MDA4LWEwNzctOTlmOGRiOWZkNGIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZWUwNTcwNDM2YmEwY2M0YTYxYTQ1YmQxNDc2MjY0MmY3MTllY2ZmNDgzNWVhNTkxNGUyYTYxYTQxZjllNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m6WWXXVgfFqx5m8Sfo5ONuImnvlDh1-6aadH8YGZrUY) 这个是正常比例（1920*1080），双页正常 ![异常2](https://private-user-images.githubusercontent.com/40261941/307653977-303897f8-fcc0-40c9-94e5-e6e53b5b3105.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTc4NTQsIm5iZiI6MTcwODk5NzU1NCwicGF0aCI6Ii80MDI2MTk0MS8zMDc2NTM5NzctMzAzODk3ZjgtZmNjMC00MGM5LTk0ZTUtZTZlNTNiNWIzMTA1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZmM3ZjM5MzYyN2M2MTM1ODIwZTlhMmI2MmJiNTUyOWRjNTEzZjRjNDllOTM0ZTk5MWQzMjRlYjViMGJmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4vRB9aOKK0HxYN0sJd1_rDkQmZoSbEB9xsNZySGBNhA) 这个是缩放之后，双页强制单页了，这个要怎么调整 我用的是1.6.3版本修改的布局 @troyeguo
> 
> > > > 在修复了1.3.2无法使用双页模式的问题[https://github.com/troyeguo/koodo-reader/issues/239](url)后的1.3.4的版本中，这个问题又出现了，现在的1.3.6版本问题仍然存在，无论如何调整窗口，最后都是双页的背景，单页的文字，感觉跟宽度无关，因为最大化和全屏也是这样 ![image](https://user-images.githubusercontent.com/15997865/144069850-fefa9b91-cd09-4f37-bd51-488c1592f545.png)
> > > 
> > > 
> > > 请问您的显示器分辨率是多少，缩放比是多少，是什么格式的电子书。
> > 
> > 
> > 破案了，是缩放比的问题，我的显示器是2k分辨率，自定义110%缩放比，看见你的回复我就还原成100%试了下，现在确实没有问题了（ps：电子书是txt）

解决了
