### ISSUE TITLE
请问百度统计在这个软件中发挥什么作用，要收集什么数据

### ISSUE THREAD

**Issue by lvzhenbo** [troyeguo/koodo-reader#185]
日常开着抓包软件，突然发现这个软件是联网的，发现是百度统计。这个软件也没有隐私说明，能否详细说说

**Comment by troyeguo** [comment]
帮助文档里有隐私说明，统计功能可以在设置里关闭
https://troyeguo.notion.site/e9c4e5755d564b0db6340eeba6d9ece9?v=7c8fcbed9adf4592ada95cfd593868c9

**Comment by lvzhenbo** [comment]
好的，谢谢
