### ISSUE TITLE
有ios版的app嗎？

### ISSUE THREAD

**Issue by maimailu** [troyeguo/koodo-reader#189]
有ios版的app嗎？我在mac上用這套好用，我的txt檔終於不會亂碼呈現了~

**Comment by troyeguo** [comment]
ios应用的开发成本太高了，个人负担不起。之后会开通捐款渠道，如果可以覆盖这个成本，就会考虑去开发。

**Comment by ale0sx** [comment]
有人有興趣一起做嗎？我有興趣做 iOS 的版本👋

**Comment by polofish84** [comment]
现在不单单可以考虑ios了，安卓的平板今年下半年也开始要爆发了，作者开捐赠通道吧！
