### ISSUE TITLE
图片会展示在俩页

### ISSUE THREAD

**Issue by mchhui** [troyeguo/koodo-reader#19]
在某些情况下
比如图片太高

配图的一部分会跑到另一页去
看起来很奇怪呢
（单页模式也不行哒 因为没有连续平滑的下滑模式啦）
如果能自适应到一页里展示就好了
（虽然可以点开看）

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，图片的问题会在下一个版本更新中解决，后续也会加入滚动阅读的模式
