### ISSUE TITLE
希望增加批量删除图书功能和自由选择是否开启回收站功能

### ISSUE THREAD

**Issue by wanan1234** [troyeguo/koodo-reader#191]
简单介绍：没有批量删除只能一本一本删太烦了，而且有回收站还要进回收站再删一次

细节描述：每次删除都要一一去删，步骤太繁琐，删完后还要进回收站再去删一次，建议增加自由选择是否开启回收站的选项。还有希望改一改鼠标移动到顶部时自动出现的三个功能选项，每次鼠标滑倒上面弹出来很不舒服，改为点击鼠标再弹出来或者干脆取消比较好。鼠标移到底部弹出的进度加载也希望能删除，每次打开图书就看到它一直在加载，加载大半天还挺影响阅读感受的

**Comment by troyeguo** [comment]
感谢您的建议，会考虑增加这些功能的。

**Comment by troyeguo** [comment]
在设置中开启触控模式，菜单栏就不会误触，点击之后，才会弹出。

**Comment by wanan1234** [comment]
原来是这样，非常感谢，困扰我的一大问题解决了
