### ISSUE TITLE
希望EPUB格式的目录固定以及PDF鼠标滚轮能直接翻一页

### ISSUE THREAD

**Issue by qlmlove** [troyeguo/koodo-reader#192]
简单介绍：
1. epub目录遮盖内容
2. PDF可以用鼠标滚轮滚一页
3. PDF设置成水平滚动时候鼠标滚动问题
4. 记住PDF大纲宽度

细节描述：
1. 希望epub格式的**目录锁定后**能够让**内容页**自动**往右边移**一下，而不是现在的固定**目录显示在内容上边遮盖住内容**，最终效果像打开PDF文件并且在左侧显示书签的样子
2. 希望设置里增加PDF文件可以用鼠标滚轮滚一页的功能
3. PDF设置成水平滚动之后建议让鼠标默认能滚动，而不是按住Shift才能滚动，（要不是知道Shift+滚动是水平滚动，估计设置成水平滚动的人都以为这软件坏了）
4. 每次打开PDF之后【文件大纲】的宽度会变成默认大小，而有的书目录比较长，每次都要拖一下，希望能记住【文件大纲】的宽度

**Comment by troyeguo** [comment]
感谢您的建议，epub的阅读体验会改进的，pdf阅读器的代码不是我写的，而是从[这里](https://github.com/mozilla/pdf.js)拷过来的，暂时没有修改的打算。
