### ISSUE TITLE
直接打开书就读，别拷贝到固定目录

### ISSUE THREAD

**Issue by retsyo** [troyeguo/koodo-reader#199]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

直接打开书就读，别拷贝到固定目录；如果作笔记，保存到图书的目录中，与图书同名

### Details

我笔记本上有图书、一个移动硬盘上是漫画和不常用图书。我不把它们全放在笔记本硬盘上，是因为笔记本硬盘放不下；我不把它们全放在移动硬盘里，是因为移动硬盘我不会天天带，常用的文档放笔记本硬盘中方便查看

**Comment by troyeguo** [comment]
感谢您的反馈，会考虑增加这个功能

**Comment by hujian** [comment]
很需要这个功能啊，我自建了一个本地的书库，好几百G的书啊，查资料用的，还有一套自己写的处理，检索用的脚本。现在，就没法找到一个好用的阅读器，关键问题就是，和iBook一样，mac上阅读器很多都有自动拷贝的问题，又没法设置，真的好烦心。

**Comment by hujian** [comment]
很需要这个功能啊，我自建了一个本地的书库，好几百G的书啊，查资料用的，还有一套自己写的处理，检索用的脚本。现在，就没法找到一个好用的阅读器，关键问题就是，和iBook一样，mac上阅读器很多都有自动拷贝的问题，又没法设置，真的好烦心。

**Comment by IzualYang** [comment]
也就是增加一个选项，拷贝的时候“仅创建符号链接”的意思吧。
但是一般阅读软件自动拷贝是有原因的，“如果不拷贝，来源文件可能会被移走”这不是阅读器的问题却又需要阅读器去考虑这个问题。

**Comment by troyeguo** [comment]
最新开发版中增加了以引用的方式导入图书的选项，开启之后就不会复制了

**Comment by wingmancn** [comment]
没有便携化
各种设置都存在\AppData\Roaming\koodo-reader
请来个能放在U盘的版本
