### ISSUE TITLE
导入备份后刷新，白屏

### ISSUE THREAD

**Issue by fcki1984** [troyeguo/koodo-reader#2]
- **问题**
备份导入后，界面白屏

- **过程**
添加一本epub格式书籍，然后备份，删除书籍，重新导入备份，然后刷新，界面白屏。

- **版本**
0.1.6
[网页版](https://troyeguo.gitee.io/koodo-web/)
- **截图**
![image](https://user-images.githubusercontent.com/39592566/78419294-f95c0f80-7676-11ea-9676-238a7e56375f.png)

**Comment by troyeguo** [comment]
感谢反馈，现在修复了。

**Comment by troyeguo** [comment]
网页版，请删除控制台->application->localstorage里的内容，再刷新
桌面版，请卸载旧版本，重装0.1.7版
