### ISSUE TITLE
Text to speech with highlight support

### ISSUE THREAD

**Issue by winterdl** [troyeguo/koodo-reader#203]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Text to speech with highlight support

### Details

Text to speech with highlight support and auto turn page or chapter.

**Comment by troyeguo** [comment]
Thanks for the advice, we will add this feature in the future.

**Comment by troyeguo** [comment]
Thanks for the advice, we will add this feature in the future.
