### ISSUE TITLE
关于官网无法打开并报错DNS_PROBE_FINISHED_NXDOMAIN的问题

### ISSUE THREAD

**Issue by AntaresShao** [troyeguo/koodo-reader#204]
作者你好，我发现我这边Koodo Reader的官网打不开了，不知道是不是出了什么问题。
就是这个网址：https://koodo.960960.xyz/
我这边网页会报错：*DNS_PROBE_FINISHED_NXDOMAIN*

**Comment by troyeguo** [comment]
我这边可以正常访问，ping检测也是正常的，请自行百度解决方案
