### ISSUE TITLE
Web版，文件存储位置问题

### ISSUE THREAD

**Issue by ljw98** [troyeguo/koodo-reader#205]
已经部署好web版，但是电子书存储位置好像并不是拉到项目里面保存，而是暂时的缓存。想知道web版如何修改存储位置(安装其他版本均可在设置里面修改，web没有该选项)，主要是希望部署到nas端，方便看书

**Comment by troyeguo** [comment]
web端不支持修改，只要你不卸载浏览器，web端的数据就会永久保存

**Comment by ljw98** [comment]
这样会有一个问题弊端就是，我已经搭建好网站（图书是保存到服务器上的），现在希望家里用电脑看书就没办法了（因为不是存放于本地）；又或者在外边访问也不能看见图书，这样就有割裂感了。想问问是否有将web版像桌面端可以拉文件，又或者我可以通过修改路径实现相互连通。

**Comment by ljw98** [comment]
对了，我之前在nas的网站写了一下搭建网站的介绍文档，应该没问题吧？
https://post.smzdm.com/p/alx3zklp/

**Comment by troyeguo** [comment]
感谢推广，第五步打包文件的命令写错了是 yarn build，不是 yarn buil
Web端的数据同步功能已经在开发计划中了，敬请期待

> 这样会有一个问题弊端就是，我已经搭建好网站（图书是保存到服务器上的），现在希望家里用电脑看书就没办法了（因为不是存放于本地）；又或者在外边访问也不能看见图书，这样就有割裂感了。想问问是否有将web版像桌面端可以拉文件，又或者我可以通过修改路径实现相互连通。
> 
> 对了，我之前在nas的网站写了一下搭建网站的介绍文档，应该没问题吧？希望你们可以加油，多考虑一下web版，个人感觉可以和Calibre有竞争的实力。
> https://post.smzdm.com/p/alx3zklp/

感谢推广，第五步打包文件的命令写错了是 yarn build，不是 yarn buil
Web端的数据同步功能已经在开发计划中了，敬请期待

**Comment by ljw98** [comment]
感谢回复，上面提到的可能不小心写错了。期待新功能
