### ISSUE TITLE
Fullscreen reading

### ISSUE THREAD

**Issue by amie33r** [troyeguo/koodo-reader#206]
Hello,
Is it possible to make this application to extend the page to the entire screen?
For ex: Koodo displays the epub book as follows

![ghac](https://user-images.githubusercontent.com/75431883/132226130-8512c936-6141-4068-935b-aaecc25b7009.JPG)

and I am asking whether the application can display the epub book like this

![cgh](https://user-images.githubusercontent.com/75431883/132226438-28bf290c-5f50-439f-887c-cf46904ca969.JPG)

**Comment by troyeguo** [comment]
There is a Page Scale option in the right panel, you can adjust the book width from there.

**Comment by amie33r** [comment]
> 
> 
> There is a Page Scale option in the right panel, you can adjust the book width from there.

Thank you for the help.
