### ISSUE TITLE
Flatpak builds

### ISSUE THREAD

**Issue by Lunarequest** [troyeguo/koodo-reader#207]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Flatpaks are a linux distro agnostic  packaging method similar to snaps, unlike snaps these are supported in more linux distros. 

### Details

I've attempted to package this as a flatpak but the main issue is node-sass requires python2 which isn't support anymore. Another issue is the yarn-lock is often out of sync from the actual package list.

**Comment by troyeguo** [comment]
This project is developed on Windows, build issues on other operating systems are out of our capability. Feel free to pull request.

**Comment by Lunarequest** [comment]
closing this issue since its now on flathub

**Comment by troyeguo** [comment]
> @troyeguo Since it's [merged](https://flathub.org/apps/details/io.github.troyeguo.koodo-reader), it would be nice if you add a download badge (https://flathub.org/badges) or so to this repo

We just added the download badge in the Readme, thanks again for the good work.
