### ISSUE TITLE
Support epub 3 footnote

### ISSUE THREAD

**Issue by winterdl** [troyeguo/koodo-reader#208]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Support footnote popup like the above link description.

### Details

https://help.apple.com/itc/booksassetguide/en.lproj/itccf8ecf5c8.html

Support footnote popup like the above link description.

Thank you.

**Comment by troyeguo** [comment]
Don't request features already listed in the roadmap, Thanks!
