### ISSUE TITLE
为什么阅读epub时背景不能是空白

### ISSUE THREAD

**Issue by jichuan254** [troyeguo/koodo-reader#209]
为什么阅读EPUB格式文件的时候非得有个书一样的背景呢？不能是非常原始的一大块空白么？为什么没有这个选项出现呢？是我找的位置错了么？

**Comment by troyeguo** [comment]
右边的菜单可以关掉

**Comment by jichuan254** [comment]
> 右边的菜单可以关掉

不行啊，我又看了一遍，右边的菜单关于背景只有调节背景颜色的选项，可以调节为白色，但是中间那条杠杠还是没法关掉，背景还是那张图啊，没有可以直接关掉的选项。

**Comment by jichuan254** [comment]
> 右边的菜单可以关掉

不行啊，我又看了一遍，右边的菜单关于背景只有调节背景颜色的选项，可以调节为白色，但是背景没有变，仿真图书翻页的背景图片还是在的，无法关掉成为空白，我的软件是官网的最新版

**Comment by troyeguo** [comment]
鼠标滚到最下面，关闭仿真背景

**Comment by jichuan254** [comment]
> 鼠标滚到最下面，不使用仿真背景

没有，我右下角从开启听书到文字阴影一共是五个选项，每个选项后面带开关按钮不假，可惜没有关闭仿真背景的选项，另外说一句我用的是Windows 11，可能是BUG，我今天是第一次使用这个软件，我同样发现的BUG还有底部的菜单栏一直呈现彩色波浪的加载条，无论我等待多久都仍然在加载。

**Comment by troyeguo** [comment]
> > 鼠标滚到最下面，不使用仿真背景
> 
> 没有，我右下角从开启听书到文字阴影一共是五个选项，每个选项后面带开关按钮不假，可惜没有关闭仿真背景的选项，另外说一句我用的是Windows 11，可能是BUG，我今天是第一次使用这个软件，我同样发现的BUG还有底部的菜单栏一直呈现彩色波浪的加载条，无论我等待多久都仍然在加载。

在Epub格式图书才有这个选项，Window11的bug我这边暂时没法调试
<img width="890" alt="捕获" src="https://user-images.githubusercontent.com/13820674/132951907-161af924-48ba-4afe-89bb-1eaa6474a62d.PNG">

**Comment by jichuan254** [comment]
> > > 鼠标滚到最下面，不使用仿真背景
> > 
> > 
> > 没有，我右下角从开启听书到文字阴影一共是五个选项，每个选项后面带开关按钮不假，可惜没有关闭仿真背景的选项，另外说一句我用的是Windows 11，可能是BUG，我今天是第一次使用这个软件，我同样发现的BUG还有底部的菜单栏一直呈现彩色波浪的加载条，无论我等待多久都仍然在加载。
> 
> 在Epub格式图书才有这个选项，Window11的bug我这边暂时没法调试
> <img alt="捕获" width="890" src="https://user-images.githubusercontent.com/13820674/132951907-161af924-48ba-4afe-89bb-1eaa6474a62d.PNG">

对的，我读的是EPUB的，看来完全可能是因为加载条卡住了导致文字阴影底下的菜单无法加载了，虽然你现在无法调试，但是我还是简述现象以备后续参考：进入EPUB图书后，左右两边的菜单都能正常开启（鼠标移动到左右两边就浮出来），但是唯独底部浮出一个带有一个彩色波浪式加载条的方框，然后右边的菜单只显示到文字阴影。

**Comment by troyeguo** [comment]
> > > > 鼠标滚到最下面，不使用仿真背景
> > > 
> > > 
> > > 没有，我右下角从开启听书到文字阴影一共是五个选项，每个选项后面带开关按钮不假，可惜没有关闭仿真背景的选项，另外说一句我用的是Windows 11，可能是BUG，我今天是第一次使用这个软件，我同样发现的BUG还有底部的菜单栏一直呈现彩色波浪的加载条，无论我等待多久都仍然在加载。
> > 
> > 
> > 在Epub格式图书才有这个选项，Window11的bug我这边暂时没法调试
> > <img alt="捕获" width="890" src="https://user-images.githubusercontent.com/13820674/132951907-161af924-48ba-4afe-89bb-1eaa6474a62d.PNG">
> 
> 对的，我读的是EPUB的，看来完全可能是因为加载条卡住了导致文字阴影底下的菜单无法加载了，虽然你现在无法调试，但是我还是简述现象以备后续参考：进入EPUB图书后，左右两边的菜单都能正常开启（鼠标移动到左右两边就浮出来），但是唯独底部浮出一个带有一个彩色波浪式加载条的方框，然后右边的菜单只显示到文字阴影。

好的，感谢反馈

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版
