### ISSUE TITLE
划词菜单简化

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#210]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

划词菜单感觉没必要这么大，不紧凑，可能只需要一排的文字就可以了。

### Details

![image](https://user-images.githubusercontent.com/57058325/132949137-df49ddea-46aa-402e-b628-5e5b82936230.png)

**Comment by troyeguo** [comment]
这个项目不接受UI，使用习惯相关的建议
