### ISSUE TITLE
希望上架微软商店

### ISSUE THREAD

**Issue by moleng09** [troyeguo/koodo-reader#211]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

希望上架微软商店，可以方便二合一用户，也方便付费支持。

### Details

> 在 Windows 11 中，Microsoft Store 最大的一项变化是，只要是可以在 Windows 上运行的应用程序都支持上传到应用商店。原因是微软对新版的 Microsoft Store 进行了架构上的重构，因此商店除了包含 Windows 10 上已有的 UWP 应用外，还支持上架 Win32 应用甚至是 Android 应用。

**Comment by troyeguo** [comment]
感谢您的建议，微软开发者账号要19美元，折合人民币119块，在捐款收入覆盖这个成本之前不会考虑上架，并且开发者不想浪费时间在微软的应用审核上

**Comment by moleng09** [comment]
OK
其实如果有教育邮箱的话，就可以免费申请开发者账号

**Comment by troyeguo** [comment]
> OK
> 其实如果有教育邮箱的话，就可以免费申请开发者账号

我记得这个优惠好几年前就没了
