### ISSUE TITLE
github issue里中文的问题反馈/功能建议提交会报错

### ISSUE THREAD

**Issue by whyjxz14** [troyeguo/koodo-reader#218]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating System

Web

### App Version

无

### Bug Detail

该网页无法正常运作如果问题仍然存在，请与网站所有者联系。
HTTP ERROR 400

### Screenshots (Optional)

![Uploading image.png…]()

**Comment by troyeguo** [comment]
应该时gihub的问题，已经暂时移除了中文的issue模板了

**Comment by troyeguo** [comment]
把 checkbox 中的“是”改成“Yes”就好了，github对中文的支持还是不太行
