### ISSUE TITLE
拖动桌面文件导致误触导入提醒动画却无法取消

### ISSUE THREAD

**Issue by KimYangOfCat** [troyeguo/koodo-reader#229]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统

macOS

### Koodo Reader 版本

1.2.9

### 我遇到的问题

拖动桌面文件导致误触导入提醒动画却无法取消，如图。

目前可行的解决方法是重启软件，或者按提醒导入一本书籍才可取消。

是否考虑增加通过 esc 键或者再次点击界面取消提醒动画的方法？

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/32960305/137034169-e530e4f8-4de4-4a18-9f9a-e0ec3eb4d703.png)

**Comment by troyeguo** [comment]
请安装1.3.1开发版
