### ISSUE TITLE
1.3.2版本以后加入txt文件无法选择双页、单页和滚动模式，默认滚动阅读

### ISSUE THREAD

**Issue by CrBoysen** [troyeguo/koodo-reader#239]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统

Windows

### Koodo Reader 版本

1.3.3

### 我遇到的问题

1.3.2之后加入的txt文件不能再选择双页、滚动或者单页，只能默认滚动阅读。
这个情况在1.3.3仍然存在。
而1.3.1版本添加的txt文件在1.3.2和1.3.3还可以用双页和单页

### 截图或录像(可选的)

![屏幕截图 2021-10-23 221615](https://user-images.githubusercontent.com/15997865/138560298-1982016f-8ad5-447a-9641-eada16ce66e4.png)

### 图书的下载链接(可选的)

任意一个txt小说文件

**Comment by troyeguo** [comment]
您好，请升级到最新1.3.4版，这些功能已经支持了
