### ISSUE TITLE
从本地导入问题

### ISSUE THREAD

**Issue by chinagui** [troyeguo/koodo-reader#24]
### 环境

操作系统：Windows 10
软件版本：1.1.4

### 问题

点击 `从本地导入` 后，选择 epub 文件，软件未导入该文件，也未有任何报错

**Comment by troyeguo** [comment]
您好！
这种情况一般是导入的epub文件有问题，您可以下载一下这本书：https://reader.960960.xyz/assets/demo.epub，再导入一次看看。

**Comment by chinagui** [comment]
感谢回复！
这个 demo.epub 确实可以导入。但是我导入的这个 epub 文档用其他工具（calibre 等）是可以打开的。

**Comment by troyeguo** [comment]
您好！
这种情况我也没有很好的解决办法，epub 解析是由 epub.js 这个库负责的，只能希望 epub.js 后续更新可以解决这个问题。
