### ISSUE TITLE
一个小小的小问题

### ISSUE THREAD

**Issue by Airthink** [troyeguo/koodo-reader#242]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统

Windows

### Koodo Reader 版本

1.3.3

### 我遇到的问题

阅读器全屏后按下ESC退出全屏，阅读界面上端仍然显示"退出全屏"，且点击也没有任何效果，重新打开后又恢复正常

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版
