### ISSUE TITLE
Koodo Reader 1.3.3 not load directly pdf and add in library even disabling that feature

### ISSUE THREAD

**Issue by Augusto7743** [troyeguo/koodo-reader#243]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating System

Linux

### App Version

1.3.3

### Bug Detail

All settings disabled
Clicking in any pdf start Koodo Reader main window, but the pdf not is loaded.
The user need drag drop files in main window.

Enabling "Open book without adding it to library" not work. Any pdf loaded is added to library.

What is the name of Koodo-Reader executable that load directly pdfs ?
Linux Ubuntu 20.04 using Double Commander and PCManFM-QT being the pdf file associated with Koodo Reader.
Koodo Reader main window start, but not load the pdf.

I not understand if devs test before release.
Koodo Reader 1.3.3 loading diretly pdf and not adding in library not work.

**Comment by troyeguo** [comment]
You can try to update to 1.3.4, see if this bug still exists

**Comment by Augusto7743** [comment]
Fixed.
THANKS !!!!!!!!!!!! :)
