### ISSUE TITLE
Key Bindings are Wrong When Creating a Note

### ISSUE THREAD

**Issue by Todd-Fulton** [troyeguo/koodo-reader#244]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating System

Windows

### App Version

1.3.3

### Bug Detail

I've only tested this on epub files.

When creating a note in an epub, and the cursor is in the text editor to create the note, if one presses any of the arrow keys, now including the space-bar, or any other key that would otherwise change the page in the book, the page will change and exit the text editor for creating a note.

The correct behavior should be that the key-bindings are changed to match what is expected in the text-editor mode, i.e. when you press an arrow key, it moves the cursor, or when you press space-bar it creates a space, etc.

Thank you very much, this is one of my favorite ebook readers for epub files so far.

**Comment by troyeguo** [comment]
This bug has been fixed, you can try to update to 1.3.4

**Comment by troyeguo** [comment]
This bug has been fixed, you can try to update to 1.3.4
