### ISSUE TITLE
scoop 支持

### ISSUE THREAD

**Issue by diklios5768** [troyeguo/koodo-reader#245]
是否有办法支持scoop安装

**Comment by diklios5768** [comment]
感谢，我会尝试提交给其他开发者，如果有新的安装方法会联系一下你

**Comment by diklios5768** [comment]
现一共有三个库收录了此软件，感谢
分别是：
https://github.com/CALMorACT/hola_bucket
https://github.com/yuanying1199/scoopbucket
https://github.com/LuoHuiRu/ScoopBucket

**Comment by troyeguo** [comment]
感谢提醒，已经添加了hola_bucket作为安装源，readme也更新了scoop安装方式

**Comment by diklios5768** [comment]
现在知名的dorado库也帮忙添加了本软件
dorado仓库：https://github.com/chawyehsu/dorado
添加方法：
```powershell
scoop bucket add dorado https://github.com/chawyehsu/dorado
scoop install dorado/koodo-reader
```

**Comment by troyeguo** [comment]
> 现在知名的dorado库也帮忙添加了本软件 dorado仓库：https://github.com/chawyehsu/dorado 安装方法：
> 
> ```powershell
> scoop bucket add dorado https://github.com/chawyehsu/dorado
> scoop install dorado/koodo-reader
> ```

好的，感谢反馈
