### ISSUE TITLE
封面识别

### ISSUE THREAD

**Issue by ranminnice** [troyeguo/koodo-reader#248]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [X] Yes

### 这个Issue没有同时提多个需求.

- [X] Yes

### 简单介绍

PDF文件导入之后只有一种默认封面,但是本身文件是有自己的封面的,另外书架也可以添加一下别的风格,类似图片显示的书架以及封面
![image](https://user-images.githubusercontent.com/52843410/139298172-7007044b-e782-4710-b6bd-6178f7021aaf.png)

### 细节描述

如上

**Comment by troyeguo** [comment]
请升级至1.4.0

**Comment by lvgitt** [comment]
> 请升级至1.4.0

1.4啥时候推送到正式版啊？

**Comment by troyeguo** [comment]
> > 请升级至1.4.0
> 
> 1.4啥时候推送到正式版啊？

1.4是开发版，功能不稳定，bug较多，不会作为正式版推送，如果要使用请前往Github Release下载，或者等待稳定版的更新提醒
