### ISSUE TITLE
添加图书批量管理功能

### ISSUE THREAD

**Issue by yanglp1999** [troyeguo/koodo-reader#249]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [X] Yes

### 这个Issue没有同时提多个需求.

- [X] Yes

### 简单介绍

在对书籍加书架以及删除过程中需要挨个点击，需要大量的机械重复操作

### 细节描述

通过添加复选框等方式实现对书籍的批量管理，实现例如批量加书架或者批量删除功能等功能

**Comment by troyeguo** [comment]
多选功能请点击图书左上角的选择

**Comment by troyeguo** [comment]
开发计划里也有，请认真阅读再提交新需求
