### ISSUE TITLE
滚动阅读问题；章节点击问题

### ISSUE THREAD

**Issue by gitbula** [troyeguo/koodo-reader#250]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统

Windows

### Koodo Reader 版本

1.3.4

### 我遇到的问题

1. 滚动阅读时，往回滚动滚轮接近章节开头，会自动跳到前一章的章末，或别的章节。
2. 在目录栏点击章节时，有时会跳到别的地方，特别是第一次点击时。

### 截图或录像(可选的)

https://user-images.githubusercontent.com/93466365/139575408-93d342cd-832f-4541-8faf-b13480de64d7.mp4

**Comment by troyeguo** [comment]
这个问题存在很久了，这个问题可能和epub.js有关，我也不知道具体是什么原因。

**Comment by troyeguo** [comment]
这个问题有个折中的解决办法，就是把无限加载改成按章节加载。

**Comment by mujingling3** [comment]
我遇到了类似问题，但是我找不到无限加载选项。无论是网页还是本地版，选择滚动模式后必须手动加载下一张。这个是要再那里调整呢。

**Comment by troyeguo** [comment]
> 我遇到了类似问题，但是我找不到无限加载选项。无论是网页还是本地版，选择滚动模式后必须手动加载下一张。这个是要再那里调整呢。

会在后续版本中增加这个设置，目前只支持无限加载
