### ISSUE TITLE
页数跳转

### ISSUE THREAD

**Issue by gitbula** [troyeguo/koodo-reader#251]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [ ] Yes

### 这个Issue没有同时提多个需求.

- [ ] Yes

### 简单介绍

能否阅读页面底下的进度选项的本章页数和章节数框上添加跳转功能？

### 细节描述

![屏幕截图 2021-10-31 170633](https://user-images.githubusercontent.com/93466365/139575628-d520af84-e6ad-440c-837e-fa9033170212.jpg)

**Comment by troyeguo** [comment]
本章页数的跳转暂时没有好的实现方式，章节数的跳转输入数字，然后在菜单的其他位置点击一下，就可以实现了
