### ISSUE TITLE
Dark Text display [Brightening issue]

### ISSUE THREAD

**Issue by gosndka** [troyeguo/koodo-reader#255]
Hello, I don't if this is bug or not but when I try to open an epub book, the text display darkens and it is very difficult to read. for reference you can see this images below:

![Capture](https://user-images.githubusercontent.com/92586328/139648213-f8175366-24d7-40c6-8c2a-f6c1f883ac18.JPG)

![ghb](https://user-images.githubusercontent.com/92586328/139648232-c7bc36dc-a1ed-4ef1-8fe7-c8fd11714ad9.JPG)

Is it possible to brighten the text? like this

![gbh](https://user-images.githubusercontent.com/92586328/139648544-8ebf3675-97d5-4ddf-8d8e-931a12ae17db.JPG)

**Comment by troyeguo** [comment]
You may have accidentally adjusted the brightness in the right menu

**Comment by gosndka** [comment]
> 
> 
> You may have accidentally adjusted the brightness in the right menu

Can you tell me what I should do? And I didn't do anything other than update the app from 1.3.0 to the latest version 1.3.4
