### ISSUE TITLE
希望docker部署的能提供多用户功能

### ISSUE THREAD

**Issue by HelIwalker** [troyeguo/koodo-reader#256]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [X] Yes

### 这个Issue没有同时提多个需求.

- [X] Yes

### 简单介绍

希望docker部署的能提供多用户功能

### 细节描述

管理员账号可以管理其他子用户账号

**Comment by troyeguo** [comment]
您好，请问这个需求是处于什么考虑？具体的应用场景是什么样的？

**Comment by HelIwalker** [comment]
> 您好，请问这个需求是处于什么考虑？具体的应用场景是什么样的？

我也想分享给朋友用我部署在服务器上的koodo，每个人可以独立管理自己上传的书籍笔记，现在的功能只适合单人使用

**Comment by troyeguo** [comment]
> > 您好，请问这个需求是处于什么考虑？具体的应用场景是什么样的？
> 
> 我也想分享给朋友用我部署在服务器上的koodo，每个人可以独立管理自己上传的书籍笔记，现在的功能只适合单人使用

Koodo只是一个本地阅读器，只要访问同一个域名，每个人就可以管理和阅读自己独立的电子书。所有人的数据互不相通。

**Comment by HelIwalker** [comment]
> > > 您好，请问这个需求是处于什么考虑？具体的应用场景是什么样的？
> > 
> > 
> > 我也想分享给朋友用我部署在服务器上的koodo，每个人可以独立管理自己上传的书籍笔记，现在的功能只适合单人使用
> 
> Koodo只是一个本地阅读器，只要访问同一个域名，每个人就可以管理和阅读自己独立的电子书。所有人的数据互不相通。

原来如此，明白了，非常感谢
