### ISSUE TITLE
批量操作图书这个功能完成了么？

### ISSUE THREAD

**Issue by winbug** [troyeguo/koodo-reader#257]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统

Windows

### Koodo Reader 版本

1.3.4

### 我遇到的问题

无法批量删除图书，
开发计划中看到批量操作已经完成，不知道批量删除是否完成？

**Comment by troyeguo** [comment]
请点击图书列表左上角的选择按钮
