### ISSUE TITLE
PDF暂时不支持笔记、批注功能吗？

### ISSUE THREAD

**Issue by MrThinco** [troyeguo/koodo-reader#259]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统

Windows

### Koodo Reader 版本

1.3.4

### 我遇到的问题

您好，我在官方demo中https://koodo-reader.vercel.app/，上传了pdf，但是选中文字后，没有笔记弹窗，没法书写笔记。下载最新1.3.4版本代码本地运行也不支持pdf笔记和备注。360浏览器，edge浏览器。请问最新版本支持，pdf书写笔记和注释吗？并且支持导出含笔记的PDF吗，谢谢。

### 截图或录像(可选的)

![1636001846(1)](https://user-images.githubusercontent.com/18733305/140260342-1f67bafb-660f-4e81-9b94-048fa09722f0.png)
![image](https://user-images.githubusercontent.com/18733305/140260343-7c3f6e6a-0884-46dc-bb12-fb26245ef692.png)

**Comment by troyeguo** [comment]
Koodo暂不支持该功能，会考虑增加这个功能，不过也不知道能不能实现

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版

**Comment by Sun12Xq** [comment]
1.6.5版Koodo Reader能够支持PDF笔记、批注功能吗？
