### ISSUE TITLE
关于语音朗读的改进建议

### ISSUE THREAD

**Issue by duxueminsi** [troyeguo/koodo-reader#261]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [X] Yes

### 这个Issue没有同时提多个需求.

- [X] Yes

### 简单介绍

我在使用koodo时注意到了语音阅读这个功能，这和calibre、xodo相比已经很不错了，但是我想是否可以更优化一些。

### 细节描述

edge浏览器在最近的更新中新增了read aloud大声读功能。该功能几乎涵盖了所有的语言，尤其是其中的xiaoxiao中文女声最受欢迎。（https://microsoftedgetips.microsoft.com/zh-cn/?form=MA13DX）

我正在做一些英文设计杂志的数据采集工作，在52论坛上找到的一款接口软件帮了我很大的忙。（https://www.52pojie.cn/forum.php?mod=viewthread&tid=1492932&highlight=read%2Baloud）

我想，在koodo中是否可以实现相似的功能。期待你的跟新！

**Comment by troyeguo** [comment]
您好，技术原因，Koodo无法支持调用Edge的语音接口。

**Comment by troyeguo** [comment]
第二个链接的软件本质上是把Edge浏览器作为内置浏览器调用，这在本项目中无法实现
