### ISSUE TITLE
1.3.4版本遇到操作bug

### ISSUE THREAD

**Issue by polofish84** [troyeguo/koodo-reader#265]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.3.4

### 我遇到的问题

1、同一段路如果第一次选择可有操作窗口，但是没有选择操作，第二次再选择同一段路就不会出现操作窗口。
复现步骤如下：比如选择的段落文字如下：正在默默的行动，第一次鼠标选取行动，第二次再选取行动就不会有，如果是第一次选择“的行动”，第二次选择“行动”就有，然后再回“的行动”就有了
2、上个版本txt文档，目录正常生成，但是再次打开目录就没有了！
3、当前打开页面切换背景色不生效，下次打开才可以生效

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这些bug，第二问题建议删除之前导入的电子书，重新导入一遍，新版本对目录生成逻辑进行了修改器，对旧版本可能不兼容

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版
