### ISSUE TITLE
没有在打开书籍前进行文件是否存在的判断

### ISSUE THREAD

**Issue by Nexfia** [troyeguo/koodo-reader#266]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10及以下

### Koodo Reader 版本

1.3.4

### 我遇到的问题

似乎在打开书籍文件的时候没有进行文件是否存在的判断。
我将koodo生成的电子书文件从磁盘删除了，在koodo再打开这本书时一直在加载，而并非提醒文件已被删除。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑增加这个功能的

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版
