### ISSUE TITLE
1.34导入txt小说文件，每章节最后部分不显示

### ISSUE THREAD

**Issue by Asake2018** [troyeguo/koodo-reader#268]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.34

### Bug Detail

1.34导入txt小说后，双页浏览模式下，基本每个章节后面的那么一小部分不显示，直接跳到下一章。
而且，按方向键左，会直接跳到上一章的开头，以前的版本是跳回上一页。
用1.31导入txt小说，再用1.34浏览，就没有上述问题。

**Comment by winbug** [comment]
出现同样的问题，现在只能将显示模式改成滚动状态进行访问。

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这些问题的

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版
