### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by timka** [troyeguo/koodo-reader#269]
I'm having trouble figuring out navigation keyboard shortcuts (next/prev page). I'm on OS X 10.15. Is it Ctrl+Right/Left, which I have mapped for other things, or am I missing something?

**Comment by troyeguo** [comment]
You can press up, right or space key for next page, down or left key for prev page.

**Comment by timka** [comment]
Thanks for the response. For some reason no shortcuts were functioning at first. Then I tried changing this and that in the settings and now these are working. Maybe it has something to do with full-screen.

Sorry, no sure how to reproduce.
