### ISSUE TITLE
请加入简转繁功能，谢谢。

### ISSUE THREAD

**Issue by aneterw** [troyeguo/koodo-reader#270]
### I've read Koodo's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

请加入简转繁功能，谢谢。

### Details

请加入简转繁功能，谢谢。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑增加这个功能的

**Comment by troyeguo** [comment]
请更新到1.3.5版
