### ISSUE TITLE
Koodo Reader 1.3.4 not loading directly a type of pdf

### ISSUE THREAD

**Issue by Augusto7743** [troyeguo/koodo-reader#271]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [ ] Yes

### I've already read the Q&A document, still can't solve it.

- [ ] Yes

### Operating system or browser

Ubuntu

### App Version

1.3.4

### Bug Detail

Koodo Reader 1.3.4 in Ubuntu 20.04.3 64 bits.
Linux Version 1.3.3 not load directly pdf files and was fixed in version 1.3.4, but have some types of PDF files not being loaded directly in Koodo Reader.
Please download the pdf below and try open and see if Koodo Reader start loading directly the pdf.
http://www.atarimania.com/documents/atari_comic_centipede.pdf

Thanks for read.

**Comment by troyeguo** [comment]
Thanks for the feedback, we will fix it in the next update

**Comment by Augusto7743** [comment]
@troyeguo
Please you can reply me if the pdf file below had issues ?
Only to understand if has any problem in OS.

**Comment by nn6v6nn** [comment]
@Augusto7743 　I can open your pdf file directly on Windows 10 .

**Comment by troyeguo** [comment]
Sorry for the late reply, we do have the same issue. It seems like this bug only happens when the book is larger than 10 MB and in some lower version Win 10 OS. It has been fixed in the latest 1.3.5 update.
