### ISSUE TITLE
导出书籍时候失败

### ISSUE THREAD

**Issue by aflyingnoob** [troyeguo/koodo-reader#272]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [x] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.5

### 我遇到的问题

导出epub书籍为一个1kb文件，失败，但是备份时候可以导出所有书籍正确的。

**Comment by aflyingnoob** [comment]
[](url
![微信截图_20211129203539](https://user-images.githubusercontent.com/30976978/143869221-9bb47098-0c6c-4597-884d-9e55164801d7.png)
![微信截图_20211129203556](https://user-images.githubusercontent.com/30976978/143869236-1cb749b8-70b1-48c5-8ac8-12451efcb90a.png)
)

**Comment by troyeguo** [comment]
感谢反馈，会在下个版本中修复这个问题
