### ISSUE TITLE
azw3 格式全部显示乱码

### ISSUE THREAD

**Issue by law625** [troyeguo/koodo-reader#277]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10及以下

### Koodo Reader 版本

1.3.7

### 我遇到的问题

阅读 azw3 格式全部显示乱码

### 截图或录像(可选的)

![Uploading image.png…]()

### 图书的下载链接(可选的)

本地磁盘

**Comment by troyeguo** [comment]
请查看帮助文档了解原因及解决办法
https://troyeguo.notion.site/Koodo-Reader-0c9c7ccdc5104a54825dfc72f1c84bea

**Comment by Crzq** [comment]
我也是这样

**Comment by troyeguo** [comment]
这个问题我这边暂时没有很好的解决办法

**Comment by IzualYang** [comment]
没啥好办法吧，我自购或KU的azw3，用eBookDRMRemovalBundle解除DRM后也是这样。
只能用Calibre或kindleunpack.exe转成epub了

**Comment by AntaresShao** [comment]
@troyeguo 我导入用[最新的DeDRM工具](https://github.com/noDRM/DeDRM_tools)解除DRM之后的AWZ3的时候，显示暂不支持此图书，都没机会看到乱码。这是正常的吗？🥲
<img width="297" alt="image" src="https://user-images.githubusercontent.com/79731222/172667806-dbda44a3-1f76-4050-921c-7a2ec30dec0d.png">

**Comment by troyeguo** [comment]
这个问题暂时没法解决，只能提示这个，和drm没关系，是压缩算法的问题
