### ISSUE TITLE
Koodo Reader browser setting

### ISSUE THREAD

**Issue by its-crypted** [troyeguo/koodo-reader#278]
So I've tried koodo reader it's amazing. But I've noticed something that in a book if I click on a link, the page opens in the same window and not in my default browser. The thing is it does not go back, I need to close the window and reopen the book. I can't see any option of
changing the browser in setting. So anyone has any idea about how to open links in direct default browser? or If the link opens in the same window as book is, then how to switch back to book without closing the window?

**Comment by troyeguo** [comment]
Thanks for the feedback, this looks a bug. We will fix it in the next update.

**Comment by its-crypted** [comment]
@troyeguo
This is the book I've attached [linuxnewbieguide]( https://linuxnewbieguide.org/wp-content/uploads/2016/07/The-Ultimate-Linux-Newbie-Guide-eBook-Edition-January-2017.pdf). You can download it & test as per required.

**Comment by troyeguo** [comment]
Please update to 1.3.9
