### ISSUE TITLE
CSS 文件内嵌字体

### ISSUE THREAD

**Issue by liuyug** [troyeguo/koodo-reader#28]
看到 CSS 内嵌 图片可以正常显示
但 CSSl 内嵌字体不能工作

epub.js 的 demo ，都可以正常显示。

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，这个软件显示图书内容会使用我设置的默认字体-Arial字体，之前确实没有考虑过epub内嵌字体的问题，后续会针对这个问题做进一步优化的。
