### ISSUE TITLE
MOBI格式文件在书架中没有封面，段落首行的缩进也不见了

### ISSUE THREAD

**Issue by pqwer99** [troyeguo/koodo-reader#281]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

MOBI格式文件在书架中没有封面，段落首行的缩进也不见了。
一个建议，书籍内容所在页面能与目录相对应。

**Comment by troyeguo** [comment]
mobi文件不支持封面，右侧阅读菜单中开启首行缩进
