### ISSUE TITLE
WebDav备份失败

### ISSUE THREAD

**Issue by xulingran** [troyeguo/koodo-reader#282]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the Q&A document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.3.9

### Bug Detail

尝试使用 WebDav 备份时一直卡在请稍候，更换了坚果云和自建可道云都存在这个问题

### Screenshots (Optional)

![](https://pic.xulingran.cn/imgs/2021/12/7a2f06c9c1f43257.jpeg)

**Comment by troyeguo** [comment]
您可以通过网速监测软件，看是否有数据在上传，再检查账号密码是否正确

**Comment by xulingran** [comment]
xmeters显示koodo reader的网速为0kbps，且账号密码确认过也是没问题的
系统为win10 工作站 21H2

**Comment by troyeguo** [comment]
您可以检查一下云端是否已经有Koodo Reader的文件夹，删除书库中体积较大的图书，先看看一两本书能不能正常上传。

**Comment by xulingran** [comment]
云端没有文件夹，书库中只有一本书，也无法上传

**Comment by troyeguo** [comment]
> 云端没有文件夹，书库中只有一本书，也无法上传

我这边测试正常，您可以换台电脑试试，我也不清楚原因，后续版本会增加调试功能。

**Comment by xulingran** [comment]
通过`RaiDrive`使用相同的链接、账户、密码是可以正常使用群晖的webdav的，但是在`koodo`上就无法上传，一直卡在请稍后界面，但上传至坚果云又是可以的

**Comment by gouxinxuan** [comment]
自建可道云遇到了相同的问题。打开控制台看接口返回是404，但是如果是windows的文件管理直接连可道云进行文件创建和传输都是没有问题的

**Comment by troyeguo** [comment]
请查看帮助文档，了解如何使用群晖的webdav服务

**Comment by i-iooi-i** [comment]
> 请查看帮助文档，了解如何使用群晖的webdav服务

升级到了最新版1.4.2，在网页端点击使用webdav，提示：网页版受到浏览器限制。。。🥲
