### ISSUE TITLE
排序功能失效

### ISSUE THREAD

**Issue by meinvtuzai** [troyeguo/koodo-reader#284]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [ ] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

批量加入了一些mobi格式的书籍，设置按书名&升序方式排列，但是重新启动后又不是按书名&升序方式排列了，为啥不能保存呢？每次重新设置很麻烦。

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复这个问题

**Comment by troyeguo** [comment]
请升级至1.4.0
