### ISSUE TITLE
不是有calibre了吗，不过还是挺好的，

### ISSUE THREAD

**Issue by JossSong** [troyeguo/koodo-reader#285]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [X] Yes

### 这个Issue没有同时提多个需求.

- [X] Yes

### 简单介绍

如果能推送到kindle就可以考虑了。

### 细节描述

平时都是用kindle看书，不知道有没有推送到kindle开发计划

**Comment by troyeguo** [comment]
Koodo定位是本地阅读器，不做任何依赖服务器的功能

**Comment by suliveevil** [comment]
如果能直接对接Calibre的书库就好了

**Comment by rheatin** [comment]
> Koodo定位是本地阅读器，不做任何依赖自建服务器的功能

大佬，这种本地阅读器应该是一个人在不同设备的无缝使用😄，以后会不会有在服务器缓存的功能？手机网页版以后会适配吗？（可能对于我来说更需要的是在不同设备的网页端做无感切换，继续阅读。现在这种同步方式，对于我来说可能还不如我记录我看到哪里，再在不同的端，搜索到该位置）
