### ISSUE TITLE
摸鱼模式是什么样子的啊？

### ISSUE THREAD

**Issue by gqjwan** [troyeguo/koodo-reader#286]
我按步骤操作后按F12没有变化。

**Comment by troyeguo** [comment]
开启之后，窗口背景会完全透明，只看得到文字。bug反馈请按照bug反馈的issue模板重新提交

**Comment by sangshuduo** [comment]
升级到 1.5 摸鱼模式不透明了，没找到哪里有开关，我是 Windows 11
