### ISSUE TITLE
【win10web版】在电脑重启后，上传的书籍不见了

### ISSUE THREAD

**Issue by wayheng** [troyeguo/koodo-reader#287]
在win10使用web版上传了书籍，每次电脑重启后，书籍就都不见了。
请问书籍和阅读的记录是如何做管理的？目前还没有找到相关的说明。

**Comment by troyeguo** [comment]
Web版的图书，理论上只要不卸载浏览器就永久保存。

**Comment by Hub-848** [comment]
> Web版的图书和阅读记录，理论上只要不卸载浏览器就永久保存。不太清楚您这边是什么情况。

在Ipad的Safari浏览器上点了书籍以后只能弹出菜单，书籍没有办法打开，开启触控屏模式也没有用，是不是不支持用平板的Web端呢

**Comment by troyeguo** [comment]
> > Web版的图书和阅读记录，理论上只要不卸载浏览器就永久保存。不太清楚您这边是什么情况。
> 
> 在Ipad的Safari浏览器上点了书籍以后只能弹出菜单，书籍没有办法打开，开启触控屏模式也没有用，是不是不支持用平板的Web端呢

Koodo没有为平板的Web端做优化，建议使用Chrome浏览器打开网页版

**Comment by troyeguo** [comment]
> 在win10使用web版上传了书籍，每次电脑重启后，书籍就都不见了。 请问书籍和阅读的记录是如何做管理的？目前还没有找到相关的说明。

请使用bug反馈的issue模板重新提交

**Comment by wayheng** [comment]
目前只用Chrome浏览器最新版访问该网站，经常会清空浏览器的缓存，不知道是不是因为这个导致的

**Comment by troyeguo** [comment]
> 目前只用Chrome浏览器最新版访问该网站，经常会清空浏览器的缓存，不知道是不是因为这个导致的

应该是这个原因，清理缓存也会把图书数据清空

**Comment by troyeguo** [comment]
> Web版的图书和阅读记录，理论上只要不卸载浏览器和清理网站的缓存数据就永久保存。不太清楚您这边是什么情况。

**Comment by wayheng** [comment]
目前似乎只能安装pc版来解决问题了，工作时常需要清空缓存
