### ISSUE TITLE
无法移动小说页面

### ISSUE THREAD

**Issue by JoyViolet** [troyeguo/koodo-reader#288]
想请问一下如何移动阅读中的小说界面，我只能移动小说书架，小说阅读模式下我只能通过不断的从左右上角缩放扩大移动到所需要的位置
还有小说阅读界面我移动到电脑双屏里的另一分屏，页面变得奇怪，上下章翻页跑出界面之外，不知道是什么原因
摸鱼模式下边框有一条白线，不知道该如何把他隐藏了
望指教
![image](https://user-images.githubusercontent.com/94156528/145135521-8266a497-8f9b-4943-ad84-6c218db05769.png)

**Comment by troyeguo** [comment]
不太理解您的意思，如果有视频录像会更加方便理解。白线是滚动模式下的滚动条，您可以切换为单页模式，就看不到滚动条了

**Comment by JoyViolet** [comment]
不是滚动条，是页面四条边

**Comment by JoyViolet** [comment]
还有看小说的时候有最小化和关闭键吗，我找不到，只能从任务栏里关闭。
我刚才发现我小说解析以后少了一章，但是我手机打开是完整的，不知道是什么原因
我最大的问题就是小说打开以后，那个界面不知道怎么调节才能像其他软件一样左右移动
还有如果界面缩的过小，小说不能滚动看
![image](https://user-images.githubusercontent.com/94156528/145167336-cbabff23-85c1-42e8-b1a3-f91f596a6ecb.png)
![image](https://user-images.githubusercontent.com/94156528/145167361-cef8f9cd-de4c-4120-b837-77899f0e317e.png)

**Comment by troyeguo** [comment]
如果您开启了摸鱼模式，就不能移动窗口，页面的四条边是图书的仿真背景，在右侧菜单中关闭。请参考帮助文档如何开启摸鱼模式，以及摸鱼模式的目的。

**Comment by troyeguo** [comment]
章节缺失的问题，可能是章节名没有识别出来，但章节本身应该还在。麻烦您提供以下这本书，方便改进目录识别算法。

**Comment by JoyViolet** [comment]
原来如此，因为本人主要使用CAD画图，界面一般是黑色或者33,40,48,所以想问下可否全透明
翻页按钮隐藏以后怎么翻页？滚动页面我只能在一章里滚动，日后可否有一直滚动的可能性呢

**Comment by JoyViolet** [comment]
[重生七零：媳妇有点辣 by青青柳色.txt](https://github.com/troyeguo/koodo-reader/files/7674770/by.txt)

**Comment by troyeguo** [comment]
> 原来如此，因为本人主要使用CAD画图，界面一般是黑色或者33,40,48,所以想问下可否全透明 翻页按钮隐藏以后怎么翻页？滚动页面我只能在一章里滚动，日后可否有一直滚动的可能性呢

隐藏阅读背景之后，开启摸鱼模式就是全透明，只能看到文字的状态。滚动模式下请用鼠标滚轮翻页，切换章节只能去目录。或者切换为单页模式，滚动鼠标自动翻页和换章。以后会考虑增加无限滚动功能。

**Comment by troyeguo** [comment]
图片上传失败了，我这边看不到
