### ISSUE TITLE
PDF书籍没有封面

### ISSUE THREAD

**Issue by jbdjbd432** [troyeguo/koodo-reader#292]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [X] Yes

### 这个Issue没有同时提多个需求.

- [ ] Yes

### 简单介绍

建议增加PDF书籍的封面编辑功能，或者默认调用书籍的第一页为封面。谢谢

### 细节描述

建议增加PDF书籍的封面编辑功能，或者默认调用书籍的第一页为封面。谢谢

**Comment by troyeguo** [comment]
感谢您的建议，会在后续版本增加这个功能

**Comment by troyeguo** [comment]
请升级至1.4.0
