### ISSUE TITLE
雙擊開啟圖書功能被其他閱讀器攔截

### ISSUE THREAD

**Issue by s881116s** [troyeguo/koodo-reader#293]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

當電腦安裝了[BOOK WALKER PC客戶端](http://bookwalker.jp/info/u-pc/)（下面簡稱BW閱讀器）後，雙擊開啟圖書卻是打開BW閱讀器，安裝BW閱讀器之前都是正常的。
然而更匪夷所思的是，即便指定系統用KOODO READER打開EPUB（見截圖），還是打開了BW閱讀器。
但是不使用這項功能，單純打開KOODO READER就一切正常。
不太清楚被BW閱讀器攔下來的原因，但BW閱讀器似乎沒辦法設定不開啟本地EPUB，而且也已經停止維護，希望大佬看看有沒有辦法解決。

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/58220190/145596268-689396c8-fbd0-4b0d-bb0c-ee927a4ba06d.png)
![image](https://user-images.githubusercontent.com/58220190/145596380-4ad7ffaa-3a9a-4ac5-bace-74968ab95631.png)

### 图书的下载链接(可选的)

本地EPUB都會遇到這個問題

**Comment by troyeguo** [comment]
您可以在epub图书上右键，重新选择默认打开方式为Koodo Reader
