### ISSUE TITLE
无法使用群晖的

### ISSUE THREAD

**Issue by a472691** [troyeguo/koodo-reader#294]
### 我已经阅读了Koodo的开发计划，没有找到类似的需求

- [ ] Yes

### 这个Issue没有同时提多个需求.

- [ ] Yes

### 简单介绍

我想把书籍保存在群晖上，群晖上安装了webdav服务，但是始终无法正常同步，总是卡在请稍后画面半天都没反应

### 细节描述

而且能否自定义设置保存的文件夹

**Comment by troyeguo** [comment]
请问坚果云webdav能否正常同步

**Comment by i-iooi-i** [comment]
我也遇到了相同的问题，群晖里面使用webdav点击恢复，就会一直停留在恢复页面，而书籍并没有被下载恢复出来。

**Comment by troyeguo** [comment]
请查看帮助文档

**Comment by i-iooi-i** [comment]
> 

晓得了，网页版不支持webdav。

但是我下载的绿色版，在Win上使用群晖的 Koodo使用备份和恢复都是可以实现数据互传。
不过我在mac上安装了 Koodo，同样使用群晖的 Koodo点击备份和恢复，就一直停留在“请稍后”页面，然后就没有任何反应了。

**Comment by i-iooi-i** [comment]
> 请查看帮助文档

是我的错，MAC上输错了密码，现在一切正常了。🥲

刚测试了一下，在 win  mac  Linux系统上都可以实现webdav同步。

希望大佬考虑一下，在点击同步的时候，能一起同步书籍的阅读进度。粗略试了一下，现在这个同步按钮似乎只是同步了软件设置，并不能同步阅读进度。而要同步阅读进度还要进入备份恢复手动操作，似乎体验上来说，还是稍显麻烦了。
