### ISSUE TITLE
书籍注释跳转功能突然没用

### ISSUE THREAD

**Issue by xiaoxiamitech** [troyeguo/koodo-reader#295]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

打开书很久后出现

**Comment by troyeguo** [comment]
请提供电子书和截图，复现bug的过程
