### ISSUE TITLE
苹果M1芯片，最新macOS Monterey 12 系统上，安装后打不开，提示文件已经损坏，建议移除

### ISSUE THREAD

**Issue by richfuns** [troyeguo/koodo-reader#297]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.3.9-arm64

### 我遇到的问题

如标题表述的

**Comment by troyeguo** [comment]
请查看帮助文档
