### ISSUE TITLE
右侧字体被遮挡

### ISSUE THREAD

**Issue by Zj878** [troyeguo/koodo-reader#299]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 Issues列表，没有找到类似的issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

阅读txt文本时会出现字体被遮挡，只有右侧会这样，调整窗口宽度之后会好，但是读几页之后又会出现这种情况，各种字号 间距 对齐都试过了，还是不行  截图上能很明显看到右侧字体被吞了，越往后吞的越多  必须不断调整窗口大小才能解决

### 截图或录像(可选的)

![微信截图_20211215192441](https://user-images.githubusercontent.com/51796018/146178238-80164365-149a-426d-b9d0-8796f867dd53.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题
