### ISSUE TITLE
新版本的导入文件大小有了限制

### ISSUE THREAD

**Issue by kafuuchino-s** [troyeguo/koodo-reader#30]
首先十分感谢作者更新了触控模式，我使用该软件的目的就是看漫画，因此文件的大小普遍都超过了20M，最新的版本不支持，我使用旧版本的时候是可以支持我导入40M的漫画的，触控模式中我看epub格式的漫画的时候，感觉画面比非触控模式的小了许多，不知道作者能不能支持一下对漫画的支持，谢谢！

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，之前确实没有考虑过漫画的问题，下个版本会解除大小的限制的，关于画面变小的问题，您可以把变化前后的截图发一下吗，如果可以的话，您可以发一下您这本书的下载地址吗？

**Comment by kafuuchino-s** [comment]
这个是文件的地址:[https://wws.lanzous.com/i74sagneuxg](url)
导入的时候需要更改文件名,把前面的[Vol.moe]这个删掉才能正常导入,我新版本的截图没有留下来了,我直接重新安装旧版本的软件,现在使用旧版本的软件的滚动模式挺舒服的,就是用surface的竖屏看有点窄,,还有就是在竖屏模式下,软件的导入和备份按钮是被隐藏起来了.

**Comment by troyeguo** [comment]
画面变小应该是因为横竖屏切换导致水平宽度变化，而图书两边的页边距是固定的，所以导致了画面变化，按理来说应该和触控模式没有太大关系，后续会为漫画阅读做更多优化，如果您在使用过程遇到了什么问题，或者有什么建议欢迎随时与我取得联系。

**Comment by kafuuchino-s** [comment]
> 画面变小应该是因为横竖屏切换导致水平宽度变化，而图书两边的页边距是固定的，所以导致了画面变化，按理来说应该和触控模式没有太大关系，后续会为漫画阅读做更多优化，如果您在使用过程遇到了什么问题，或者有什么建议欢迎随时与我取得联系。

谢谢作者，之前我是用edge来直接看epub漫画的，可以直接像pdf一样拉大图片的宽度，期待之后的更新。那我可以关闭问题了吗

**Comment by troyeguo** [comment]
> > 画面变小应该是因为横竖屏切换导致水平宽度变化，而图书两边的页边距是固定的，所以导致了画面变化，按理来说应该和触控模式没有太大关系，后续会为漫画阅读做更多优化，如果您在使用过程遇到了什么问题，或者有什么建议欢迎随时与我取得联系。
> 
> 谢谢作者，之前我是用edge来直接看epub漫画的，可以直接像pdf一样拉大图片的宽度，期待之后的更新。那我可以关闭问题了吗

后续的版本会增加自定义页面大小的功能，现在阅读器已经支持点击图片放大的功能，不过在旧版本的滚动模式下无法正常工作，新版本已经修复这个问题了，后续还会增加对图片缩放，旋转，保存的功能。如果您没有其他问题了，就可以关闭这个issue了。
