### ISSUE TITLE
列表模式的阅读进度没有显示

### ISSUE THREAD

**Issue by meinvtuzai** [troyeguo/koodo-reader#303]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.3.9

### Bug Detail

书籍都读了一半多了，在列表模式下的进度还是显示0，什么情况？

**Comment by troyeguo** [comment]
请提供一下您正在阅读的电子书

**Comment by troyeguo** [comment]
请升级至1.4.0
