### ISSUE TITLE
Fullscreen mode & Home button

### ISSUE THREAD

**Issue by its-crypted** [troyeguo/koodo-reader#305]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Ubuntu

### App Version

1.3.9

### Bug Detail

Koodo Reader doesn't shift to the fullscreen mode using F11.
The HOME button at right corner of reader -- when clicked it opens a new window rather than redirecting to the old window.

**Comment by troyeguo** [comment]
Thanks for the feedback, pressing F11 to enter fullscreen is supported yet, but it's in our future plan together with more keyboard shortcuts. The home button is used to redirect to the book list when you're opening books in the main window or you have closed the main window.

**Comment by its-crypted** [comment]
ok thanks.
