### ISSUE TITLE
Replace white background on opening the app with a dark one

### ISSUE THREAD

**Issue by shockproof22** [troyeguo/koodo-reader#307]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

On opening any book or the app itself, the first screen it shows it pure white and then it goes to dark mode which I've set
https://user-images.githubusercontent.com/60001922/147225794-7d0e9fac-1bc7-49f3-b635-74c9dfe950c8.png

### Details

so my simple request is to make this first screen dark for when dark mode is set in the app and white for when light mode is on and stop making me blind every time I open the app

**Comment by troyeguo** [comment]
Thanks for the advice, we will add this feature in the next update

**Comment by shockproof22** [comment]
@troyeguo and when will that update come exactly?

**Comment by troyeguo** [comment]
> @troyeguo and when will that update come exactly?

Usually, one month after the last release

**Comment by shockproof22** [comment]
okay I'll wait for it

**Comment by troyeguo** [comment]
Please update to 1.4.0
