### ISSUE TITLE
同步功能bug

### ISSUE THREAD

**Issue by 913650629** [troyeguo/koodo-reader#314]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

给图书做完笔记后，添加高亮、笔记后，直接点击同步，实际没有同步到存储目录。
1. 导入图书
2. 打开图书给图书做笔记（高亮、记笔记）
3. 关闭图书后，设置同步目录，直接点击同步
4. 实际没进行同步
5. 点击我的笔记和我的高亮
6. 此时点击同步，才能正常同步

### 截图或录像(可选的)

[Rec 0004.zip](https://github.com/troyeguo/koodo-reader/files/7797850/Rec.0004.zip)

**Comment by 913650629** [comment]
补充一点，同步生成的config.zip里面的时间时区设置问题！
![image](https://user-images.githubusercontent.com/66675245/147854378-e9ae1292-c550-46af-becf-80d025d24ced.png)

**Comment by troyeguo** [comment]
感谢反馈，这个问题在1.4.0中修复了
