### ISSUE TITLE
打开mobi格式的漫画页面显示全白

### ISSUE THREAD

**Issue by yanyufei7** [troyeguo/koodo-reader#317]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

 打开mobi图书，页面显示空白
![image](https://user-images.githubusercontent.com/46084777/147900883-92dfe786-6123-41e0-bede-0e60cd29e55e.png)

用calibre阅读器打开同一个mobi图书，可以显示
![image](https://user-images.githubusercontent.com/46084777/147900979-f0901bd8-2784-487c-b9b9-133899146114.png)

### 图书文件(可选的)

https://en.sa1lib.org/dl/16687815/360621

**Comment by troyeguo** [comment]
您好，我这边可以正常打开，内容也可以正常显示，但耗时确实会比普通图书更长。主要原因还是图书体积太大，并且也和电脑配置有关

**Comment by yanyufei7** [comment]
好的，后面试了网页版可以顺畅显示
