### ISSUE TITLE
如果带朗读和翻译就完美了

### ISSUE THREAD

**Issue by martjay** [troyeguo/koodo-reader#320]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

朗读真的很重要，不然看小说确实挺难受，如果能自动翻译可以看外文书，很有用

### 细节描述

朗读真的很重要，不然看小说确实挺难受，如果能自动翻译可以看外文书，很有用

**Comment by troyeguo** [comment]
您好，翻译功能已经支持，听书功能目前仅支持epub，其他格式会在后续版本中支持

**Comment by martjay** [comment]
> 您好，翻译功能已经支持，听书功能目前仅支持epub，其他格式会在后续版本中支持

找不到翻译功能啊，在哪里呢？

**Comment by troyeguo** [comment]
> > 您好，翻译功能已经支持，听书功能目前仅支持epub，其他格式会在后续版本中支持
> 
> 找不到翻译功能啊，在哪里呢？

选中文字之后的弹窗里有

**Comment by troyeguo** [comment]
<img width="481" alt="捕获" src="https://user-images.githubusercontent.com/13820674/148641906-e1249f1f-0a59-4986-8542-4a8a101c539f.PNG">

**Comment by martjay** [comment]
我选中PDF的文字并没有看到弹窗，还有我是说整篇翻译的功能

**Comment by troyeguo** [comment]
> 我选中PDF的文字并没有看到弹窗，还有我是说整篇翻译的功能

这是1.4.0的bug，请使用稳定版1.3.9。不会考虑提供整篇翻译功能。
