### ISSUE TITLE
无法正确跳到高亮页面

### ISSUE THREAD

**Issue by jiangaq** [troyeguo/koodo-reader#322]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.40

### 我遇到的问题

我调整过字体和字体大小、行距后，高亮后，尝试重新跳到高亮的页面，但是跳到了错误的没高亮的页面

另外，如何才能直接导出一本书所有高亮内容？

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复这个问题，导出笔记高亮功能已经在开发计划中了
