### ISSUE TITLE
阅读界面发灰，如何设置常见的白底黑字或者黑底白字都不行

### ISSUE THREAD

**Issue by chenjunyi1990** [troyeguo/koodo-reader#325]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

阅读背景在打开设置之后忽然变成灰黑色（其实只是调整下页边距其他都没有动），很不清晰，设置黑底白字或者白底黑字，也无法生效。

### 截图或录像(可选的)

![微信截图_20220111114335](https://user-images.githubusercontent.com/40488663/148881136-f278aa7e-1c20-4da8-8bf9-5e624e2b4a5d.png)

**Comment by troyeguo** [comment]
请检查右侧菜单的亮度选项
