### ISSUE TITLE
打开设置直接白屏

### ISSUE THREAD

**Issue by liuchanghuaX1** [troyeguo/koodo-reader#327]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.40

### 我遇到的问题

无法进行设置，打开设置直接白屏。

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/40064819/149538187-a7b75c6e-43a3-4887-a609-8407f35d0763.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下一个版本修复这个问题

**Comment by ShaneYe11920** [comment]
我也是，应该是Win11的问题
