### ISSUE TITLE
This app doesn't work on M1 MacBook

### ISSUE THREAD

**Issue by aniuwoo** [troyeguo/koodo-reader#329]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.39

### Bug Detail

Everytime start the app, both the stable version and pilot version, on M1 MacBook Pro it shows this
<img width="313" alt="截屏2022-01-19 07 52 09" src="https://user-images.githubusercontent.com/80492616/150037662-09de579f-d9a8-4447-bec4-c56dd4c2fe33.png">

### Screenshots (Optional)

<img width="313" alt="截屏2022-01-19 07 52 09" src="https://user-images.githubusercontent.com/80492616/150037694-3aaa33e2-2926-4bab-9f34-fc60c41f714e.png">

**Comment by troyeguo** [comment]
Check out document for more instructions on this issue: https://troyeguo.notion.site/Koodo-Reader-Document-9c767af3d66c459db996bdd08a34c34b
请参考帮助文档中的解决办法：https://troyeguo.notion.site/Koodo-Reader-0c9c7ccdc5104a54825dfc72f1c84bea
