### ISSUE TITLE
打开电子书乱码，最近大部分图书都乱码，少部分正常。乱码的电子书在其他软件上打开正常

### ISSUE THREAD

**Issue by zhengguoxin** [troyeguo/koodo-reader#331]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.3.9

### 我遇到的问题

打开大部分电子书都是乱码，用其他软件是正常的。

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/24664658/150110980-28d3889f-02c3-4d57-b85a-02e7f3a05e17.png)

### 图书文件(可选的)

[CPU自制入门.azw3.zip](https://github.com/troyeguo/koodo-reader/files/7896171/CPU.azw3.zip)

**Comment by troyeguo** [comment]
请查看帮助文档
