### ISSUE TITLE
【建议】视图模式希望单页模式能全屏宽度/或者双页模式提供一个去掉书脊选项

### ISSUE THREAD

**Issue by toyqiu** [troyeguo/koodo-reader#332]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

双页模式阅读类似实体书，很不错，但是我有比较大的竖排书阅读需求，双页模式下中间的书脊太扎眼了，希望能给个选项去掉，谢谢！

### 细节描述

![image](https://user-images.githubusercontent.com/479873/150332012-10465d7b-a6b0-40ff-9d00-86644817ea48.png)

**Comment by troyeguo** [comment]
在右侧菜单中，单页模式下可以调节页面宽度，双页模式可以关闭仿真背景
