### ISSUE TITLE
首次打开图书时无法正常操作浏览

### ISSUE THREAD

**Issue by charlieblack** [troyeguo/koodo-reader#334]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.0

### 我遇到的问题

首次打开图书总是卡住无法正常查看，翻页，从目录选择也无效，不是程序卡死，重新阅读才正常。

**Comment by troyeguo** [comment]
麻烦您提供以下图书文件
