### ISSUE TITLE
有些字体使用无效

### ISSUE THREAD

**Issue by lethefrost** [troyeguo/koodo-reader#336]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [x] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.3.9 (1.3.9.780)

### 我遇到的问题

比如开源字体[I.明體/I.Ming](https://github.com/ichitenfont/I.Ming)，在字体选择列表中可以读取到已安装的字体文件I.Ming，但是选择使用后显示的文本变回了苹果默认的黑体。

**Comment by troyeguo** [comment]
请升级至1.4.1

**Comment by lethefrost** [comment]
> 请升级至1.4.1

您好，之前提到的I.Ming字体仍然无法使用，只是选择后由“变回苹果默认的黑体”转而“变为一个serif字体（我没认出来，但是可以确认并不是I.Ming）”。谢谢修复！
