### ISSUE TITLE
1.4.0 安装后无法运行

### ISSUE THREAD

**Issue by genedna** [troyeguo/koodo-reader#337]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.4.0

### Bug Detail

安装后提示文件已经损坏

芯片： Apple M1 Max

**Comment by troyeguo** [comment]
请查看帮助文档
