### ISSUE TITLE
搜索改进建议

### ISSUE THREAD

**Issue by lethefrost** [troyeguo/koodo-reader#338]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

阅读英文书籍的时候，搜索不能输入空格，只能搜索单个单词，书太长几乎找不到想要的文段。希望搜索时允许输入空格（为什么针对空格！别的符号都可以输入……）
同时还有一些关于搜索的其他bug和需求，希望得到支持。见下文。

### 细节描述

1. 搜索允许输入空格
2. 阅读时可以用cmd+F或者ctrl+F调出搜索（有看到roadmap里有“快捷键支持”，不确定包不包括这部分……）
3. 搜索有bug，当左侧菜单是通过滑动唤出的时候，开始往搜索栏里输入文字会导致菜单再次被折叠，需要重新滑动让其显现。

**Comment by troyeguo** [comment]
请问您是在什么系统或浏览器上使用 Koodo Reader，我这边搜索包含空格的字段没有您提到的问题，您是在触控屏上使用吗？不太理解您提到的滑动唤出。Koodo Reader都是通过点击边缘位置或者将鼠标移动到边缘位置唤出菜单

**Comment by lethefrost** [comment]
> 请问您是在什么系统或浏览器上使用 Koodo Reader，我这边搜索包含空格的字段没有您提到的问题，您是在触控屏上使用吗？不太理解您提到的滑动唤出。Koodo Reader都是通过点击边缘位置或者将鼠标移动到边缘位置唤出菜单

开发者您好，我是用的macOS 12.1。不好意思我的用语可能有歧义，我之前说的“滑动唤出”指的就是鼠标滑动到边缘位置唤出菜单到意思。我现在又发现除了无法输入空格外，在输入框里方向键（比方说←和→，本来应该可以移动输入文本处的光标的）行为也不太正常…

我录了一下滑出的菜单是如何自己弹回去的现象（无论是当前是英文还是中文输入法，都会弹缩回去）
![20220127085943022](https://user-images.githubusercontent.com/47198693/151374021-b54d0d33-1d20-4c60-b377-98ef4fb6e59a.gif)


无法移动光标和无法输入空格的问题录屏显示不出来，但是确实是存在的，期间重启过软件和系统都没有解决。您排查一下？

**Comment by troyeguo** [comment]
> > 请问您是在什么系统或浏览器上使用 Koodo Reader，我这边搜索包含空格的字段没有您提到的问题，您是在触控屏上使用吗？不太理解您提到的滑动唤出。Koodo Reader都是通过点击边缘位置或者将鼠标移动到边缘位置唤出菜单
> 
> 开发者您好，我是用的macOS 12.1的客户端。不好意思我的用语可能有歧义，我之前说的“滑动唤出”指的就是鼠标滑动到边缘位置唤出菜单到意思。我现在又发现除了无法输入空格外，在输入框里方向键（比方说←和→，本来应该可以移动输入文本处的光标的）行为也不太正常…
> 
> 我录了一下滑出的菜单是如何自己弹回去的现象（无论是当前是英文还是中文输入法，都会弹缩回去） ![20220127085943022](https://user-images.githubusercontent.com/47198693/151374021-b54d0d33-1d20-4c60-b377-98ef4fb6e59a.gif)
> 
> 无法移动光标和无法输入空格的问题录屏显示不出来，但是确实是存在的，期间重启过软件和系统都没有解决。您排查一下？

感谢您的反馈，已经定位到这个问题，会在后续版本修复的

**Comment by lethefrost** [comment]
> > > 请问您是在什么系统或浏览器上使用 Koodo Reader，我这边搜索包含空格的字段没有您提到的问题，您是在触控屏上使用吗？不太理解您提到的滑动唤出。Koodo Reader都是通过点击边缘位置或者将鼠标移动到边缘位置唤出菜单
> > 
> > 
> > 开发者您好，我是用的macOS 12.1的客户端。不好意思我的用语可能有歧义，我之前说的“滑动唤出”指的就是鼠标滑动到边缘位置唤出菜单到意思。我现在又发现除了无法输入空格外，在输入框里方向键（比方说←和→，本来应该可以移动输入文本处的光标的）行为也不太正常…
> > 我录了一下滑出的菜单是如何自己弹回去的现象（无论是当前是英文还是中文输入法，都会弹缩回去） ![20220127085943022](https://user-images.githubusercontent.com/47198693/151374021-b54d0d33-1d20-4c60-b377-98ef4fb6e59a.gif)
> > 无法移动光标和无法输入空格的问题录屏显示不出来，但是确实是存在的，期间重启过软件和系统都没有解决。您排查一下？
> 
> 感谢您的反馈，已经定位到这个问题，会在后续版本修复的

太好了，辛苦啦，祝越做越好！

**Comment by troyeguo** [comment]
请升级至1.4.1
