### ISSUE TITLE
带图片的azw3打开图片过大

### ISSUE THREAD

**Issue by jiangaq** [troyeguo/koodo-reader#339]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.40

### Bug Detail

![image](https://user-images.githubusercontent.com/26076033/150908005-8da598e1-e835-4778-8f5c-7264077565fa.png)

**Comment by troyeguo** [comment]
感谢您的反馈

**Comment by troyeguo** [comment]
请升级至1.4.1
