### ISSUE TITLE
换章/切换全屏时字体或字号恢复默认

### ISSUE THREAD

**Issue by fcki1984** [troyeguo/koodo-reader#34]
网页版
步骤（字体、字号随意）：
- 字体选择simsun，字号23，换章，字号恢复默认。
- 同上配置，切换全屏或浏览器大小，字体恢复默认
- 同上配置，然后切换为任意字体并切换回simsun，切换全屏或浏览器大小，字号恢复默认

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，确实存在这个问题，会在下个版本更新中修复的。
