### ISSUE TITLE
听书消失、视图转换、章节解析、简繁转换

### ISSUE THREAD

**Issue by Moon-Orchid** [troyeguo/koodo-reader#341]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [x] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9 稳定版

### 我遇到的问题

> 注：使用EPUB格式进行测试
#### 开启听书
* 每第一次开启软件，点击“开启听书”其按钮就会消失，但语音确实开启了(关掉小说语音不消失，BUG？)。重新打开小说“开启听书”的按钮是未开启状态，重新开启再关闭才变成正常逻辑。
* 听书开启时加个朗读段落高亮感觉舒服些。
#### 视图模式
* 从双页模式切换到单页模式再点击**非**”下次打开图书生效”的功能都会使文字占整个屏幕排布，但背景还是双页阅读的(感觉这种阅读排布不错，不过要通过BUG触发)。
#### 简繁转换
* 选择繁体转换简体后，章节跳转好像每次都重新加载，总会卡一下（重新对文本生成一个单独的转换版本？）。
> 重新试了下繁-简转换后标题格式没了；
> 章节切换有时会相邻几章都有转换远一些的章节没转换，有时只转换了当前章；
#### 章节解析
* 这个问题是从上一个问题发现的：从下一章滑到没有转换的上一章时，软件经过自动转换后，会向前跳很多章。
* 发现目录里章节分好了，但是章节切换时上面的章节提示却没有切换；
* 可能是这个问题导致的，重新打开小说不是之前结束阅读的部分。
> 图片上传了
#### 小问题
* 开始时鼠标选中文字时页面总会乱跑，但是测试测试着就正常了(薛定谔的BUG)
***
第一次反馈可能有点啰嗦，我这么多事不会被骂吧。
PS：我好像是为了找小说阅读器看小说的，为什么找了两个多小时的BUG???

### 截图或录像(可选的)

章节解析的问题图片
![image](https://user-images.githubusercontent.com/49013701/150980583-8d9ecff0-5dfb-4853-a411-88b88a6f9b62.png)
![image](https://user-images.githubusercontent.com/49013701/150980647-bd307fac-3f39-4096-abe2-d1e9e9e13ce1.png)

### 图书文件(可选的)

[[小书痴的下克上]第二部_神殿的見習女巫_II - 香月美夜.zip](https://github.com/troyeguo/koodo-reader/files/7933995/_._II.-.zip)

**Comment by troyeguo** [comment]
听书的问题会在后续版本修复的，繁简转换的问题已经在1.4.0中修复了，章节解析和视图转换的问题没看懂，您的图书上传失败了

**Comment by Moon-Orchid** [comment]
* 我看了下其他格式的章节解析，并没有在左上角显示本章名，而且打开每一章时都会新起一页，在文章内的左上部分显示章节名。
![image](https://user-images.githubusercontent.com/49013701/150989994-e126e162-962b-4d88-aaad-97edebea4329.png)
* 但是我的EPUB文件目录解析正确，在左上类似页眉的部分显示了本章名，但是实际章节切换时左上角显示的章节没有变，也没有另起一页显示章节。且做简繁切换后会自动跳到那个显示的章节上。
![image](https://user-images.githubusercontent.com/49013701/150990593-19b144d1-3901-445c-95f5-416eb1695e38.png)
***
更改视图模式，然后切换除了页边距那种显示下次打开图书显示的功能就会导致下面这种情况
原来的
![image](https://user-images.githubusercontent.com/49013701/150991948-6e61940d-3328-4b3d-beff-c1257c85d3f3.png)
切换后的
![image](https://user-images.githubusercontent.com/49013701/150992223-0e79109a-7e37-466e-ae46-6540821aed54.png)

**Comment by troyeguo** [comment]
章节解析的问题应该只是这本书的特例，视图切换主要是技术原因，必须要重新打开图书后才能生效，这个bug只对图书本身生效，对阅读背景无效。

**Comment by Moon-Orchid** [comment]
另
我更新了1.4.0版本，第一次打开软件开启听书，听书按钮消失问题依然存在，但关闭后已不再朗读；
现在1.4.0只对这本书正确解析出的章节进行跳转，其他章节只能在目录显示但不能点击。
应该是这本比较特殊，其他格式并没有章节解析问题。

感谢做出这个软件。

**Comment by ssbroad** [comment]
> 请升级至1.4.1

请问软件读书功能目前只支持epub吗？txt格式点击会白屏。 后续会增加其他格式吗
