### ISSUE TITLE
Mac图标可不可以取消这个黑边

### ISSUE THREAD

**Issue by deusyu** [troyeguo/koodo-reader#346]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

![image](https://user-images.githubusercontent.com/42929363/151770785-d3b51577-6ea3-45a6-8e85-1fac4b06b2a1.png)
![image](https://user-images.githubusercontent.com/42929363/151771295-b1206c3e-451a-4ced-843a-1186ea22efb3.png)

如图，无论是应用自己的图标，还是作为扩展的文件后缀图标，显示都是大黑色的背景，实在和mac其他图标格格不入，请求优化。
MacOS版本是10.15.7

### 细节描述

如上简介

**Comment by troyeguo** [comment]
Koodo Reader的版本多少

**Comment by deusyu** [comment]
1.2.9，由于brew版本过低没有升级最新的版本，抱歉浪费了您的时间
