### ISSUE TITLE
Make koodo web version a Progressive Web App (PWA)

### ISSUE THREAD

**Issue by yhcharles** [troyeguo/koodo-reader#348]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

A Progressive Web App is simply a web page, but it can be "installed" to local device, including mobile/desktop.
- This will make it a lot easier for users to try and use this great app, and probably attract more users.
- This can also save developer's time to build and release multiple versions for different platforms.

### Details

It should not be too complex to make this change. Here are some references:
https://medium.com/james-johnson/a-simple-progressive-web-app-tutorial-f9708e5f2605
https://zhuanlan.zhihu.com/p/25459319

**Comment by troyeguo** [comment]
We used to try to make web version a PWA. But later when we update the static files in our remote server, PWA can't seem to detects these changes and still used local caches. Also PWA configuration might conflict with Electron itself.
Some reference about why we don't want to use PWA: https://www.youtube.com/watch?v=JJSloXLTyNg
