### ISSUE TITLE
夜间模式开启，设定页面背景为黑色，但是书籍打开后中间部分背景全白。

### ISSUE THREAD

**Issue by AntaresShao** [troyeguo/koodo-reader#349]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.0

### 我遇到的问题

# 前提
夜间模式开启。阅读时背景颜色设置为深灰色，背景颜色设为白色。如下列图。
<img width="303" alt="bug-白屏-阅读设置1" src="https://user-images.githubusercontent.com/79731222/152630551-6ef4482a-5ee8-42b1-9c68-332f3a1e9c9b.png"><img width="303" alt="bug-白屏-阅读设置2" src="https://user-images.githubusercontent.com/79731222/152630556-1d92d30a-5e1c-4300-9a9d-cde5190c0a13.png"><img width="303" alt="bug-白屏-阅读设置3" src="https://user-images.githubusercontent.com/79731222/152630560-27e358ab-e740-4804-a5a6-b2cb8bed53d9.png">
# 问题复现
打开EPUB格式书籍后背景为白色，字体可以调节为黑色，但是背景无论怎么在侧边栏调节都不变色。下图为将文字改回白色时的效果，此时背景颜色设置一直为深灰色。
<img width="1120" alt="bug-白屏-1" src="https://user-images.githubusercontent.com/79731222/152630593-02d9bbb9-5203-4942-b14c-009241335f1a.png">
若将文字改为黑色，背景仍为深灰色，则效果如下图所示。
<img width="1120" alt="bug-白屏-2" src="https://user-images.githubusercontent.com/79731222/152630650-8b55a53a-9e0e-4569-8a1f-82b6e889c9a2.png">
在下方检查文件过程中（见下一部分）发现在Koodo Reader中的页数编码貌似也出现了混乱，这里没有进行详细考究。
# 检查文件
为验证该文档没有损坏，又将文档在Calibre中打开，Calibre软件也是设置为夜间模式，其阅读效果如下图所示。
<img width="375" alt="bug-calibre检查" src="https://user-images.githubusercontent.com/79731222/152630941-b7559e68-38e0-47c6-b30a-9995e4629222.png">
个人认为文件本身格式是没有问题的。

### 截图或录像(可选的)

已经在上面一部分列出。

### 图书文件(可选的)

将已经发现有该类问题的两个EPUB文件进行了上传。
[BooksUpload.zip](https://github.com/troyeguo/koodo-reader/files/8007502/BooksUpload.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复这个问题的

**Comment by troyeguo** [comment]
请升级至1.4.1
