### ISSUE TITLE
EPUB格式目录中超过3级无法打开

### ISSUE THREAD

**Issue by hoefershen** [troyeguo/koodo-reader#35]
目录只能点开两级，第三级那> 点开，又返回上一级了，第3、4级根本没有办法打开，试了W*S，N**tReader都是可以正常展开的图书。

建议加上展开所有，收到所有目录的功能，谢谢。

**Comment by troyeguo** [comment]
您好！
感谢您的反馈和建议，会在下个版本中增加这个功能的。
