### ISSUE TITLE
网页版 备份webdav失败 window.require is not a function

### ISSUE THREAD

**Issue by wiidede** [troyeguo/koodo-reader#350]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Chrome 及其他 Chromium 浏览器(包括 Edge 和所有国产浏览器)

### Koodo Reader 版本

1.4.0

### 我遇到的问题

使用 chrome/firefox 在 reader.960960.xyz 备份webdav失败，控制台报错：

> Uncaught (in promise) TypeError: window.require is not a function
    e webdav.tsx:7
    c runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 4
    e webdav.tsx:6
    e webdav.tsx:6
    c runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 4
    UploadFile main.769a5a81.chunk.js:1
    n component.tsx:144
    c runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 6
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
webdav.tsx:7:38

主要是这行代码：

```js
const { createClient } = window.require("webdav");
```

**Comment by wiidede** [comment]
我去下载了客户端，试了一下可以备份，但客户端好像是1.3.9，不知道是版本的问题还是没有electron的问题

**Comment by troyeguo** [comment]
网页版不支持webdav备份，后续版本会增加提示的

**Comment by wiidede** [comment]
> 网页版不支持webdav备份，后续版本会增加提示的

好的好的，不然一直都是在上传的样子很奇怪😂

**Comment by troyeguo** [comment]
请升级至1.4.1
