### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by heiheyuge3** [troyeguo/koodo-reader#351]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

在某些书里有批注，字体大小同正文不同，希望加入不同颜色，加以区分。

### 细节描述

在某些书里有批注，字体大小同正文不同，希望加入不同颜色，加以区分。

**Comment by troyeguo** [comment]
如果图书本身没区分，则Koodo Reader 也没办法区分正文和批注

**Comment by heiheyuge3** [comment]
> 如果图书本身没区分，则Koodo Reader 也没办法区分正文和批注

因为在别的阅读器内是可以区分的，所以才这么一提，颜色大小都不同。

**Comment by troyeguo** [comment]
> > 如果图书本身没区分，则Koodo Reader 也没办法区分正文和批注
> 
> 因为在别的阅读器内是可以区分的，所以才这么一提，颜色大小都不同。

麻烦您提供一下电子书文件还有这个阅读器的名字

**Comment by heihe1234** [comment]
一本书如果设置了很多高亮  笔记之后，翻页动作会很慢，重新打开书籍也会很慢而且很卡。书中插图有很多无法显示，而且书中注释也无法使用不能点击。

**Comment by heiheyuge3** [comment]
[](url
[红楼梦脂评汇校本.pdf](https://github.com/troyeguo/koodo-reader/files/8046143/default.pdf)
)
阅读器是：稻壳阅读器，随便一搜就能找到。

**Comment by heiheyuge3** [comment]
> 
[]（url
[红楼梦脂评汇校本.pdf](https://github.com/troyeguo/koodo-reader/files/8046143/default.pdf)
）
阅读器是：稻壳阅读器，随便一搜就能找到。

**Comment by heiheyuge3** [comment]
搞好了，我把文件弄错了，谢谢回复。
