### ISSUE TITLE
Popup menu not working on pdf (v1.4.0)

### ISSUE THREAD

**Issue by DarkDeveloper-Plant** [troyeguo/koodo-reader#354]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [ ] Yes

### There are no similar issues on the issue list

- [ ] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Other Linux distribution

### App Version

1.4.0

### Bug Detail

Hi
On version 1.3.9 popup menu was working with pdfs when highlighting a piece of text but on version 1.4.0 only works on epubs

OS : Arch linux
App version: 1.4.0 AppImage 

### Screenshots (Optional)

pdf:
![Screenshot from 2022-02-11 09-29-57](https://user-images.githubusercontent.com/47008296/153544473-90319e4a-b0e1-4320-a11b-afc91d6c09bd.png)

epub:
![Screenshot from 2022-02-11 09-32-41](https://user-images.githubusercontent.com/47008296/153544529-7b6c755e-70fa-4b06-aa9f-3ecffa9892ae.png)

**Comment by troyeguo** [comment]
Thanks for the feedback, we will fix it in the next update

**Comment by troyeguo** [comment]
Please update to latest 1.4.1 version
