### ISSUE TITLE
大部分页面不能添加标签，少数页可以添加

### ISSUE THREAD

**Issue by yunyq** [troyeguo/koodo-reader#356]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

点击添加标签没有反应

### 截图或录像(可选的)

https://user-images.githubusercontent.com/99524638/153698576-0e54ed68-18f4-4fc8-aff3-d72d6dcbc260.mp4

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by yunyq** [comment]
[如何阅读一本书 by [美] 莫提默·J. 艾德勒 查尔斯·范多伦 (z-lib.org).zip](https://github.com/troyeguo/koodo-reader/files/8053016/by.J.z-lib.org.zip)
感谢，软件很好！

**Comment by troyeguo** [comment]
1.4.1版还有这个问题吗？

**Comment by yunyq** [comment]
没有了，太棒了！感谢作者。
有个小建议，当锁定索引栏时，会遮挡书本内容，可否让其重新排版。
![image](https://user-images.githubusercontent.com/99524638/153783315-e67bf50d-4c71-42d2-acf1-b5f003be5ad0.png)

**Comment by yunyq** [comment]
发现了新的问题。
在1.4.1版里，书签添加正常，但一些书籍的目录失效，点击无法跳转。同样的书籍，在1.3.9里可以正常跳转。
[大众哲学 - 艾思奇.zip](https://github.com/troyeguo/koodo-reader/files/8057163/-.zip)
。

**Comment by troyeguo** [comment]
> 没有了，太棒了！感谢作者。 有个小建议，当锁定索引栏时，会遮挡书本内容，可否让其重新排版。 ![image](https://user-images.githubusercontent.com/99524638/153783315-e67bf50d-4c71-42d2-acf1-b5f003be5ad0.png)

感谢您的建议，会考虑增加这个功能

**Comment by troyeguo** [comment]
> 

感谢反馈

**Comment by tyf2018** [comment]
软件好用，赞。不过我使用的是1.4.1版本，问题仍旧（个别可以添加，但大部分电子书都提示 暂不支持）。电子书如下：

[1q84.zip](https://github.com/troyeguo/koodo-reader/files/8080647/1q84.zip)

**Comment by troyeguo** [comment]
> 软件好用，赞。不过我使用的是1.4.1版本，问题仍旧（个别可以添加，但大部分电子书都提示 暂不支持）。电子书如下：
> 
> [1q84.zip](https://github.com/troyeguo/koodo-reader/files/8080647/1q84.zip)

目前只有epub支持添加书签，其他格式还在开发中

**Comment by troyeguo** [comment]
请升级至最新开发版
