### ISSUE TITLE
Sort does not work on other shelves (custom) + others

### ISSUE THREAD

**Issue by lunchplus** [troyeguo/koodo-reader#357]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.3.9

### Bug Detail

Choosing a sort method does not work on books inside custom shelves. 

Also, please make the delete comprehensive and uniform (i.e. only delete from catalog). Deleting from the default shelf works fine but deleting from other shelves results in unresponsiveness (unless the operation is canceled). 

The trash is also relevant for that launch instance so it is kind of useless. I hope it retains what was deleted in previous sessions.

Lastly, switching from sidebars causes a shelf title bug. If I open the "Study" Shelf then go to Trash and go back to the Shelf, the title becomes "Books" but the contents are still that of "Study."

Anyway, really great job with this app, thanks for your efforts! I will continue to explore and report any bugs.

**Comment by troyeguo** [comment]
Thanks for the feedback, we will look into it

**Comment by troyeguo** [comment]
> ![image](https://user-images.githubusercontent.com/76794832/153755962-ac2e87d0-296c-4360-bb32-0de51cbdeff7.png)
> 
> It has improved--well I've seen stuff reorder but seemingly in the wrong hierarchy/order still. I think sorting through "Add Time", "Reading Progress", "Reading Duration" are the only ones working correctly.
> 
> Incorrect for Recently Read or Book Name. Moreover, sorting by Author Name somehow results in some of the books becoming hidden. From my observation, **some** books with Unknown Author are the ones being hidden (some are still shown).
> 
> But thanks for trying to address the previous issues immediately. Good luck with the next debugging sessions!

Thanks for the feedback

**Comment by troyeguo** [comment]
Please upgrade to 1.4.2
