### ISSUE TITLE
兄弟，你好啊，咱们认识一下呗

### ISSUE THREAD

**Issue by hz0324** [troyeguo/koodo-reader#36]
你好啊，我们是做Neat Reader，也算是你这个软件的竞品吧。
看到你也在北京，还跟我们做类似的业务，非常开心，也许未来我们可以一起做事。
跨平台电子书阅读器这条路不好走啊，我看你已经做了好几个月了，应该也踩了不少坑了，哈哈。
我们可以先认识一下，如果有机会，未来可以一起共事。（我们可能会拿到教育部的电子教材项目，给全国大学生提供电子化教材软件，届时会扩大团队）

我的微信是huangzhong5690。

**Comment by johnzjzlast** [comment]
又是收费的吧:moneybag:
