### ISSUE TITLE
跨平台使用同步功能时会报错 “Book not exist”

### ISSUE THREAD

**Issue by Visitant0226** [troyeguo/koodo-reader#362]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.1

### Bug Detail

使用同步功能在macOS和Windows之间同步进度时，在macOS上导入打开的书籍，在Windows上无法正常打开，提示“Book not exist”。
我看在config/books.json文件中，书籍定义的path是绝对路径，虽然在两个系统上书籍存放的地址相对config是一样的，但因为绝对路径的起始值不同，导致跨平台无法找到正确的数据。
不论是启用了“引用”功能还是不启用“引用”功能，都是相同的问题

### Screenshots (Optional)

无

### Files (Optional)

无

**Comment by Visitant0226** [comment]
刚刚看了下打开书籍部分的代码，打开书籍支持key和path两种方式，path这种方式在跨平台会有问题，但是因为我之前使用了用引用的方式打开图书，所以导致key在跨平台时也无法找到书籍了

**Comment by troyeguo** [comment]
我这边 Windows 和 macOS 之间同步正常，请清空所有本地数据后，按照帮助文档重新尝试

**Comment by Visitant0226** [comment]
使用引用的方式打开文档时也正常吗，引用时并没有同步文档到另一个平台

**Comment by troyeguo** [comment]
同步功能不支持引用导入的图书

**Comment by vsdgniuz** [comment]
I have the exact same problem. I am using Google drive to sync the folders. Book imported on macOS says "Book not exist" on Windows and vice versa. I have cleaned all sync folders, set it up from scratch multiple times following the exact instructions in help. The books.json file has the path set as the path on macOS, not google drive. Has this issue been resolved? If yes, what should I do to correct the paths?
