### ISSUE TITLE
通过关联文件 pdf docx 打开主窗口提示书籍已存在后无后续操作

### ISSUE THREAD

**Issue by melinyi** [troyeguo/koodo-reader#366]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

last

### 我遇到的问题

通过关联文件 pdf docx 打开主窗口提示书籍已存在后无后续操作，仅仅是提示添加重复。其他格式文件测试会使用阅读器窗口打开这个文件。

**Comment by troyeguo** [comment]
感谢您的反馈，会后续版本中修复这个问题的
