### ISSUE TITLE
左侧菜单切换逻辑异常

### ISSUE THREAD

**Issue by sapceman** [troyeguo/koodo-reader#37]
左侧其他菜单切换到‘’全部图书”，如果打开“自动打开上次阅读的读书”开关，会自动打开上次阅读的读书，个人理解这时应该只是查看全部图书，并不想打开上次阅读的读书

**Comment by sapceman** [comment]
从“列表模式”切换至“卡片模式”也出现类似情况

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，这应该是一个bug，会在下一次版本更新修复的。
