### ISSUE TITLE
woff格式字体支持

### ISSUE THREAD

**Issue by toyang** [troyeguo/koodo-reader#373]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

woff格式字体无效，转为ttf也不行

### 细节描述

使用sigil制作的电子书使用了自定义中文字体（woff格式，里面重新定义了每个字的码值）且制作的epub为epub 3版本，在calibe中可以打开正常显示，在Koodo Reader中显示乱码，我搜了一下说epub 3规范要求支持woff格式字体的。
另外：转成ttf也无法显示

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by toyang** [comment]
> 麻烦您提供一下电子书文件

已经发送到官网提供的邮箱里

**Comment by toyang** [comment]
重新安装了1.4.1开发版，可以正常显示，但目前遇到比较大的问题是如果电子书比较大（100MB+或几百MB）的，点书签没反应，不会跳转（底部的loading已经没有了）
