### ISSUE TITLE
Header and Footer not sync (update) when move next, prev page

### ISSUE THREAD

**Issue by winterdl** [troyeguo/koodo-reader#38]
<img width="1082" alt="Screen Shot 2020-10-26 at 1 31 40 PM" src="https://user-images.githubusercontent.com/302480/97140694-c5217b00-178f-11eb-8b3d-5fca10e0f22c.png">

Koodo reader ver 1.1.7.145
Macos version, Web version

When I move next or prev page, the footer and header not update the page number or chapter name.

**Comment by troyeguo** [comment]
Thank you for the feedback, we will try to resolve it in the next version.
