### ISSUE TITLE
All of ebooks with AZW3 mode appear messy code.

### ISSUE THREAD

**Issue by fairgame88** [troyeguo/koodo-reader#382]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.3.9

### Bug Detail

All of ebooks with AZW3 mode appear messy code.

**Comment by troyeguo** [comment]
We have explained it in our document
