### ISSUE TITLE
次级目录跳转失效；滚动模式只能单章滚动；搜索页面打字时自动隐藏；mobi和azw3格式打开出错

### ISSUE THREAD

**Issue by gitbula** [troyeguo/koodo-reader#383]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.1

### 我遇到的问题

1. 总目录可以跳转，次级目录则没有反应，以前版本（1.3.9）前都没遇到这个问题，在1.4.1才遇到。
2. 滚动模式只能单章滚动，以前版本没这问题，1.3.9和1.4.1才遇到。
3. 搜索时一打字搜索页面就隐藏，虽然可以搜索，但有些不便。搜索时搜索页面能否固定，移开鼠标再隐藏？
4. 一部分mobi格式和所有azw3格式打开时背景透明，无法滚动（滚动模式下）。

![屏幕截图 2022-03-03 094605](https://user-images.githubusercontent.com/93466365/156480739-94f60520-72a0-49be-91bc-7e7144cfe5b1.jpg)
![屏幕截图 2022-03-03 094732](https://user-images.githubusercontent.com/93466365/156480751-7bd9f29b-f61f-44fc-af4b-9f2de5b82b23.jpg)
[Desktop.zip](https://github.com/troyeguo/koodo-reader/files/8174141/Desktop.zip)
![屏幕截图 2022-03-03 095055](https://user-images.githubusercontent.com/93466365/156480952-76d637ef-aac1-4ce2-9dbf-180a0b44d504.jpg)

**Comment by troyeguo** [comment]
麻烦您提供一下存在这些问题的电子书文件，滚动模式技术调整之后，只支持单章滚动，搜索的问题会在后续版本中修复的

**Comment by gitbula** [comment]
这个太多文件了，我的mobi和azw3格式书籍差不多都打不开，mobi倒是有一本能打开，而且也上传不了mobi和azw3格式的文件

**Comment by gitbula** [comment]
以后都不会支持全书滚动了吗？

**Comment by troyeguo** [comment]
> 以后都不会支持全书滚动了吗？

会考虑增加这个选项，我这边无法复现1和4的问题，麻烦您随意提供一两本，压缩为zip格式，拖拽到GitHub的输入框里，就可以上传了

**Comment by troyeguo** [comment]
最好提供一下截图或者录像

**Comment by gitbula** [comment]
问题1解决了，我打开全屏再退出全屏就可以跳转了。
问题3，搜索页面有时是固定的，有时会自动隐藏，特别是一开始打字或按确认键搜索时，之后大多都是固定的。
问题4，不能滚动的问题是我搞错了，因为单章滚动的原因，第一章内容极少，都是一页所以不能滚动。不过还是存在一些问题，透明背景，即使更改了背景颜色重新打开也是透明的，而且mobi和azw3格式都没有搜索框。
![屏幕截图 2022-03-03 101358](https://user-images.githubusercontent.com/93466365/156483135-3ebedb35-99ea-4a66-97ac-3db8dcb7b7bf.jpg)

**Comment by gitbula** [comment]
小窗口切换全屏时很容易卡

**Comment by troyeguo** [comment]
mobi, azw3的功能还在完善中，背景透明是因为开启了摸鱼模式，和背景色调节无关
