### ISSUE TITLE
a vscode extension

### ISSUE THREAD

**Issue by heartacker** [troyeguo/koodo-reader#384]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

it will be great to have a koodo reader extension for vscode

### Details

just like https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio

**Comment by troyeguo** [comment]
We don't have any plan to support vscode extension
