### ISSUE TITLE
书签

### ISSUE THREAD

**Issue by YUNDAN21** [troyeguo/koodo-reader#386]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

![image](https://user-images.githubusercontent.com/89337880/156882778-3466424f-e327-43ec-ae0f-721e3071d5bc.png)
书签

### Details

建议支持所有格式的文档添加书签，如今只有部分格式的文档能够添加书签

**Comment by troyeguo** [comment]
请升级至最新开发版
