### ISSUE TITLE
笔记链接和笔记内容不一致错误

### ISSUE THREAD

**Issue by wbdxin** [troyeguo/koodo-reader#388]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.41

### 我遇到的问题

我遇到的问题现象如下：
1.此现象出现在打开已有笔记的文件之后，[对新创建的笔记是可以正常跳转和编辑的]
2.当打开之前做过笔记的epub文件，选择笔记并跳转后，点击笔记点，弹出的内容并非历史笔记内容，而是最后的一条笔记
<img width="337" alt="koodo_note_feedback" src="https://user-images.githubusercontent.com/33190521/157784925-22f8e287-99ed-41aa-b160-bcf4bbefcea8.png">
如上图，笔记内容和标题不符

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题

**Comment by troyeguo** [comment]
请升级至最新开发版

**Comment by wbdxin** [comment]
您好，当前升级到1.4.3开发版
当点击笔记项的goto按钮，无反应，没有进行跳转
OS:win11

**Comment by troyeguo** [comment]
> 您好，当前升级到1.4.3开发版 当点击笔记项的goto按钮，无反应，没有进行跳转 OS:win11

感谢您的反馈，您方便提供一下您的图书的备份文件用于测试吗？
