### ISSUE TITLE
Need improve Touchmode

### ISSUE THREAD

**Issue by winterdl** [troyeguo/koodo-reader#39]
Touchmode: ON

- Could not select text to highlight or take node, it conflict with action navigate to next and prev page.
- Support swipe left or right to navagate between page (it's hard to determine what action user want to do: swipe to select text or swipe to navigate)

**Comment by troyeguo** [comment]
I'm not sure whether you follow the same step as i do, it works fine on my computer. First, long press on the first word you want to select, a text-selection widget will pop up, hold the widget and move the last word. the whole process won't trigger navigation action.
https://i.loli.net/2020/10/31/XKjHMNS7CvnBVsi.jpg

**Comment by winterdl** [comment]
You enable touch mode in Settings, then could not select text, I captured the screen as attach image
![Screen Recording 2020-10-31 at 5 06 20 PM](https://user-images.githubusercontent.com/302480/97776552-abbb6d00-1b9b-11eb-9a8c-8c35ac74648b.gif)

**Comment by troyeguo** [comment]
Maybe the name "touch mode" is little confused, you must first make sure your screen is a touch screen like the  screen on the Surface Book, then you can turn on the touch mode. It looks to me that you're still trying to select text with your mouse. Actually, with a touch screen  you can select the text by long pressing the screen with your finger. I'm sorry for the misleading translation.

**Comment by winterdl** [comment]
Sorry I did not test on mobile device, but chrome device simulator, I've just though that the chrome simulator could simulate touch events with mouse.

**Comment by troyeguo** [comment]
long press on the chrome simulator won't trigger text-selection widget, only real touch screen will.
