### ISSUE TITLE
How to implement slide animation when navigate next prev page

### ISSUE THREAD

**Issue by winterdl** [troyeguo/koodo-reader#40]
I've tried add attribute {scroll-behavior:smooth} (only chrome firefox support, not safari) to the viewarea but the scrolling too laggy. Do you any idea about implement page transition animation effect?

**Comment by troyeguo** [comment]
epub.js do not provide page transition animation api, the pages in the book are actually independent columns aligning horizontally in one single page. the only way to implement page transition animation is to add a sliding mask on the book when scrolling. i'm still trying to figure out the best way to do this.

**Comment by winterdl** [comment]
When test on phone, setup flow: paginated and snap:true, we could got page navigation effect when swipe left or right.
You could see in snap.js, but I dont know why they dont apply to desktop with mouse events.

![Screen-Recording-2020-11-05-at-11 13 15-PM](https://user-images.githubusercontent.com/302480/98266314-ba9b8880-1fbc-11eb-973a-1ffeea64120c.gif)

**Comment by troyeguo** [comment]
the snap.js only contains the touch event, you can find more here: https://github.com/futurepress/epub.js/blob/master/src/managers/helpers/snap.js
