### ISSUE TITLE
导入不同书籍出现图书重复

### ISSUE THREAD

**Issue by HHoao** [troyeguo/koodo-reader#401]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.1/1.3.9

### Bug Detail

https://user-images.githubusercontent.com/64757882/159818636-4f646912-24b9-4c3c-bba7-932d6c684e56.mp4

不同的pdf出现导入重复，尝试了两个版本都有此问题，尝试了清除缓存，清除数据，都无效

**Comment by troyeguo** [comment]
这个问题会在后续版本中修复的

**Comment by troyeguo** [comment]
您方便提供一下这两本书吗？

**Comment by HHoao** [comment]
似乎因为文件有点大上传不了，这两本书都超过了100M

**Comment by troyeguo** [comment]
可以用网盘或者邮件传吗？

**Comment by HHoao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "troyeguo/koodo-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 中午12:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [troyeguo/koodo-reader] 导入不同书籍出现图书重复 (Issue #401)





 
可以用网盘或者邮件传吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

SpringCloud微服务实战.pdf (175.47M, 2022年04月23日 12:55 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e616362a64c3993bc6c7025423603490059505a550401571d520152011b055556554e5a5c05014b545307535152505f08515053642f313540130a0c03755d094505adc0d3c8ff97fad4b6df4a465500305c&code=0acbd61f




Tomcat内核设计剖析.pdf (108.77M, 2022年04月23日 12:55 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2932373859d30a9fee3f247f12630b495a000f0956535a504f57000c054e0d0006501a5957075c4b5556020907560856560b0709347539320d5f545940a7e3dca9fbdf84f2a5f3a8941c475c526304&code=b2784c9f

**Comment by troyeguo** [comment]
已经收到，感谢回复

**Comment by troyeguo** [comment]
请升级至最新开发版
