### ISSUE TITLE
用键盘左右键翻页的时候，会因为遇到新章节失效

### ISSUE THREAD

**Issue by xx990410** [troyeguo/koodo-reader#404]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

用键盘左右键翻页的时候，每次遇到新的章节，此功能就失效了，必须用鼠标左键点击一下书籍页面，该功能才会重新可用，直到遇到下一个新章节。

### 截图或录像(可选的)

https://user-images.githubusercontent.com/53733191/160334589-1f5a4ca0-7858-4534-83a4-2c284672ca57.mp4

### 图书文件(可选的)

[Uploading Immanuel Kant Die drei Kritiken - Kritik der reinen Vernunft. Kritik der praktischen Vernunft. Kritik der Urteilskraft by Kant, Immanuel (z-lib.org).zip…]()

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题的

**Comment by RMSSID** [comment]
是的，我也遇到这个问题，经常键盘翻页失效。

**Comment by troyeguo** [comment]
请升级至最新开发版
