### ISSUE TITLE
按F11键不能进入全屏，建议支持全屏快捷键F11

### ISSUE THREAD

**Issue by RMSSID** [troyeguo/koodo-reader#405]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.1

### Bug Detail

全屏不支持F11快捷键，只能通过鼠标点进入全屏按钮才能进入全屏；建议可以通过按钮F11进入全屏模块和退出全屏模块

**Comment by troyeguo** [comment]
请升级至最新开发版
