### ISSUE TITLE
ARM64- v“Koodo Reader.app” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by cocoonkid** [troyeguo/koodo-reader#406]
### I've already installed the latest developer version of Koodo Reader, this problem still exists

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12- Arm64

### App Version

1.4.1-Arm64

### Bug Detail

ARM64-M1 version does not open at all.

x86 works.

### Screenshots (Optional)

![CleanShot 2022-03-30 at 11 50 39@2x](https://user-images.githubusercontent.com/43231640/160803848-82bf4192-00e3-4fcc-8fb3-dea68fbfc052.jpg)

**Comment by troyeguo** [comment]
Please refer to our document

**Comment by cocoonkid** [comment]
@troyeguo 

I would but it is not in English and as it is in notion I cannot auto translate  it.

The issue still persists

**Comment by cocoonkid** [comment]
I was able to find the important bits and  to  fix it.   The same problem exists for homebrew installed Chromium.

`xattr -cr /Applications/kodoo\ Reader.app`

Thanks!
