### ISSUE TITLE
建议在笔记部分也呈现笔记所引用的文字

### ISSUE THREAD

**Issue by lushlush** [troyeguo/koodo-reader#41]
其实可以考虑将书摘和笔记做成一个东西，或者在笔记部分也呈现笔记引用的原文。不然如果过段时间去看笔记的话，光看笔记不知道笔记对应着什么内容。
最后，感谢开发者，软件真的很好。

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，其实点击笔记的下方的显示笔记出处，就可以跳转到原文，笔记的原文也会以高亮形式显示，在之前的版本也做过在笔记下方直接显示原文内容，后来主要考虑到减少代码量，还有样式排版的问题，就去除掉了。

**Comment by lushlush** [comment]
谢谢回复！
我的想法是，点击跳转原文的话，其实个人觉得不是特别方便，因为就想着如果复习笔记的时候，正好对应着笔记和标黄的地方复习，就可以不用一次次地打开书籍了。而且笔记是基于引用原文的，所以就觉得两者同时呈现会更好。
不过这可能是个人使用习惯问题，不代表所有人都有这个问题。也辛苦你了~
