### ISSUE TITLE
返回主窗口导致闪退？

### ISSUE THREAD

**Issue by yichangshengwu** [troyeguo/koodo-reader#410]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

其他 Linux 发行版

### Koodo Reader 版本

1.4.1

### 我遇到的问题

开启了“直接在主窗口打开图书”后，
阅读中点击右下角的主页按钮，程序退出了？
（未感知到有主窗口出现的迹象，应该直接退出了）

若是不在主窗口阅读，
关闭阅读窗口倒是没发现异常，

系统是 arch linux, 
装的是 archlinuxcn 源里的版本，
konsole 里也没给什么有价值的信息...

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复这个问题的

**Comment by troyeguo** [comment]
请升级至最新开发版

**Comment by yichangshengwu** [comment]
已不再闪退了，
辛苦啦
