### ISSUE TITLE
epub文件点击目录 无法跳转

### ISSUE THREAD

**Issue by sudongpokaorouu** [troyeguo/koodo-reader#411]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.1

### 我遇到的问题

epub文件点击目录 无法跳转

### 截图或录像(可选的)

<img width="223" alt="Snipaste_2022-04-04_11-07-36" src="https://user-images.githubusercontent.com/81897619/161467411-b2721201-32df-4b06-8d9e-97f2d24ad37e.png">

### 图书文件(可选的)

[Uploading 鲁迅全集 (鲁迅,墨盟) (z-lib.org).zip…]()

**Comment by troyeguo** [comment]
麻烦您重新上传一下图书

**Comment by sudongpokaorouu** [comment]
[鲁迅全集 (鲁迅,墨盟) (z-lib.org).zip](https://github.com/troyeguo/koodo-reader/files/8456067/z-lib.org.zip)

**Comment by troyeguo** [comment]
会在后续版本修复这个问题的

**Comment by troyeguo** [comment]
请升级至最新开发版
