### ISSUE TITLE
txt格式增加全局搜索功能

### ISSUE THREAD

**Issue by riverwalker01** [troyeguo/koodo-reader#413]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

希望txt格式的书能支持 全局搜索功能

### 细节描述

目前全局搜索功能只有 epub格式的书才支持，其它格式好像都没有 全局搜索 按钮，希望能加上，毕竟这是个很重要的功能

**Comment by troyeguo** [comment]
这个功能会在下个版本推出的

**Comment by troyeguo** [comment]
请升级至最新开发版

**Comment by riverwalker01** [comment]
已升级，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "troyeguo/koodo-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月17日(星期天) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [troyeguo/koodo-reader] txt格式增加全局搜索功能 (Issue #413)





 
请升级至最新开发版
