### ISSUE TITLE
epub与mobi上下空白不一致，且epub空白过大

### ISSUE THREAD

**Issue by diziww** [troyeguo/koodo-reader#417]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.3.9

### Bug Detail

mobi的书打开后，上下空白比较小

epub的书打开后，上下空白会比较大，有一点影响了内容

我试了几本书都是这样

不过我发现看pdf书籍的窗口界面意外的好，epub可以类似那个界面就好了

### Screenshots (Optional)

这是有epub的，可以看到空白大约占了五分之一屏幕了
![image](https://user-images.githubusercontent.com/68603389/162563818-b8cccb7a-0df5-4bdd-8225-a5aaac163655.png)

这是mobi的书，空白部分就比较小，没有很影响阅读
![image](https://user-images.githubusercontent.com/68603389/162563755-2b1d4613-c880-456c-bae9-db6e27c7bb5b.png)

**Comment by troyeguo** [comment]
请升级至最新开发版
