### ISSUE TITLE
Support fo other language(Bangla language)

### ISSUE THREAD

**Issue by abusayed0206** [troyeguo/koodo-reader#419]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

When I open Bangla pdf it shows weird characters ! 

### Details

Here is a screenshot of this: http://link.abusayed.dev/T07I1c

**Comment by troyeguo** [comment]
Please try to import this book in our web version. if you get any warnings, then this issue has nothing to do with language but with its compression algorithm.
