### ISSUE TITLE
mobi格式是怎么解析的

### ISSUE THREAD

**Issue by alexmay21** [troyeguo/koodo-reader#42]
hello，想问下mobi格式的文件是怎么解析的呢

**Comment by troyeguo** [comment]
您好，mobi格式用到了这个文件 https://github.com/troyeguo/koodo-reader/blob/master/src/utils/mobiUtil.js
首先用这个文件提取文字，解析成txt格式，再将txt格式转化为epub格式，再用epub.js展示图书内容

**Comment by mrmarktyy** [comment]
@troyeguo https://imclient.herokuapp.com/mobiviewer/ 
这个插件可以直接读取本地mobi，我不知道它是怎么实现的 
你可以看下是不是有什么启发

**Comment by troyeguo** [comment]
> @troyeguo https://imclient.herokuapp.com/mobiviewer/
> 这个插件可以直接读取本地mobi，我不知道它是怎么实现的
> 你可以看下是不是有什么启发

感谢您的建议，其实解析mobi的这个文件我也是直接从类似的项目中直接复制过来的，但最难的不是展示mobi文件，而是记录阅读位置，进度跳转，解析目录，这些功能还是只能借助epub.js来实现，目前比较棘手的问题是mobi文件到epub文件的转换过程中，如何保留图片。

**Comment by mrmarktyy** [comment]
谢谢回答。我也有点理解这个问题了。
我正在尝试做个mobi/epubjs的手机阅读app（用RN实现）

正在研究怎么做mobi文件的翻页功能。。

**Comment by troyeguo** [comment]
> 谢谢回答。我也有点理解这个问题了。
> 我正在尝试做个mobi/epub的读书app（用RN实现）
> 
> 正在研究怎么做mobi文件的翻页功能。。

我之前也打算用RN和expo开发Koodo Reader的移动版，设计稿已经画好了，App的模板也已经开发完成了，但我发现epub.js的RN版不支持在expo的managed workflow下运行，但eject之后又无法使用expo publish来生成安装包，所以就作罢了。请问你的app是怎么解析epub文件的？

**Comment by mrmarktyy** [comment]
我打算都用WebView来对付了，对epub和mobi的展现都用浏览器里实现。
从app里读取文件系统文件后也可以传送给webview

**Comment by troyeguo** [comment]
> 我打算都用WebView来对付了，对epub和mobi的展现都用浏览器里实现。
> 从app里读取文件系统文件后也可以传送给webview
> 
> > 但我发现epub.js的RN版不支持在expo的managed workflow下运行，但eject之后又无法使用expo publish来生成安装包
> 
> 嗯 感觉需要针对RN重写epubjs里的render logic把，

我找到了一个类似的项目，也是用webview和epubjs来实现的，https://github.com/farshed/duofolio，但它也需要修改安卓文件夹下的gradle文件，才能实现webview打开指定的html文件，你的项目是在原生react native 环境下开发的吗？

**Comment by mrmarktyy** [comment]
我目前还是用Expo，确实在特定需求中很受限。 

因为webview和rn是互通的，不知道能不能把html发送给webview， 然后webview里再通过innerHTML之类的方法来render

**Comment by mumujj** [comment]
问一下mobi格式的目录和内容中的图片怎么读取的呢？

**Comment by asgsdbrseg** [comment]
> 谢谢回答。我也有点理解这个问题了。 我正在尝试做个mobi/epub的读书app（用RN实现）
> 
> 正在研究怎么做mobi文件的翻页功能。。

进度查询

**Comment by hhk-png** [comment]
> > 谢谢回答。我也有点理解这个问题了。 我正在尝试做个mobi/epub的读书app（用RN实现）
> > 正在研究怎么做mobi文件的翻页功能。。
> 
> 进度查询

翻页的话我知道三种方案，
1.第一个是使用css的column属性，配合transform、posotion:absolute等可以位移的属性，底层的逻辑交给浏览器实现。但是这种方法在选中文本的时候，在鼠标移动到空白处时，会出现反向选择的情况，找了挺长时间也不知道怎样解决。除了这个bug，其他的能想到的排版功能结合css都可以实现的差不多了。

2.Epub.js这个库应该是自己实现了一个分页的逻辑，没有细看。

3.如果要说分页的话还有一种方法是使用svg中的text，image等标签进行渲染，相当于自己实现一个排版引擎，比如得到、多看阅读是这样做的。

第一种和第三种我在我正在写的这个库 [https://github.com/hhk-png/svg-ebook-reader](https://github.com/hhk-png/svg-ebook-reader) 里面实现了一下。基于css column的方案基本上实现了。使用svg做排版的我简单实现了一个，不过效率贼慢，尤其是渲染中文文本的时候，因为需要用到playwright测量单个汉字的字符长宽，在浏览器中没测试过。

还有前面你们说到的跳转功能，不知道是不是点击书籍中的a标签进行书籍章节的跳转，这个可以通过给书里的a标签的href来添加一些前缀头，比如 'innerATag:[href]' ，然后在ui层面对a标签的跳转进行一个拦截来实现。这个还没做过
