### ISSUE TITLE
批量管理

### ISSUE THREAD

**Issue by zszknight** [troyeguo/koodo-reader#420]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

希望能增加一些批量管理的功能

### 细节描述

无法一次性选择多个文件，移到自己的子分类中去

**Comment by troyeguo** [comment]
请点击左上角的选择按钮
