### ISSUE TITLE
pdf文件第一頁或者第二頁來當書籍封面

### ISSUE THREAD

**Issue by youkeith** [troyeguo/koodo-reader#421]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

希望pdf文件第一頁或者第二頁來當書籍封面,這也不會顯示太多文字影響美觀.

### 细节描述

希望pdf文件 第一頁或者第二頁來當書籍封面,這也不會顯示太多文字影響美觀.

**Comment by troyeguo** [comment]
请升级至最新开发版
