### ISSUE TITLE
导入200本以上的书就会卡死，备份到本地卡死无反应！！！

### ISSUE THREAD

**Issue by yuh1898** [troyeguo/koodo-reader#422]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

导入200本书，性能太差

**Comment by troyeguo** [comment]
请升级最新开发版
