### ISSUE TITLE
导入大小10m左右的txt格式小说打开很慢很慢很慢.....

### ISSUE THREAD

**Issue by ebasegykj** [troyeguo/koodo-reader#425]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.3.9

### Bug Detail

导入大小10m左右的txt格式小说打开很慢很慢很慢.....

**Comment by uniform641** [comment]
1.5.1版本同样有这个问题，20MB左右的txt文件多次无法打开，或打开后使用左边栏目录跳转时卡死。

**Comment by troyeguo** [comment]
请升级至最新开发版，并使用预缓存功能
