### ISSUE TITLE
Open pdf file in the epub reader

### ISSUE THREAD

**Issue by ToTheMoon1234** [troyeguo/koodo-reader#426]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

The pdf file opened through koodo opens in the mozilla pdf reader. Is there any way it can be opened in the reader which comes on opening an ePub file?

### Details

This is because the mozilla reader has no option, as per my knowledge, to annonate or highlight on pdf while the epub reader is better with many options. So if pdfs can be opened via epub reader or any other reader where annotation and highlighting on pdf is allowed would be helpful to many people. This option can be made optional as per as user choice.

Thanks.

**Comment by troyeguo** [comment]
the pdf reader comes with the same anotation and highlight tools in epub reader. Make sure you're using the latest version from github release

**Comment by troyeguo** [comment]
Please upgrade to 1.4.2
