### ISSUE TITLE
在高亮文本后删除高亮，文字依然是高亮的

### ISSUE THREAD

**Issue by FengYu98** [troyeguo/koodo-reader#427]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

在选择一段文字将其高亮后，再删除高亮，文字依然是高亮的

**Comment by troyeguo** [comment]
请升级至最新开发版
