### ISSUE TITLE
1.4.2版本 epub文件缺失封面时，无法打开、无法被导入书库

### ISSUE THREAD

**Issue by lilyblessing** [troyeguo/koodo-reader#428]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.2

### 我遇到的问题

当epub文件缺失封面时，无法打开无法被导入书库。
在低版本中导入过的图书不受影响，升级后删除再导入则失败，手动添加封面后导入成功。
测试其他文件如PDF、mobi则无此问题。

### 图书文件(可选的)

[图书样例.zip](https://github.com/troyeguo/koodo-reader/files/8501134/default.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题的

**Comment by troyeguo** [comment]
请升级至1.4.2版
