### ISSUE TITLE
备份与恢复

### ISSUE THREAD

**Issue by 913650629** [troyeguo/koodo-reader#43]
您好大神，这个可以将备份与恢复功能和坚果云进行联动么？
在(C:\Users\Administrator\AppData\Roaming\koodo-reader)文件夹，创建一个专门的文件夹，例如(C:\Users\Administrator\AppData\Roaming\koodo-reade\backup)，在backup文件夹里，创建两个子文件夹（equb、data），可以设置一个选项（自动恢复备份），每次启动后自动，从这两个文件夹校检变化（可以通过时间），若发生变化（即在电脑a上对书籍进行了批注），坚果云会将这个变化同步到登录电脑b中。当电脑b打开软件时，自动恢复备份，此时，电脑a和b就相当于简单的云同步了。
希望大神，能试着去实现此联动。

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，自动备份同步功能会考虑在后续的版本中支持，和坚果云联动会考虑通过webdav的方式进行，创建专门的备份文件夹技术实现上没有问题，但过于繁琐了。

**Comment by 913650629** [comment]
谢谢大佬，爱你爱你，用了你的阅读器就很舒服
