### ISSUE TITLE
1.4.2开发版翻页经常卡死

### ISSUE THREAD

**Issue by riverwalker01** [troyeguo/koodo-reader#430]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.2

### 我遇到的问题

1.4.2开发版在翻页的时候经常性卡死，卡死之后页面就变空白了，而且一旦出现这种情况之后即使重启软件也无法打开该书籍，只有删除重新导入方可阅读。
1.4.2版本翻页很卡，有很严重的滞后感觉，1.4.1无该问题。

### 截图或录像(可选的)

![1](https://user-images.githubusercontent.com/103118771/163722200-a842abcd-01e3-46e8-aa29-90b2770bdbc5.jpg)
![2](https://user-images.githubusercontent.com/103118771/163722242-8e2084db-a693-4af3-bd6a-8b37e77f3145.gif)

### 图书文件(可选的)

[哈利波特與火焰杯.zip](https://github.com/troyeguo/koodo-reader/files/8501927/default.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by Dgnic** [comment]
我也遇到了这个问题，在左菜单跳章节的时候整本书卡住无法打开，重启软件也没有解决。由于原来的书籍有一些高亮与备注，下不去手直接删除，下一个版本修复后可以直接打开原来出问题的书吗？

**Comment by troyeguo** [comment]
请升级至1.4.2版

**Comment by Dgnic** [comment]
就是在 1.4.2 开发版遇到的 Bug.

**Comment by troyeguo** [comment]
请升级至1.4.3版

**Comment by troyeguo** [comment]
刚发布的，刚才发错了，本来想过来改的

**Comment by Dgnic** [comment]
更新之后，上个版本卡住的书似乎还是没办法打开，可能要重新导入了...
![](https://cdn.jsdelivr.net/gh/Dgnic/Multifarious-image-@master/img202204231718744.png)

**Comment by troyeguo** [comment]
请更新至最新开发版
