### ISSUE TITLE
win10 epub进入书籍  点击窗口最大化  方向键翻页失效

### ISSUE THREAD

**Issue by He-Xun** [troyeguo/koodo-reader#436]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

win10 epub进入书籍  点击窗口最大化  方向键翻页失效
如果不最大化 以窗口模式  方向键是可以用的

### 图书文件(可选的)

![image](https://user-images.githubusercontent.com/17931864/164382741-692cf2e5-d514-4482-a4b6-18c93fac68a1.png)

**Comment by troyeguo** [comment]
感谢反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级至1.4.2版
