### ISSUE TITLE
安卓版本

### ISSUE THREAD

**Issue by crushslh** [troyeguo/koodo-reader#442]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

能开发安卓版本吗

### Details

能开发安卓版本吗

**Comment by PineSongCN** [comment]
安卓版本，用 《静读天下》吧，或者建议直接起点小说阅读器，就算只看本地也是很优秀的阅读器。

**Comment by salamander7456** [comment]
> 安卓版本，用 《静读天下》吧，或者建议直接起点小说阅读器，就算只看本地也是很优秀的阅读器。

您好，我想請問下，靜讀天下的webdrive雲同步（我用的堅果雲），能夠兼容Koodo嗎？因為我手機用的靜讀天下，想看看能否同步
