### ISSUE TITLE
搜索结果 文本溢出

### ISSUE THREAD

**Issue by ZIDOUZI** [troyeguo/koodo-reader#447]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.43

### 我遇到的问题

如图,搜索框文本溢出

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/53157536/166088782-92280839-d387-4e8a-ab18-740f14c42ef9.png)
![image](https://user-images.githubusercontent.com/53157536/166088855-10878cab-c83f-4e9d-a856-c54a17231718.png)

### 图书文件(可选的)

https://book.kotlincn.net/kotlincn-docs.epub

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级最新开发版
