### ISSUE TITLE
Koodo cannot import certain epub books

### ISSUE THREAD

**Issue by HanaK91** [troyeguo/koodo-reader#451]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.3

### Bug Detail

Some epubs just won't import into Koodo. I am sending an example of one such book as a zip file.

### Files (Optional)

[Cesta na sever - Karel Capek.zip](https://github.com/troyeguo/koodo-reader/files/8602011/Cesta.na.sever.-.Karel.Capek.zip)

**Comment by troyeguo** [comment]
Thanks for the feedback, we will fix it in the next update

**Comment by troyeguo** [comment]
This epub file is not packed with a professional epub tool, There may be some compatible issues with our epub parser. We recommend importing this book after converting with Calibre.
