### ISSUE TITLE
翻书时卡顿和显示空白

### ISSUE THREAD

**Issue by yhcad** [troyeguo/koodo-reader#452]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

Koodo-Reader-1.4.3

### 我遇到的问题

翻书时卡顿和显示空白

**Comment by troyeguo** [comment]
会在下个版本修复的

**Comment by EricSolshkov** [comment]
类似的问题：
快速使用滚轮来回翻页会触发空白显示和无法翻页（包括翻页按钮和方向键）的bug，此时页眉显示Unknown Chapter，页码章节出现以下情况（不总是出现同一种，不总是同时出现）1.章节数显示为-1，2.页码超出本章页数；
无法通过任何方式离开此状态，只能退出阅读（有时仍不能解决），或删除图书，重新导入

**Comment by troyeguo** [comment]
> 

感谢您的反馈

**Comment by troyeguo** [comment]
请升级最新开发版

**Comment by pengzij** [comment]
> 请升级最新开发版

已经升级到1.4.4开发板，出现翻页后书本打开后变成空白，重启软件无法解决。删除当前书本，重新导入书本恢复。

**Comment by licongliyu** [comment]
升级到开发版1.4.5还是出现同样的问题 看来这个问题暂时还没有完全解决

**Comment by pengzij** [comment]
> 升级到开发版1.4.5还是出现同样的问题 看来这个问题暂时还没有完全解决

特别是当我短时间连续点击翻页或者多个按键时，几乎会稳定触发这个问题。阅读PDF似乎没遇到该问题，但是epub文件很容易触发该问题。

**Comment by troyeguo** [comment]
请更新至最新开发版
