### ISSUE TITLE
导入 “.PDF”格式的文件时失败

### ISSUE THREAD

**Issue by yiletianya** [troyeguo/koodo-reader#453]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Chrome 及其他 Chromium 浏览器(包括 Edge 和所有国产浏览器)

### Koodo Reader 版本

1.4.0

### 我遇到的问题

使用docker端Koodo Reader时，批量导入 “.PDF”格式的文件时失败，且无任何提示，但导入“.pdf”格式可以。特别是批量导入时，一旦 中间有“.PDF”格式的文件，后面的文件都受影响无法导入且无任何提示。

**Comment by troyeguo** [comment]
麻烦您提供一下电子书源文件

**Comment by troyeguo** [comment]
请升级最新开发版
