### ISSUE TITLE
开关全屏模式时，高亮无法正常显示

### ISSUE THREAD

**Issue by EinNiemand28** [troyeguo/koodo-reader#456]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

Koodo-Reader-1.4.3

### Bug Detail

进入全屏后高亮不再显示，且此时退出全屏仍无法显示
需重新打开书籍才能正常显示

**Comment by EinNiemand28** [comment]
全屏模式下标注的高亮也不能显示，需退出全屏重新打开书籍

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级最新开发版
