### ISSUE TITLE
目录无法正常跳转，该文件在NeatReader中目录跳转正常

### ISSUE THREAD

**Issue by ybcheng001** [troyeguo/koodo-reader#46]
![image](https://user-images.githubusercontent.com/50897579/102294437-42918c80-3f84-11eb-9c3d-f1f78ed7cb0b.png)

**Comment by ybcheng001** [comment]
epub.min.js:1 Uncaught (in promise) Error: No Section Found
    at b._display (epub.min.js:1)
    at e.a.dequeue (epub.min.js:1)
    at epub.min.js:1

**Comment by troyeguo** [comment]
您好!
感谢您的反馈，如果示例图书可以正常跳转的话，问题就出在图书本身，可能是图书在打包成epub格式的时候，并没有完全遵守epub的标准规范。Neat Reader和 Koodo Reader 采用了不同的epub解析引擎，无法保证图书在两个软件都以同样的方式工作，您可以把该图书发送的我的邮箱：guo362429@gmailcom，方便测试和改进解析算法。

示例图书下载地址：https://reader.960960.xyz/assets/demo.epub
