### ISSUE TITLE
Koodo reader 笔记及高亮注释显示问题

### ISSUE THREAD

**Issue by logan00000000** [troyeguo/koodo-reader#461]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

***
- 书籍格式`.epub`
***
1. **笔记内容**有时候不能打开，或者打开是空白。
2. **笔记内容**打开第一个显示后，所有的笔记都是前一个打开的内容，其中包含高亮但没有做过笔记注释
3. 有些书籍无法打开，进入之后直接卡死
4. 目录有时候无法跳转，退出重新进入会变好

**Comment by troyeguo** [comment]
请升级最新开发版
