### ISSUE TITLE
听书和阅读时自动翻阅

### ISSUE THREAD

**Issue by NRWDNL999** [troyeguo/koodo-reader#462]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

听书和阅读时自动翻阅

### 细节描述

听书支持自定语音包和阅读时自动翻阅下一页解放双手

**Comment by liliadamth** [comment]
希望添加这个功能。

**Comment by troyeguo** [comment]
这个功能一直就有

**Comment by liliadamth** [comment]
> 

非常感谢您的回复，网页版使用微软TTS时，有时会有重复阅读的问题，我误以为没有自动翻阅，十分抱歉。
