### ISSUE TITLE
滚动模式下，字会贴在页面两边。

### ISSUE THREAD

**Issue by gitbula** [troyeguo/koodo-reader#463]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.4

### 我遇到的问题

滚动模式下，字会贴在页面两边，1.4.2到1.4.4版本都是如此。

### 截图或录像(可选的)

![Uploading 屏幕截图 2022-05-22 095426.jpg…]()

**Comment by troyeguo** [comment]
你的截图上传失败了

**Comment by gitbula** [comment]
![屏幕截图 2022-05-22 095426](https://user-images.githubusercontent.com/93466365/169924148-e2290dc1-dcec-4d50-ae2d-42920fd72372.jpg)

**Comment by troyeguo** [comment]
您好，我这边没法复现，是所有图书都存在这个问题吗？

**Comment by gitbula** [comment]
![屏幕截图 2022-05-24 113519](https://user-images.githubusercontent.com/93466365/169944052-6412d6e3-122e-4bc0-8690-4971d24df836.jpg)
![屏幕截图 2022-05-24 113606](https://user-images.githubusercontent.com/93466365/169944062-0d53cdd6-b6d5-4628-9bf6-c79409b87f67.jpg)

**Comment by troyeguo** [comment]
退出摸鱼模式后还存在这个问题吗？

**Comment by gitbula** [comment]
还是一样

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复这个问题的
