### ISSUE TITLE
Can we have bionic reading feature in Koodo?

### ISSUE THREAD

**Issue by mohitmujawdiya** [troyeguo/koodo-reader#464]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

A similar implementation would be very appreciated!

### Details

Hi, is an implementation like bionic reading possible on Koodo? Here is an example:

![image](https://user-images.githubusercontent.com/61835205/169839516-33f55f32-b3e5-4dbd-b240-cf295ac87fa7.png)

This method helps people read efficiently. An extension has already been made for Chrome. Here is the repo in case the code is helpful. (https://github.com/ansh/bionic-reading)

Bionic Reading is patented in France and trademarked in some other countries, but I am sure it won't be much of an issue (https://www.reddit.com/r/ObsidianMD/comments/uv995v/bionic_reading_seems_great_but_patent_is_a_bummer/)

**Comment by troyeguo** [comment]
> Any updates regarding this feature?

It's already supported in the latest developer version. 
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/7d541b52-5f20-4932-952d-4997c8376822)
