### ISSUE TITLE
图书重复

### ISSUE THREAD

**Issue by zhiyuan-liao** [troyeguo/koodo-reader#465]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.39

### Bug Detail

当我导入一本书的时候，发现提示图书重复。但是我无法通过日志或者后台检查重复的图书。
实际上并不是一本重复的图书。

**Comment by troyeguo** [comment]
请升级最新开发版
