### ISSUE TITLE
中文听书功能建议

### ISSUE THREAD

**Issue by difinini** [troyeguo/koodo-reader#468]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

Edge的中文AI语音比目前的好很多，是否可以替换目前的AI语音呀？

### 细节描述

Edge的中文AI语音比目前的好很多，是否可以替换目前的AI语音呀？

**Comment by difinini** [comment]
我找到了..是我没发现不好意思

**Comment by bzhltl** [comment]
> 是否可以替换目前的AI语音呀？

在哪可以选，我这只能选择离线的语音，在线的语音没得选。

**Comment by troyeguo** [comment]
目前不支持edge的ai语音，技术上也没法实现

**Comment by troyeguo** [comment]
已支持

**Comment by bzhltl** [comment]
感谢，先试用一下
