### ISSUE TITLE
听书功能BUG

### ISSUE THREAD

**Issue by bamlan** [troyeguo/koodo-reader#47]
在WIN10 x64系统下，使用听书功能，只能听当前页，调试了下发现，src\containers\settingPanel\component.tsx 的handleAudio函数有BUG，文件第72、73行：

        this.props.currentEpub.rendition.next();
        this.handleAudio();

改为：
        this.props.currentEpub.rendition.next().then(this.handleAudio);

第69行  if (!this.state.isAudioOn /*|| this.props.isReading*/) 中的this.props.isReading一直为true, 未跟到什么时机修改这个值，注释后暂时能正常听书。

另外：我升级了electron到11后，使用release模式打包的文件运行时，读取app.asar中的文件报解包错误，降electron版本到10后运行正常。

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题。
