### ISSUE TITLE
koodo reader  导入、打开图书问题

### ISSUE THREAD

**Issue by SwordArtOnlineKiritoChen** [troyeguo/koodo-reader#48]
最新版本
可以正常导入图书  
打开图书非常之慢  图书文件打开一直处于转圈状态 
（可能是文件太大？ 我将一些epub格式单行本利用calibre合并后打开  小文件可以正常使用）
使用Starrea打开文件 一秒打开文件 

图书导入功能 刷新时间有问题 有时候导入后 需要重启才能看到

**Comment by SwordArtOnlineKiritoChen** [comment]
使用体验： 外貌UI设计 还不错 
但是在书籍的处理上面还需更多优化  加入批处理 快捷键等操作

**Comment by SwordArtOnlineKiritoChen** [comment]
怀疑文件大小影响文件打开速度：
35310KB 72306KB大小文件可以正常打开 
147118KB大小文件无法正常打开

可能对于文件的解析方面还有待加强

**Comment by SwordArtOnlineKiritoChen** [comment]
同步备份 多元化  支持网盘  云服务器等

**Comment by troyeguo** [comment]
感谢您的反馈，koodo reader基于electron和JavaScript编写，性能上和calibre，starrea这些基于原生语言编写的软件肯定没法比的，因此不建议使用本软件阅读较大体积的电子书，感谢您的建议，会考虑在后续版本中添加这些功能的。

**Comment by tiny-andr** [comment]
希望阔以一次性添加某个目录下的所有图书，有些打包好的txt小说包解压之后就是一个弄好的目录，然后里面也是分类好的目录，一个一个导入起来有点麻烦～。😀

**Comment by troyeguo** [comment]
> 希望阔以一次性添加某个目录下的所有图书，有些打包好的txt小说包解压之后就是一个弄好的目录，然后里面也是分类好的目录，一个一个导入起来有点麻烦～。😀

感谢您的建议，会考虑在后续版本中增加这个功能的

**Comment by TAODEI** [comment]
你好，为什么我导入教材的答案就提示图书重复无法添加

**Comment by Cu1ii** [comment]
> 你好，为什么我导入教材的答案就提示图书重复无法添加
现在也有这个问题
