### ISSUE TITLE
新版本出现A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Bruce-Wall** [troyeguo/koodo-reader#480]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

去年10月有用户在Issue里提出了类似bug，在回复里当时的新版本已经解决了问题。但我使用现在的新版本时，这个问题又出现了。启动时就会出现如图所示对话框然后退出。

### 截图或录像(可选的)

<img width="418" alt="Koodo_Reader_wYqZHjK2U5" src="https://user-images.githubusercontent.com/18501962/172089738-29918b30-60d6-4783-abbc-db3e6a88612c.png">

**Comment by troyeguo** [comment]
请下载最新开发版

**Comment by Bruce-Wall** [comment]
> 请下载最新开发版

下载了1.4.4版，问题依旧。

**Comment by troyeguo** [comment]
感谢您的反馈

**Comment by troyeguo** [comment]
请升级至最新开发版
