### ISSUE TITLE
请问软件的翻译引擎用的是哪个?

### ISSUE THREAD

**Issue by kongzhixin** [troyeguo/koodo-reader#481]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

翻译效果比较好,希望了解下翻译引擎

### 细节描述

翻译效果比较好,希望了解下翻译引擎

**Comment by troyeguo** [comment]
百度翻译
