### ISSUE TITLE
I have found a little wrong expression in lanuage section in setting window.

### ISSUE THREAD

**Issue by molajusi** [troyeguo/koodo-reader#483]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.4

### Bug Detail

I have found a little wrong expression in lanuage section in setting window.
"한국인" means "Korean people".
So "한국인" should be changed to "한국어" in korean text.

### Screenshots (Optional)

![image](https://user-images.githubusercontent.com/64630607/172579309-257914fa-6623-4a1c-83a4-7416c19b14d5.png)

**Comment by troyeguo** [comment]
Thanks for the feedback, we will fix it in the next update

**Comment by troyeguo** [comment]
Please update to version 1.4.5
