### ISSUE TITLE
建议多级目录增加一键收起、一键展开

### ISSUE THREAD

**Issue by authorizationppp** [troyeguo/koodo-reader#485]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

目前具有多级目录的PDF默认全部目录展开，目录很长时通过目录查找内容比较麻烦，建议默认多级目录收起或者增加一键收起功能。

### 细节描述

目前具有多级目录的PDF默认全部目录展开，目录很长时通过目录查找内容比较麻烦，建议默认多级目录收起或者增加一键收起功能。

**Comment by troyeguo** [comment]
设置里有
