### ISSUE TITLE
听书功能第一次开启，“开启听书”模块会消失

### ISSUE THREAD

**Issue by eaudouce** [troyeguo/koodo-reader#486]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.4

### 我遇到的问题

听书功能第一次开启，“开启听书”模块会消失。退出再重开才恢复正常。

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至最新开发版
