### ISSUE TITLE
选项可控制鼠标横向滚动不触发翻页

### ISSUE THREAD

**Issue by complyue** [troyeguo/koodo-reader#487]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

增加选项, 控制鼠标横向滚动不触发翻页

### 细节描述

苹果 Magic 鼠标整个表面是个触控板, 默认发送360°滚动事件, 阅读时比较容易误触横滚导致意外翻页. 希望能有个选项禁止横滚翻页.

**Comment by troyeguo** [comment]
不好意思，我没有这种鼠标，没办法测试

**Comment by troyeguo** [comment]
谢谢您的好意，其实我也只有Windows电脑，实在不用为了一个bug，让您这样破费

**Comment by complyue** [comment]
嗯, 如果近期没有入手Mac的计划确实不方便测. 不过这个bug对我来说还是挺烦恼的, 找个时间我看准备个PR吧, 做点贡献. 

Koodo确实很棒, 感谢你的开源贡献/付出!

**Comment by complyue** [comment]
先记一下, 应该是 https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent 这里, 通过 ·WheelEvent.deltaMode· 区分, 以像素为单位滚动时很小的 ·deltaX· ·deltaY· 值不要响应就对了. 增加选项的话应该可以是个 “滚动灵敏度” 的拖动条.

**Comment by complyue** [comment]
@troyeguo 按 https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event 的说法, `wheel` 事件是标准的 api, 以前常用的非标准 `mousewheel` 事件应该避免使用. Chrome 从 61 版, Firefox 从 17 版开始就支持标准的 `wheel` 事件, 所以Koodo 是不是能改为用 `wheel` 事件呢? 

我看到的有 https://github.com/troyeguo/koodo-reader/blob/master/src/utils/serviceUtils/mouseEvent.tsx#L161 这里 和 https://github.com/troyeguo/koodo-reader/blob/master/src/components/popups/popupMenu/component.tsx#L72 这里两处, 你是什么意见?

**Comment by troyeguo** [comment]
感谢您的反馈

**Comment by troyeguo** [comment]
> > 感谢您的反馈
> 
> 代码我可以去改起来做个PR的, 不过逻辑和api上面的抉择需要跟你商量一下, 你稍微抽点时间想一下是不是可以这么处理? 然后我改好提交PR你review过了合并就好.

好的

**Comment by complyue** [comment]
备注: https://github.com/complyue/koodo-reader/tree/no-scroll 这个分支我临时自用, 完全不响应鼠标滚轮.

**Comment by complyue** [comment]
这样看有个相对简单的解决思路, 就是加一个 [禁用鼠标滚轮] 的选项, 实现起来比较容易, 也不用想太多.

原本是想更精细化的控制 [鼠标滚轮灵敏度], 对不同的滚轮类型 - 按行滚动、按页滚动、按像素(包括触屏二指拖拽和Apple Magic Mouse)滚动 - 各自需要个合适的阈值计算公式.

@troyeguo 你觉得按第一个简单实现可以接受么? 

我个人试下来体验是okay的, 禁掉就没有误翻页问题了, 不用滚动手势翻页也没啥缺憾.

**Comment by troyeguo** [comment]
禁掉了正常的滚轮翻页就没法响应，我不太清楚magic mouse的滚轮事件是怎样的，最好在通用设备上测试没有问题再提交

**Comment by complyue** [comment]
我的意思是加一个选项, 默认就和目前一样, 只有通过配置界面opt in去禁掉

**Comment by troyeguo** [comment]
感谢您的建议，会考虑的

**Comment by troyeguo** [comment]
请升级至最新开发版

**Comment by complyue** [comment]
太棒了, 竖滚正常翻页, 横滚不会翻页了. (不过不知道将来有没有人又想要横滚翻页的功能)

感谢 @troyeguo 对UX的精心打磨 (看历史还试过延时处理之类的), 目前的设计我个人用起来是很舒服的, 必须赞!

问题解决, 这个issue我就关了.
