### ISSUE TITLE
章节号错位

### ISSUE THREAD

**Issue by complyue** [troyeguo/koodo-reader#488]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

macOS 12

### Koodo Reader 版本

1.4.4

### 我遇到的问题

目录有 1-9 章,实际还有第10章不在目录中, 界面会显示 0-8 的章节号对应 1-9 章, 读到第10章时界面显示为 -1 章.

除了显示不对, 按章节号导航也大多没反应.

稳定 1.3.9 版章节号更不对, 显示几乎都不更新, 也没法用来导航.

怀疑是源文件的章节编排有问题, 不过作为阅读器, 对类似问题最好能有适当容错性.

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/15646573/174346804-c2ef2f8c-c362-456d-8135-c888b9a203a4.png)

![image](https://user-images.githubusercontent.com/15646573/174346479-05309b97-76c2-4c05-b09e-f7120ae2825c.png)

### 图书文件(可选的)

https://open-mind.net/papers/the-paradigmatic-body-embodied-simulation-intersubjectivity-the-bodily-self-and-language/at_download/paperEPUB

[Embodied Simulation- Intersubjectivity- the Bodily Self- and Language.epub.zip](https://github.com/troyeguo/koodo-reader/files/8929460/Embodied.Simulation-.Intersubjectivity-.the.Bodily.Self-.and.Language.epub.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级至最新开发版
