### ISSUE TITLE
我心目中比较完美的私人书库软件可能是这个样子。

### ISSUE THREAD

**Issue by kumakumasan** [troyeguo/koodo-reader#49]
作为Neatreader的终生用户，突然发现Koodo，觉得眼前一亮，特别是开源挺好的。我想请开发者考虑以下需求：

- [ ] 是否可以考虑能允许将代码和书库部署在私人的VPS上面？
- [ ] 是否可以支持Android端，在Android端设置自己的服务器和书库的地址来进行同步阅读?
- [ ] 是否可以书架可以支持多级？
- [ ] 是否可以给书籍多一些字段，譬如评分或者Tag之类的，更加方便对书籍进行汇总和排序？

提的有点多，如果都能实现，那将是一个非常完美的私人书库软件，哪怕付费都是可以的。因为书是可以看一辈子的。
至于是否支持多种格式，我觉得都是次要的，现在都有很方便的转换工具，直接就可以转成各种格式，而这种私人书库级别的可能正好是书虫最急切需要的。

**Comment by troyeguo** [comment]
您好
感谢您的建议！
1, 目前这个软件是纯前端项目，所有的代码都部署在前端，用不到VPS服务器的，书库的话未来会考虑增加webdav的备份方式，不知道这个能不能满足您的需求
2. 安卓版客户端已经在开发了，但出现了一些技术问题，暂时搁置了，如果能够解决的话这个功能肯定是优先支持的
3. 多级书架会考虑在后续版本更新中支持
4. 评分和标签功能也会考虑在后续版本中支持

**Comment by kumakumasan** [comment]
您好！开发者，谢谢您的贡献和回复。
我想针对我提的第一点再做一下展开说明。

现在的看书软件其实很多，neatreader作为目前口碑最好的阅读器，除了因为他的界面比较清爽之外，他收费主打的其实是多端云同步。这实际上是众多电子书爱好者一个非常硬的需求。
就拿我和我身边的看电子书的爱好者而言，我们在电脑前面，通常会用电脑看，平时行动的时候是会用手机看，而neatreader的云同步解决了我们进度、文摘和笔记无缝流转的问题，虽然可以用你所说的备份恢复方式来处理，但是很显然太过折腾了。
另外，之所以提出做私人书库，是因为neatreade也只能提供10G的空间存放书，一方面空间有限，另一方面还是希望能自己把控自己的资料和隐私。还有，我查了你目前把信息都是存在浏览器的本地缓存里面了，一不小心误操作说不定就全没了。

不过您也解释了目前只是个前端项目，我能充分理解，期待有一天你能腾出手来，祝一切顺利。

**Comment by troyeguo** [comment]
> 您好！开发者，谢谢您的贡献和回复。
> 我想针对我提的第一点再做一下展开说明。
> 
> 现在的看书软件其实很多，neatreader作为目前口碑最好的阅读器，除了因为他的界面比较清爽之外，他收费主打的其实是多端云同步。这实际上是众多电子书爱好者一个非常硬的需求。
> 就拿我和我身边的看电子书的爱好者而言，我们在电脑前面，通常会用电脑看，平时行动的时候是会用手机看，而neatreader的云同步解决了我们进度、文摘和笔记无缝流转的问题，虽然可以用你所说的备份恢复方式来处理，但是很显然太过折腾了。
> 另外，之所以提出做私人书库，是因为neatreade也只能提供10G的空间存放书，一方面空间有限，另一方面还是希望能自己把控自己的资料和隐私。还有，我查了你目前把信息都是存在浏览器的本地缓存里面了，一不小心误操作说不定就全没了。
> 
> 不过您也解释了目前只是个前端项目，我能充分理解，期待有一天你能腾出手来，祝一切顺利。

感谢您的回复，云同步的功能正在开发了，这个功能会和Dropbox，Webdav配合使用，安卓版开发也会尽快推动的，最后感谢您的支持。
