### ISSUE TITLE
EPUB格式漫画快速翻页时阅读页面会卡死

### ISSUE THREAD

**Issue by voidzhakul** [troyeguo/koodo-reader#490]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [x] Yes

### 操作系统或浏览器

Ubuntu

### Koodo Reader 版本

1.4.4 开发版

### 我遇到的问题

EPUB格式漫画快速翻页时阅读页面会卡死，文件越大时触发此BUG的概率越大
(录像中打开的第一本书，为我上传的test.zip

### 截图或录像(可选的)

https://user-images.githubusercontent.com/37470928/174742460-a191a036-af28-4ef8-a611-a2bf5c198801.mp4

### 图书文件(可选的)

[test.zip](https://github.com/troyeguo/koodo-reader/files/8946632/test.zip)

**Comment by troyeguo** [comment]
感谢您的反馈

**Comment by troyeguo** [comment]
请更新至最新开发版
