### ISSUE TITLE
阅读epub格式图书，遇到图片后，无法按键翻页。

### ISSUE THREAD

**Issue by brok1y** [troyeguo/koodo-reader#494]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

我看的是EPUB电子书，当翻到图片时，就无法再用键盘的方向键控制翻页了，必须用鼠标点击翻页按钮才能翻页。

### 图书文件(可选的)

[川原砾 - 刀剑神域 019.zip](https://github.com/troyeguo/koodo-reader/files/8984823/-.019.zip)

**Comment by troyeguo** [comment]
请升级至最新开发版
