### ISSUE TITLE
网页提交PDF时报错

### ISSUE THREAD

**Issue by hnbc66677** [troyeguo/koodo-reader#497]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.5

### 我遇到的问题

从本地提交PDF文件时报错 测试dame不会

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/85747229/177001016-840d0490-fa37-4d0e-9b98-aa5817b67d15.png)

![image](https://user-images.githubusercontent.com/85747229/177001028-0dc52741-a3c2-4cac-b1fb-22f532bdf189.png)

### 图书文件(可选的)

[初中数学7.5.zip](https://github.com/troyeguo/koodo-reader/files/9033020/7.5.zip)

**Comment by troyeguo** [comment]
我这边测试一切正常
