### ISSUE TITLE
新建书架相关bug

### ISSUE THREAD

**Issue by lb428** [troyeguo/koodo-reader#498]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

开发者您好，我在使用过程中"书架"相关功能里，
1）有些情况下新建的书架右边不会显示删除按钮，具体而言，我将它命名为1，显示在所有书架最顶上（下面有截图）
2）点击新建书架会直接白屏（第2张截图），然后就卡住
3）点击全部图书也会直接白屏并卡住

### 截图或录像(可选的)

![1](https://user-images.githubusercontent.com/70442494/177004047-6000b2ce-06c6-43bd-b447-f6c1ef0603a1.png)
![2](https://user-images.githubusercontent.com/70442494/177004048-37654e4c-87e5-4d61-a862-041d84341907.png)

**Comment by troyeguo** [comment]
最新开发版已经限制使用纯数字作为书架名
