### ISSUE TITLE
左侧的目录和下方的进度条失灵

### ISSUE THREAD

**Issue by yg200** [troyeguo/koodo-reader#499]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.5

### 我遇到的问题

左侧目录点击后不能跳转到对应的位置，下方的进度条拖动也没有任何反应，情况严重时甚至会加载不出文字卡死。

### 截图或录像(可选的)

https://user-images.githubusercontent.com/94277637/177025748-0e5aecf1-5067-417f-bc83-a20919b860de.mp4

### 图书文件(可选的)

[新约 某魔法的禁书目录 11X.zip](https://github.com/troyeguo/koodo-reader/files/9034104/11X.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
不好意思，这个问题可能和图书本身有关，请尝试使用calibre转换之后导入
