### ISSUE TITLE
不能识别章节中的“零”字，如果章节中存在比如一千零一章，不能生成章节

### ISSUE THREAD

**Issue by Yoezzz** [troyeguo/koodo-reader#502]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.4.5

### Bug Detail

不能识别章节中的“零”字，如果章节中存在比如一千零一章，不能生成章节

**Comment by Yoezzz** [comment]
![image](https://user-images.githubusercontent.com/38277859/178090365-061fd16e-2a2b-4a74-a2ad-1e6a48377779.png)

**Comment by troyeguo** [comment]
感谢您的反馈

**Comment by troyeguo** [comment]
请更新至最新开发版
