### ISSUE TITLE
优化触摸屏体验

### ISSUE THREAD

**Issue by Doddddd** [troyeguo/koodo-reader#506]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

禁用滑动翻页选项（防止误触），使用点击翻页

### 细节描述

把屏幕分成9个区域，每个区域可以单独设置为“下一页”、“上一页”、“无操作”、“目录”等功能

**Comment by troyeguo** [comment]
感谢您的建议考虑增加这个功能的
