### ISSUE TITLE
任意图书进入全屏后，都会变成第一本阅读过的书

### ISSUE THREAD

**Issue by Doddddd** [troyeguo/koodo-reader#507]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.5

### 我遇到的问题

任意图书进入全屏后，都会变成第一本阅读过的书

### 截图或录像(可选的)

https://user-images.githubusercontent.com/88972478/178150721-869bf443-ab97-45cd-9d98-139bb57874f7.mp4

**Comment by troyeguo** [comment]
不好意思，我这边没办法复现，您可以提供一下完整流程的录像吗？

**Comment by Doddddd** [comment]
> 不好意思，我这边没办法复现，您可以提供一下完整流程的录像吗？

暂时无法复现（已经出现两次），如果再次出现我会重新打开这个问题上传录屏
