### ISSUE TITLE
简繁转换与注释链接的相关功能异常

### ISSUE THREAD

**Issue by gitransistor** [troyeguo/koodo-reader#510]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [x] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9  & 1.4.5

### 我遇到的问题

1.3.9版本在使用简繁转换功能后会出现注释的链接失效的情况，1.4.5开发版简繁转换时仅对没有注释链接的段落进行转换，其余都不转换

### 截图或录像(可选的)

1.3.9版本的截图可以看到链接变为纯数字了：

![汗青堂中国史：还原历史的真相（一套涉及中国不同时期的历史著作，以突破传统的研究模式，全面而系统地还原历史真相！套装共5册） (汗青堂系列) - Koodo Reader 2022_7_15 1_00_15 - ](https://user-images.githubusercontent.com/109301858/179042130-e95438d2-0dc8-4045-879e-9380a70e0da0.png)

1.4.5：
![汗青堂中国史：还原历史的真相（一套涉及中国不同时期的历史著作，以突破传统的研究模式，全面而系统地还原历史真相！套装共5册） (汗青堂系列) - Koodo Reader 2022_7_15 0_53_34 - ](https://user-images.githubusercontent.com/109301858/179042210-6722db8f-cbef-45af-807b-c7e77a1ffc75.png)

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by gitransistor** [comment]
链接：https://pan.baidu.com/s/1P3OZTeGzNTjbQrkcEGC6Ig?pwd=qwav 
提取码：qwav

**Comment by troyeguo** [comment]
> 链接：https://pan.baidu.com/s/1P3OZTeGzNTjbQrkcEGC6Ig?pwd=qwav 提取码：qwav

感谢您的反馈，会在后续版本修复的

**Comment by gitransistor** [comment]
好的，辛苦了

**Comment by troyeguo** [comment]
请更新至最新开发版
