### ISSUE TITLE
支持CHM格式文件的阅读

### ISSUE THREAD

**Issue by yundan125** [troyeguo/koodo-reader#520]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

支持CHM格式文件的阅读

### 细节描述

支持CHM格式文件的阅读

**Comment by troyeguo** [comment]
请查看开发计划，暂时没有支持新格式的计划
