### ISSUE TITLE
Koode Reader 1.4.5版本加载并打开epub时出现卡死问题

### ISSUE THREAD

**Issue by jinguang-dong** [troyeguo/koodo-reader#521]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Ubuntu

### Koodo Reader 版本

1.4.5

### 我遇到的问题

1、加载epub文件;
2、打开翻到后面几页后，出现卡死的问题，一直无法恢复

### 截图或录像(可选的)

![Screenshot at 2022-07-25 15-41-12](https://user-images.githubusercontent.com/20970392/180724336-d7a468d1-985d-4a99-baaf-fdbe427cadd3.png)

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by jinguang-dong** [comment]
[cplus-program-part.zip](https://github.com/troyeguo/koodo-reader/files/9196143/cplus-program-part.zip)
[Uploading cplus-program-part.z01.zip…]()

**Comment by troyeguo** [comment]
请更新至最新开发版

**Comment by jinguang-dong** [comment]
好的 谢谢
目前已已经切换到 okluar epub的阅读器，体验还可以，等后面有空了我再切换至 koode 最新版本体验一下

另外想了解一下，与这个issue 相关的pr是哪一个呢？看了git log 没有能直接找到关联项，谢谢
