### ISSUE TITLE
Add Persian language to translate

### ISSUE THREAD

**Issue by Ja7ad** [troyeguo/koodo-reader#523]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

please add persian language to translate feature.

**Comment by troyeguo** [comment]
Thanks for the suggestion, we will add this feature in future update

**Comment by troyeguo** [comment]
Please update to 1.4.6
