### ISSUE TITLE
Finished translation into Polish - please add it

### ISSUE THREAD

**Issue by marciniuk** [troyeguo/koodo-reader#527]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

A moment ago I finished the translation into Polish

### Details

The Polish language has been translated 100%, please add.

Btw, great project!

**Comment by troyeguo** [comment]
Thanks for the heads up, we just rolled out a new version.

**Comment by marciniuk** [comment]
1. I introduced minor corrections with the variety, Polish is hard in this respect and working on a "living organism" is the only way to be without errors ;P

2. There are things that haven't been translated, such as "translation" in the settings, or a warning (photo below)
![Zrzut ekranu 2022-07-31 123900](https://user-images.githubusercontent.com/45925550/182022899-938d3808-ffaf-4687-9f55-c2d2ff74aa8f.png)

**Comment by troyeguo** [comment]
Thanks for the feedback. We’ve noticed it.
