### ISSUE TITLE
阅读的时候我已经选了滚动模式，为什么不能用pagedown按键一路阅读下去，每章还要切换？

### ISSUE THREAD

**Issue by quicklwl** [troyeguo/koodo-reader#528]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

windows，阅读书籍
阅读的时候我已经选了滚动模式，为什么不能用pagedown按键一路阅读下去，每章还要切换？

### 细节描述

如题

**Comment by troyeguo** [comment]
会在后续版本增加这个功能的

**Comment by quicklwl** [comment]
看到了，在1.4.5里实现了。谢谢
