### ISSUE TITLE
最新开发者版本PDF打不开

### ISSUE THREAD

**Issue by martjay** [troyeguo/koodo-reader#530]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.6

### 我遇到的问题

最新开发者版本PDF打不开，一片空白，我点打印显示PDF未完成载入，我感觉这个阅读器有问题

系统：windows 11 pro X64

下载的软件版本也是X64绿色版

**Comment by martjay** [comment]
1.3.9官网最新版的翻译又有问题，希望能全文翻译就好了，希望支持自定义api翻译接口，这样是不是就不容易出错

**Comment by troyeguo** [comment]
请更新至1.4.7
