### ISSUE TITLE
1.4.1版本打开书后无法加载内容，上面报错 unknow chapter

### ISSUE THREAD

**Issue by riverwalker01** [troyeguo/koodo-reader#536]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.1

### 我遇到的问题

打开书后一片空白
![Uploading image.png…]()

### 截图或录像(可选的)

[](url)

### 图书文件(可选的)

[Uploading 寂寞的游戏.zip…]()

**Comment by troyeguo** [comment]
你的图书上传失败了

**Comment by riverwalker01** [comment]
[寂寞的游戏.zip](https://github.com/troyeguo/koodo-reader/files/9276656/default.zip)
这次呢？应该上传成功了吧，这本书我用别的软件可以打开的，而且能显示目录

**Comment by troyeguo** [comment]
这次成功了，感谢您的反馈
