### ISSUE TITLE
Epub格式，单页模式下出现2次第1页

### ISSUE THREAD

**Issue by subtle99** [troyeguo/koodo-reader#537]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.7

### 我遇到的问题

Epub格式，单页模式下出现2次第1页（底部菜单页码也不正确）

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件
