### ISSUE TITLE
纯图片的mobi格式打开只显示封皮和目录

### ISSUE THREAD

**Issue by daxiong007** [troyeguo/koodo-reader#54]
纯图片的mobi格式打开只显示封皮(不是文件封皮)和目录两个字，还有能否支持漫画阅读

**Comment by troyeguo** [comment]
您好！
感谢您的反馈，目前mobi，azw3格式的图书都只支持文字部分的导入，图片的导入还在研究中，也会尽快支持的。

**Comment by daxiong007** [comment]
OK，静待大佬研究出来

**Comment by troyeguo** [comment]
koodo reader现在已经支持导入mobi和azw3文件中的图片了
