### ISSUE TITLE
调整字体大小时，输入框和滑动条对应的数字不同步

### ISSUE THREAD

**Issue by Yoakez** [troyeguo/koodo-reader#546]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.7开发版

### 我遇到的问题

例如，当前字体大小滑动条对应的数字是30，输入框的数字也是30，然后我手动输入15，字体大小就变成15了，但滑动条的位置没有变化，左右轻拉滑动条会将输入框旁边的数字变成29或31，字体大小也会随之变大，但输入框内的数字仍是15。
（下面的页边距、字间距等选项我没有调整过，但可能也存在相同的问题。）

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版修复这个问题的
