### ISSUE TITLE
可以自定义已存在的数据目录

### ISSUE THREAD

**Issue by MilkTeaNo7** [troyeguo/koodo-reader#547]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [ ] Yes

### 简单介绍

我不知道上传的文件放在哪儿了

### 细节描述

当我本地有几十个G的图书时，莫非也要重新导入一遍？，如果能和大多数docker一样自定义数据挂载目录就好了

**Comment by troyeguo** [comment]
请查看帮助文档，docker版的数据存在浏览器缓存里，不建议长期保存数据

**Comment by MilkTeaNo7** [comment]
好的感谢
