### ISSUE TITLE
部分默认右对齐的文字在软件中变成了左对齐

### ISSUE THREAD

**Issue by Yoakez** [troyeguo/koodo-reader#548]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.7开发版

### 我遇到的问题

书中有部分文字默认是右对齐的，但在软件中变成了左对齐。将对齐方式设置为两端对齐也无法使其右对齐，若设置为右对齐则所有文字都变成右对齐了。
（图1是我在Koodo Reader中的截图，图2是在另一阅读器中的截图）

### 截图或录像(可选的)

![1](https://user-images.githubusercontent.com/52622615/185168077-4425bdf1-b6c3-41e1-8a09-4f04c24218e2.png)
![2](https://user-images.githubusercontent.com/52622615/185168149-9b583476-5b73-4096-a2f1-685292d59185.png)

**Comment by troyeguo** [comment]
麻烦提供一下电子书文件

**Comment by Yoakez** [comment]
[C Primer Plus（第6版）中文版（异步图书）.zip](https://github.com/troyeguo/koodo-reader/files/9368312/C.Primer.Plus.6.zip)

**Comment by troyeguo** [comment]
请升级至最新开发版，现在增加了默认选项
