### ISSUE TITLE
滚动模式文字贴边显示

### ISSUE THREAD

**Issue by gitbula** [troyeguo/koodo-reader#550]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.7-x64

### 我遇到的问题

我的电脑从1.4.2版本开始，滚动模式下小窗口大窗口阅览，左侧的字会贴边显示，右边的字会显示不齐整。我试过在别人的电脑打开，问题就变成了无论哪种阅读模式，都是双页显示。我怀疑不同的电脑出现的问题是不一致的。
看轻小说，封面的图片可以看，但是文中的图片就无法显示。

### 截图或录像(可选的)

![屏幕截图 2022-08-21 110252](https://user-images.githubusercontent.com/93466365/185774569-737f26f6-4056-44bf-b95d-e04bf51be5c7.jpg)
![屏幕截图 2022-08-21 110351](https://user-images.githubusercontent.com/93466365/185774570-0a98af6f-ecd2-43e6-9af5-3f369d2ef2b9.jpg)
![mmexport1661051209669](https://user-images.githubusercontent.com/93466365/185774580-4cc0f454-698b-4d7b-9d1f-b1881dfccd0c.png)
![mmexport1661051219172](https://user-images.githubusercontent.com/93466365/185774582-144ed1ca-4608-4128-b28a-bd94a6244fa5.png)
![mmexport1661051222774](https://user-images.githubusercontent.com/93466365/185774585-74b05799-4641-4636-b68d-e88eccca478f.png)
![mmexport1661051235259](https://user-images.githubusercontent.com/93466365/185774588-921e51c3-e69d-4d6a-a681-9c8bb269e26e.png)

**Comment by troyeguo** [comment]
这个和电脑分辨率和缩放比有关，如果是最后这几张图的显示效果，建议切换为单页模式或者滚动模式。第一张和第二张图的问题会在后续版本中修复的。第三张图的问题理论上再次打开，或者调整窗口大小之后就会修复。

**Comment by gitbula** [comment]
那轻小说的图片显示可以改进一下吗？
