### ISSUE TITLE
it is not possible to start the project according to the instructions using the "Develop" item

### ISSUE THREAD

**Issue by KurKuza** [troyeguo/koodo-reader#556]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 11

### App Version

1.3.9

### Bug Detail

belgorod@MacBook-Pro-Danil koodo-reader % yarn
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "react-hot-toast > goober@2.0.41" has unmet peer dependency "csstype@^2.6.2".
warning " > hard-source-webpack-plugin@0.13.1" has unmet peer dependency "webpack@*".
warning " > html-react-parser@0.13.0" has incorrect peer dependency "react@^0.14 || ^15 || ^16".
warning " > rc-color-picker@1.2.6" has incorrect peer dependency "react@16.x".
warning " > rc-color-picker@1.2.6" has incorrect peer dependency "react-dom@16.x".
warning " > react-lottie@1.2.3" has incorrect peer dependency "react@^0.14.7 || ^15.0.0 || ^16.0.0".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[5/5] 🔨  Building fresh packages...
[-/9] ⠂ waiting...
[2/9] ⠂ node-sass
[-/9] ⠄ waiting...
[-/9] ⠄ waiting...
error /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/belgorod/Desktop/koodo-reader/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/belgorod/Desktop/koodo-reader/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.16.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 16.16.0
gyp verb command install [ '16.16.0' ]
gyp verb install input version string "16.16.0"
gyp verb install installing version: 16.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.16.0
gyp verb build dir attempting to create "build" dir: /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass/build/config.gypi
(node:32333) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp verb config.gypi checking for gypi file: /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/belgorod/Desktop/koodo-reader/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/belgorod/Desktop/koodo-reader/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/belgorod/Desktop/koodo-reader/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/belgorod/Desktop/koodo-reader/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/belgorod/.node-gyp/16.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/belgorod/.node-gyp/16.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/belgorod/Desktop/koodo-reader/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/belgorod/.node-gyp/16.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/belgorod/Desktop/koodo-reader/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/belgorod/.node-gyp/16.16.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' -I/Users/belgorod/.node-gyp/16.16.0/include/node -I/Users/belgorod/.node-gyp/16.16.0/src -I/Users/belgorod/.node-gyp/16.16.0/deps/openssl/config -I/Users/belgorod/.node-gyp/16.16.0/deps/openssl/openssl/include -I/Users/belgorod/.node-gyp/16.16.0/deps/uv/include -I/Users/belgorod/.node-gyp/16.16.0/deps/zlib -I/Users/belgorod/.node-gyp/16.16.0/deps/v8/include -I../src/libsass/include  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:2:
../src/libsass/src/ast.hpp:1614:25: warning: loop variable 'numerator' creates a copy from type 'const std::string' [-Wrange-loop-construct]
        for (const auto numerator : numerators)
                        ^
../src/libsass/src/ast.hpp:1614:14: note: use reference type 'const std::string &' to prevent copying
        for (const auto numerator : numerators)
             ^~~~~~~~~~~~~~~~~~~~~~
                        &
../src/libsass/src/ast.hpp:1616:25: warning: loop variable 'denominator' creates a copy from type 'const std::string' [-Wrange-loop-construct]
        for (const auto denominator : denominators)
                        ^
../src/libsass/src/ast.hpp:1616:14: note: use reference type 'const std::string &' to prevent copying
        for (const auto denominator : denominators)
             ^~~~~~~~~~~~~~~~~~~~~~~~
                        &
2 warnings generated.

**Comment by troyeguo** [comment]
Please run this project under Node 14 or below
