### ISSUE TITLE
Scroll bar covers letters at right end of each line

### ISSUE THREAD

**Issue by Mister-Teatime** [troyeguo/koodo-reader#557]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Other Linux distribution

### App Version

1.4.7

### Bug Detail

When I switch to continuous scrolling mode, Koodo shows a vertical scroll bar covers the right-most part of the text.
This is independent the width of the reader window. I can have a lot of space on the right side of the text, but the scroll bar does stick to the right edge of the window, always stays on top of the text.

Switching to left-aligned layout (rather than justified or right-aligned) means that some lines becomes short enough to not be cut off, but I have not found any option that either makes the scroll bar transparent or moves it just a few pixels further right, to put it next to the text.

As far as I can tell, all it would take to resolve this is to draw the scroll bar 8 pixels further to the right.

Operating system: Manjaro
Desktop Environment: KDE Plasma 5.24.6

### Screenshots (Optional)

![Screenshot_20220828_233900](https://user-images.githubusercontent.com/58110145/187095586-9cb570d2-ba47-4ce6-8d14-f373d6a920d1.png)

**Comment by troyeguo** [comment]
Thanks for the feedback, we will fix it in the next update

**Comment by NoahMLoomis** [comment]
@troyeguo I can take a look at this if you want?

**Comment by troyeguo** [comment]
Please update to 1.4.8
