### ISSUE TITLE
听书不会自动翻页

### ISSUE THREAD

**Issue by iamyx123** [troyeguo/koodo-reader#558]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.7

### 我遇到的问题

使用最新版听书功能时，只会重复阅读当前页的内容，不会自动翻页。

**Comment by troyeguo** [comment]
不好意思我这边没办法复现，您可以提供一下录像

**Comment by iamyx123** [comment]
https://user-images.githubusercontent.com/88130457/187404063-6b04c417-1594-424c-a9bb-719bbd31206c.mp4

自动翻页之后还是朗读之前页的内容

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的。暂时可以先关闭翻页动画

**Comment by troyeguo** [comment]
请升级至最新开发版
