### ISSUE TITLE
翻译报错了

### ISSUE THREAD

**Issue by wanyne-yyds** [troyeguo/koodo-reader#559]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

我使用划词翻译时报了 ”出错了“；我怀疑跟公司限网有关系，请问能设置个功能可以设置代理服务器吗？

### 细节描述

如上

**Comment by troyeguo** [comment]
旧版本的翻译功能已经用不了，请升级到1.4.7

**Comment by wanyne-yyds** [comment]
尝试了，有效，谢谢！

**Comment by troyeguo** [comment]
由于Google 翻译退出中国市场，现在国内能用的只剩下Bing翻译引擎了

**Comment by yuanyuepeng** [comment]
我下载了1.4.7版本，为什么翻译还是报错，用的也是Bing翻译

**Comment by third0light** [comment]
用Bing翻译，文字稍微多一点（一段文字）就会报错。
