### ISSUE TITLE
使用外接触摸屏幕时选中文字无法弹出菜单

### ISSUE THREAD

**Issue by iamyx123** [troyeguo/koodo-reader#561]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.7

### 我遇到的问题

使用外接触摸屏幕时选中文字无法弹出菜单

### 截图或录像(可选的)

https://user-images.githubusercontent.com/88130457/187883859-512151f6-a209-4425-ae83-8b31c1bb2838.mp4

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级至最新开发版
