### ISSUE TITLE
epub公式渲染错误

### ISSUE THREAD

**Issue by ervinzhao** [troyeguo/koodo-reader#563]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 10 and below

### App Version

1.4.7

### Bug Detail

单页/双页模式下epub中的公式渲染错误。出现问题的书是《Data Science from Scratch First Principles with Python, Second Edition (Joel Grus) (z-lib.org) 》，在第6章第2页"product of the probabilities that each one happens:" 这句话后面。现象是公式貌似被渲染了成了一个超级大的尺寸，然后每页只能显示一小部分。这一张的页数计算完后有6000多页。顺序模式是正常的。

截图第一张是顺序模式正常显示；第二张是单页模式公式前的部分，第三张氏单页模式公式显示有问题的第一张（完全空白，后面很多张都是整个公式的一小部分）。

### Screenshots (Optional)

![1361662113692_ pic](https://user-images.githubusercontent.com/1237403/188118105-0f160dde-dd05-454f-9b80-7c0d26244631.jpg)
![1371662113752_ pic](https://user-images.githubusercontent.com/1237403/188118271-abf167eb-e952-4667-ac78-20c7b67e9ed7.jpg)
![Uploading 1381662113826_.pic.jpg…]()

### Files (Optional)

[data.zip](https://github.com/troyeguo/koodo-reader/files/9477036/data.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
不好意思这是epub.js的问题，我这边暂时没法修复

**Comment by rfhits** [comment]
> 不好意思这是epub.js的问题，我这边暂时没法修复

您好，我正在阅读的 epub 文件也无法渲染公式，但是在 Neat Reader 的网页版上却可以渲染，我注意到 Neat Reader 使用了 `MathJax.js`，而且在 `epub.js` 仓库 的[样例](https://github.com/futurepress/epub.js/blob/master/examples/mathml.html)中，也使用了 MathJax，不知道您是否有试过呢？

谢谢！

**Comment by troyeguo** [comment]
请更新至最新开发版
