### ISSUE TITLE
建议添加自定义页边距、页眉、页脚功能

### ISSUE THREAD

**Issue by johnzjzlast** [troyeguo/koodo-reader#57]
全屏阅读的时候页边距觉得有点宽，如果可以自定义就很好了。
另外，页眉、页脚的显示/不显示可以分开设置，因为页脚的页数不太有用，但页眉（当前章节、阅读进度）想保留。

**Comment by troyeguo** [comment]
您好，感谢您的反馈，会在后续版本中增加这些功能的
