### ISSUE TITLE
每页标题

### ISSUE THREAD

**Issue by XYY1411** [troyeguo/koodo-reader#571]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.8

### 我遇到的问题

epub
如图所示位置似乎显示的是改 xhtml 文件的 `<h1>` 标签内容，而不是 `<title>` 的内容。

### 截图或录像(可选的)

![QQ截图20220908230630](https://user-images.githubusercontent.com/63308158/189158205-8e2d4f56-2a8d-4425-89bc-991185595f55.png)

**Comment by troyeguo** [comment]
识别不出标题就会显示这个

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by XYY1411** [comment]
> 
[epub.zip](https://github.com/troyeguo/koodo-reader/files/9531804/epub.zip)

**Comment by troyeguo** [comment]
我这边测试，大部分章节都可以正常显示，少部分章节可能本身就没有标题

**Comment by XYY1411** [comment]
![QQ截图20220910075303](https://user-images.githubusercontent.com/63308158/189460013-b33ed570-e631-4c5b-8b80-2b2bd4b57e83.png)
![QQ截图20220910075312](https://user-images.githubusercontent.com/63308158/189460014-dd562ffa-34ba-4e1d-bd64-15ec486b79b4.png)
这个epub是我自己做的，我每一章都加了 `<title>` 包括封面
