### ISSUE TITLE
统计功能

### ISSUE THREAD

**Issue by Cx330stars** [troyeguo/koodo-reader#573]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.8

### 我遇到的问题

打开.md的文件阅读只显示阅读本章所需的阅读时间，不显示已经阅读的时间，在书架不显示已经阅读的百分比，看完了也不显示

### 截图或录像(可选的)

![Koodo_Reader_SLAWQoDgiu](https://user-images.githubusercontent.com/108574832/189250986-9c26dab5-66d6-4fb3-adb1-e4b219bb07f2.png)
![Koodo_Reader_dHFK6VAiNz](https://user-images.githubusercontent.com/108574832/189251036-246d2773-fa10-422c-8000-d25446d5587f.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级最新开发版
