### ISSUE TITLE
1.3.9阅读背景无法更改

### ISSUE THREAD

**Issue by DearY-Ye** [troyeguo/koodo-reader#574]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.3.9

### 我遇到的问题

阅读时背景突然变成白色，还无法更改。

### 截图或录像(可选的)

[2022-09-10 11-08-18.zip](https://github.com/troyeguo/koodo-reader/files/9539475/2022-09-10.11-08-18.zip)

### 图书文件(可选的)

[《凡人修仙传》作者：忘语.zip](https://github.com/troyeguo/koodo-reader/files/9539476/default.zip)

**Comment by troyeguo** [comment]
您可以升级到1.4.8，我这边没办法复现，或者卸载重装看看

**Comment by DearY-Ye** [comment]
> 您可以升级到1.4.8，我这边没办法复现，或者卸载重装看看

好的，解决
