### ISSUE TITLE
备份无法恢复

### ISSUE THREAD

**Issue by FretroH** [troyeguo/koodo-reader#575]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.8

### 我遇到的问题

备份无法恢复，一直卡在请稍后界面

### 截图或录像(可选的)

![批注 2022-09-10 152627](https://user-images.githubusercontent.com/53276353/189473733-0db53fbb-c2b5-47cd-b94d-d7f7add5d895.png)

**Comment by FretroH** [comment]
> 麻烦您提供一下备份文件

文件太大了怎么办，百度云可以吗
链接：https://pan.baidu.com/s/1BV0dPt04iOnhjEvA31bJng 
提取码：of44

**Comment by FretroH** [comment]
> 麻烦您提供一下备份文件

文件太大了怎么办，百度云可以吗

链接：https://pan.baidu.com/s/1BV0dPt04iOnhjEvA31bJng 
提取码：of44

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
您可以再分享一下吗？文件过期了，之前没时间下

**Comment by FretroH** [comment]
链接：https://pan.baidu.com/s/10YZpSfpbmwICNUeDjnuLaw 
提取码：8vv7

**Comment by troyeguo** [comment]
好的，谢谢

**Comment by troyeguo** [comment]
请升级最新开发版
