### ISSUE TITLE
epub格式电子书内图片格式PNG无法显示

### ISSUE THREAD

**Issue by Liuzhe0905** [troyeguo/koodo-reader#577]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

epub格式电子书内当图片格式为PNG页面无法显示图片

### 细节描述

增加支持epub格式电子书图片格式为PNG的显示

**Comment by Ziffer-yan** [comment]
我遇到了同样的情况，发现图片也是无法正常显示的。
这是在Koodo中显示的epub
![image](https://user-images.githubusercontent.com/33079825/194853430-f56ca37b-89f4-44e9-b27c-51c3a057b1bc.png)
这是在其他阅读器中显示的epub
![image](https://user-images.githubusercontent.com/33079825/194853597-9b375720-4db4-48cb-9af9-c9580f440a3b.png)
希望能check下这部分的代码，或者添加这部分的功能。

**Comment by troyeguo** [comment]
请查看帮助文档
