### ISSUE TITLE
摘录有些bug

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#58]
摘录有时候删不掉（点击删除没反应）。有时候划字了却不会显示摘录选项。
![image](https://user-images.githubusercontent.com/57058325/105804969-fc483800-5fdb-11eb-813d-ce4ecb797a9b.png)

**Comment by troyeguo** [comment]
您好，感谢您的反馈，删不掉的问题确实存在，后续会解决的。划字不显示这个问题，我这里没办法重现，您可以说一下您的阅读模式还有页面缩放比例吗？

**Comment by johnzjzlast** [comment]
划字不显示菜单这个很偶发，应该无碍
