### ISSUE TITLE
增加对mhtml的支持？

### ISSUE THREAD

**Issue by tjpgt** [troyeguo/koodo-reader#582]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

不知道能否增加对mhtml格式文件的支持

### 细节描述

就是浏览器保存网页时选择单个文件保存下来的文件格式
![image](https://user-images.githubusercontent.com/29495241/191445739-239793f9-442f-4bbc-b778-8ebe0730c672.png)

**Comment by troyeguo** [comment]
感谢您的建议，会考虑的
