### ISSUE TITLE
「记笔记」功能无法正常使用

### ISSUE THREAD

**Issue by chenluna** [troyeguo/koodo-reader#584]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.3.9

### 我遇到的问题

刚开始使用您的软件，在做了三个笔记后，三个笔记共享一个内容。

最开始是前两个笔记内容为 空白 ，遂做了第三个笔记。关闭图书并再次打开后，三个笔记开始**共用一个笔记内容**

附一个个人无法正常使用的功能提问：
关于「记笔记」功能里的「+」后的「标签」(个人如此理解该功能)功能，**我无法删除已添加标签**，并且每一个新的笔记，都伴随着原先笔记的已有标签。

有幸能遇见您们所开发的软件，希望我们能共同进步，祝愿您们的软件开发得越来越好

### 截图或录像(可选的)

![1](https://user-images.githubusercontent.com/104905164/191656374-f58725c7-974d-429c-a35e-ae6c5b84df77.png)
![2](https://user-images.githubusercontent.com/104905164/191656379-8aa160dd-4706-403f-9e8e-a5a788bd93d7.png)

**Comment by troyeguo** [comment]
请升级最新开发版

**Comment by chenluna** [comment]
关于「标签」的删除功能，已在软件的笔记界面找到删除功能

**Comment by troyeguo** [comment]
请升级最新开发版

**Comment by neochen6** [comment]
> 关于「标签」的删除功能，已在软件的笔记界面找到删除功能

在最新的稳定版1.5.1，还存在上述问题；所以是稳定版还没修复？还是在某个界面存在“删除”操作？

**Comment by neochen6** [comment]
升级到开发版1.5.3后，在主页面-我的笔记-全部标签（点击）找到了隐藏的删除，不确定1.5.1是否拥有；这个删除与添加离得确实太远
