### ISSUE TITLE
s3同步方式

### ISSUE THREAD

**Issue by ghost** [troyeguo/koodo-reader#585]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

1. 能支持s3同步吗，那些网盘国内不怎么用，我也不想保存在百度网盘，求求了。

### 细节描述

综上
1. 能支持s3同步吗，那些网盘国内不怎么用，我也不想保存在百度网盘，求求了。

**Comment by troyeguo** [comment]
同步支持Dropbox，Onedrive, Google Drive，备份支持webdav，Dropbox
