### ISSUE TITLE
关于「记笔记」功能的bug在最新的开发版存有bug

### ISSUE THREAD

**Issue by chenluna** [troyeguo/koodo-reader#587]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.8

### 我遇到的问题

包括但不限于：
1.笔记错误显示为空白；
2.笔记高亮失败；
3.笔记记录后错误显示为其他笔记的内容；

以上bug顺序基于下方视频录制过程中发生的顺序

### 截图或录像(可选的)

Uploading 2022-09-23 13-00-42_20220923_13041020.mp4…

**Comment by troyeguo** [comment]
您的录像上传失败了

**Comment by chenluna** [comment]
https://user-images.githubusercontent.com/104905164/191902559-87123032-19be-4c25-8476-ec327bb54f9c.mp4

**Comment by chenluna** [comment]
> 您的录像上传失败了

现在我重新上传了

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级最新开发版
