### ISSUE TITLE
win11无法打开pdf,确认pdf没有问题

### ISSUE THREAD

**Issue by tomuGo** [troyeguo/koodo-reader#590]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.4.8开发板

### Bug Detail

无法打开pdf,确认pdf没有问题。epub没有问题

### Screenshots (Optional)

![image](https://user-images.githubusercontent.com/24789356/193231893-cfb491d4-551d-42c1-9627-8b297a836c80.png)

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by troyeguo** [comment]
请升级最新开发版
