### ISSUE TITLE
导入图书出错

### ISSUE THREAD

**Issue by Crzq** [troyeguo/koodo-reader#596]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.8

### 我遇到的问题

此时我的书架上有四本书。导入图书直接打开了，且没有导入成功。

**Comment by troyeguo** [comment]
麻烦您提供一下导入失败的电子书

**Comment by Crzq** [comment]
是这样的：我如果清空我的书架，再导入，就可以导入进来；貌似书架书籍超过一定数量，就会导入失败。
我之前也遇到过这种情况，不过不是四本，是书架上有十几本书籍后，导入失败了，我清空了书籍，方才导入成功。

**Comment by Crzq** [comment]
补充一下，在以上的情况下，此时此刻，再次执行导入的操作，会导入失败，取而代之的是，会直接打开书籍。

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请升级最新开发版
