### ISSUE TITLE
dropbox无法备份

### ISSUE THREAD

**Issue by GriffinSGJ** [troyeguo/koodo-reader#598]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Chrome 及其他 Chromium 浏览器(包括 Edge 和所有国产浏览器)

### Koodo Reader 版本

Version 1.3.9 (1.3.9.780)

### 我遇到的问题

dropbox无法备份，每次都提示网络问题，但我已经检查过了，应该没有问题，dropbox里面其他的软件的备份是没有问题，就是这个软件的备份一直提示网路问题。

### 截图或录像(可选的)

![Screenshot 2022-10-09 at 18 09 30](https://user-images.githubusercontent.com/93034256/194751001-427aa3bf-adcf-4016-b037-797666653ca0.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
我换了个网络环境，上传了一个200多兆的文件又成功了。这应该是网络的问题。
