### ISSUE TITLE
笔记、收藏高亮显示、跳转、分组。

### ISSUE THREAD

**Issue by fcki1984** [troyeguo/koodo-reader#6]
- 有计划为笔记、收藏添加高亮显示(可选择不同颜色)、添加跳转到原书位置、添加自定义分组吗？
[高亮显示参考](https://github.com/bubble-Q/QiuReader-react)
现在安卓epub阅读器一般都有`标注高亮和显示`功能，可以直观地看到标注，避免重读的时候重复标注和体会不同时期的思想变化。

**Comment by troyeguo** [comment]
感谢您的建议！
这个建议很好，后续会考虑添加的，感谢您的支持。

**Comment by troyeguo** [comment]
您好！
最新的Koodo Reader已经支持了高亮颜色选择和跳转原书位置功能，分组功能会考虑在后续版本中支持，欢迎下载使用，您可以前往 https://koodo.960960.xyz/log 了解新版本的更多功能

**Comment by fcki1984** [comment]
很好用，谢谢。
