### ISSUE TITLE
屏幕四个边的菜单不灵敏

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#60]
屏幕四个边的菜单不灵敏，有时候鼠标移动到四个边上了但不会出相应菜单。

**Comment by troyeguo** [comment]
这主要是因为我有意把菜单触发的面积减小到窗口边缘正中间大概200px宽度了，之前菜单误触比较严重，只需把鼠标移动到长或宽的正中间的位置就好了。

**Comment by Z-fly** [comment]
能否加个保持菜单一直显示不隐藏的选项？

**Comment by troyeguo** [comment]
@Z-fly 感谢您的建议，会考虑在后续版本增加这个功能
