### ISSUE TITLE
打开epub格式书籍后再打开pdf书籍就是空白

### ISSUE THREAD

**Issue by zznova** [troyeguo/koodo-reader#601]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.48 开发版

### 我遇到的问题

打开epub格式书籍后再打开pdf书籍就是空白，必须重启软件直接打开pdf才行。环境：win10 64位专业版已打最新补丁。

**Comment by zznova** [comment]
1.39稳定版也有此问题

**Comment by troyeguo** [comment]
请升级最新开发版
