### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by AmadeusGraves** [troyeguo/koodo-reader#603]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

We need koodo available in docker hub.

### Details

We need koodo available in docker hub to be able to install it without import the code from github. Also if it published on docker hub we can update koodo with watchtower.

**Comment by troyeguo** [comment]
We don't maintain any third-party download sources except for sourceforge. You can still find lots of docker images published by our users on docker hub. Although we don't guarantee for their integrity, and you should use at your own risk.

https://hub.docker.com/search?q=koodo&sort=updated_at&order=desc
