### ISSUE TITLE
翻页迟缓卡顿，CPU占用飙升。

### ISSUE THREAD

**Issue by RuntimeErrorz** [troyeguo/koodo-reader#609]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.4.9

### Bug Detail

几乎所有书阅读一定时间后翻页都会卡顿，CPU占用飙升至百分之30左右。
- CPU：11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz、AMD 5600X；
- 内存：16GB

### Files (Optional)

[Books.zip](https://github.com/troyeguo/koodo-reader/files/9806852/Books.zip)

**Comment by troyeguo** [comment]
不好意思，我这边没办法复现。麻烦提供一下任务管理器的截图或者录像

**Comment by sofeFE** [comment]
version 1.3.9 安装版
系统: win10 专业版 
电脑配置也都不算低. 
问题: 左右上下键 翻页的时候卡顿, 甚至没反应 .跟这位楼主的问题相似.
之前用的 1.2.6 绿色版 就没有这种情况. 翻页很流畅. 
更新到1.3.9 安装版本就成这样了. 
这种没法用图片展示, 视频怕都不容易展示.

**Comment by RuntimeErrorz** [comment]
> version 1.3.9 安装版 系统: win10 专业版 电脑配置也都不算低. 问题: 左右上下键 翻页的时候卡顿, 甚至没反应 .跟这位楼主的问题相似. 之前用的 1.2.6 绿色版 就没有这种情况. 翻页很流畅. 更新到1.3.9 安装版本就成这样了. 这种没法用图片展示, 视频怕都不容易展示. ps: 使用的时候也会出现 cpu占用率飙升到30-40% (都没开其他软件...).

是的，我想用实时展示按键来展示的，不过之后忘了这事了。

**Comment by dlmpx** [comment]
> 不好意思，我这边没办法复现。麻烦提供一下任务管理器的截图或者录像

![test](https://user-images.githubusercontent.com/73294677/210958565-6d8785db-2edd-4661-9dbd-288517d7e38a.gif)
阅读的是《鸟哥的Linux私房菜》，在阅读一段时间后，会出现此issue一样的情况，CPU和内存占用飙升，其中内存呈现占用急剧上升后陡然下降，正常情况下占用会稳定在300MB左右，猜测原因是内存泄漏？可见GIF图。（设置方面：1、开启摸鱼模式2、开启滚动模式3、开启繁简转换4、开启文字阴影。其余保持默认）

**Comment by RuntimeErrorz** [comment]
确实，我还在想这么严重的问题怎么没人提出？

**Comment by troyeguo** [comment]
这是epub.js的问题，后续会考虑替换
