### ISSUE TITLE
字体渲染问题

### ISSUE THREAD

**Issue by johnzjzlast** [troyeguo/koodo-reader#61]
左是AdobePDF的宋体，右为Koodo的宋体（同一字体）。Koodo的宋体看起来比较**细锐**（看着可能费眼），不够黑。不知道这方面有可能改善吗

![image](https://user-images.githubusercontent.com/57058325/105806755-80e88580-5fdf-11eb-8ebd-f9dd5cf1f838.png)

**Comment by troyeguo** [comment]
后续会增加字体加粗的选项

**Comment by johnzjzlast** [comment]
应该不是简单加粗的关系，可能跟字体渲染有关系，具体这方面不是很了解。
比如在AdobePDF中，平滑文本如果选成用于“手提电脑/液晶显示屏”，就显示的比较清晰平滑；如果选择“用于显示器”，就比较细锐。
![image](https://user-images.githubusercontent.com/57058325/105830405-6d99e200-6000-11eb-9f88-a16e02d6da4f.png)

**Comment by troyeguo** [comment]
字体渲染可能和屏幕设置或者electron应用底层技术有关，在我的知识范围内可能没法解决

**Comment by johnzjzlast** [comment]
有一款小众的epub阅读软件Justread，它的宋体显示的时候比koodo显示的宋体清晰一些（字体稍黑也不晕影），这个软件不知是否是基于electron（软件开发者已不维护），不知道koodo能否借鉴一下Justread在这方面完善下。

![image](https://user-images.githubusercontent.com/57058325/106860717-ba1ba680-66ff-11eb-84cf-1e9e3054a135.png)
