### ISSUE TITLE
滚动模式下 右侧显示不全.

### ISSUE THREAD

**Issue by jancrocus** [troyeguo/koodo-reader#611]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.9

### 我遇到的问题

滚动模式下 右侧页面显示不全, 滚动条 有遮挡.  1.4.1 没有这个问题, 之后的都有问题. 

### 截图或录像(可选的)

![image](https://user-images.githubusercontent.com/26436056/196583041-abd4e589-340e-4f6a-ae2d-42fd9296a758.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请更新至最新版
