### ISSUE TITLE
希望更改滚动模式键盘操作模式

### ISSUE THREAD

**Issue by sstiger1230** [troyeguo/koodo-reader#613]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

希望更改滚动模式键盘操作模式

### 细节描述

当前单页模式的键盘操作是翻页，滚动模式键盘操作是下一章。

希望滚动模式的键盘操作也是翻页。

谢谢。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑增加的

**Comment by anansamada** [comment]
> 感谢您的建议，会考虑增加的

很奇怪的是，滚动模式，在网页端，键盘向下箭头是滚动，在桌面端，键盘向下箭头是下一章。同样的操作是不同的效果。桌面端没有了键盘向下滚动的功能。希望双端统一，桌面端下箭头改为与网页一致的滚动。

**Comment by troyeguo** [comment]
> > 感谢您的建议，会考虑增加的
> 
> 很奇怪的是，滚动模式，在网页端，键盘向下箭头是滚动，在桌面端，键盘向下箭头是下一章。同样的操作是不同的效果。桌面端没有了键盘向下滚动的功能。希望双端统一，桌面端下箭头改为与网页一致的滚动。

请确保桌面版是最新开发版
