### ISSUE TITLE
关于日文轻小说插图翻页问题

### ISSUE THREAD

**Issue by X012C** [troyeguo/koodo-reader#624]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.4.9

### 我遇到的问题

日文的轻小说EPUB格式翻页的时候大概率会在插图页卡住。
复现：在插图和文本页来回翻几次即可，我通常在第二次必触发这个BUG。
 

### 图书文件(可选的)

图书来源：

**Comment by X012C** [comment]
Uploading Koodo Reader 2022-10-31 11-12-13.mp4…

**Comment by X012C** [comment]
https://user-images.githubusercontent.com/99554281/198923576-32c0d1f6-98dd-41ac-937d-c8eb1bfd573a.mp4

**Comment by troyeguo** [comment]
麻烦提供一下电子书文件

**Comment by X012C** [comment]
[Uploading 仅供测试用：アニメ『とある魔術の禁書目録』 Ｂｌｕ－...典付録) (z-lib.org).zip…]()

**Comment by X012C** [comment]
> 麻烦提供一下电子书文件

已上传。
