### ISSUE TITLE
打开图书出现问题

### ISSUE THREAD

**Issue by Cx330stars** [troyeguo/koodo-reader#627]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.9

### 我遇到的问题

我在打开一个以后缀名为md的文件,然后里面的所有的图书都不见了，只有刚刚打开的那个文件，但是写的笔记还在，标签也在，回收站里面也是空的

### 图书文件(可选的)

[README.md](https://github.com/troyeguo/koodo-reader/files/9906516/README.md)

**Comment by troyeguo** [comment]
控制台有报错吗？

**Comment by Cx330stars** [comment]
> 控制台有报错吗？

没有任何报错打开了里面全部是空的

**Comment by troyeguo** [comment]
不好意思，我这里没办法复现，您可以尝试备份恢复，看看是否还存在这个问题，如果还是存在，麻烦您把备份文件发给我们一份

**Comment by Cx330stars** [comment]
现在是好了不知道是什么问题之前，现在打开可以了
