### ISSUE TITLE
点击目录链接时，会弹出“是否用浏览器打开此链接”的弹窗

### ISSUE THREAD

**Issue by waahaa** [troyeguo/koodo-reader#63]
## 我的环境

| 名称     | 值  |
| -------- | --- |
| 操作系统 | win10 19041.685 | 
| 软件版本 | 1.2.0 | 

---

## 期望行为

点击目录链接正常转跳
## 当前行为
点击目录链接时，会弹出“是否用浏览器打开此链接”的弹窗

**电子书附件：**
[The Economist - Fri, 29 January.zip](https://github.com/troyeguo/koodo-reader/files/5893073/The.Economist.Fri.29.January.-.The.Economist.zip)

![无标题2 - 副本](https://user-images.githubusercontent.com/41323324/106260877-daf57f00-625b-11eb-99b5-0dd2688dfb98.png)

**Comment by troyeguo** [comment]
您好，感谢您的反馈，会在后续版本中修复这个问题的。
