### ISSUE TITLE
打开过的书籍无法导入书库

### ISSUE THREAD

**Issue by xiliangm** [troyeguo/koodo-reader#631]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.4.9开发版

### 我遇到的问题

“设置”里已开启“打开图书但不添加到书库”。出现问题如下：
1、浏览某本epub书籍A，直接打开（不是在主窗口模式下打开）。
2、看了下，感觉可以加入书库，关闭书本A，使用“导入图书”。
3、导入失效，仍然是在子窗口打开书本A。
4、需要关闭主程序，再打开程序，执行导入，才能成功把书本A导入书库。

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复这个问题的

**Comment by troyeguo** [comment]
请更新至最新版
