### ISSUE TITLE
Web demo on mobile loses reading progress

### ISSUE THREAD

**Issue by alliefli** [troyeguo/koodo-reader#633]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [ ] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Chrome/Edge

### App Version

1.3.9 (2021.12.4)

### Bug Detail

Using the web demo. If I reload the tab or exit the book I am currently reading and then reopen it I am back to the book's starting page.
Weirdly, this does not happen on the desktop browser, only on mobile browsers.

**Comment by troyeguo** [comment]
Sorry, we don't plan to support mobile broswer in forseeable future.
