### ISSUE TITLE
目录含上下层支持勾选默认展开多级目录

### ISSUE THREAD

**Issue by sometimessimple** [troyeguo/koodo-reader#635]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

![image](https://user-images.githubusercontent.com/113500461/200483346-3b704c70-cef6-4ff4-9c89-2adf9205cae9.png)
如图 这种目录建议可以在设置里打开默认展开

### 细节描述

如上

**Comment by syoux** [comment]
设置功能里面有默认展开所以目录的选项
![11](https://user-images.githubusercontent.com/46363328/201326614-342d225b-d6ad-410d-a44e-fa6d49956d2f.png)
