### ISSUE TITLE
Becomes unbearably slow after using the arrow keys to turn the page.

### ISSUE THREAD

**Issue by kinglouisph** [troyeguo/koodo-reader#643]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Other Linux distribution

### App Version

1.4.8

### Bug Detail

Reproduction instructions: 
1. Open a book
2. Use arrow keys to turn pages a few times
3. Notice that it starts to take a second or more to turn each page after the first few times

**Comment by troyeguo** [comment]
Sorry, we can't reproduce this bug. Can you provide us with a copy of the book you'r reading.

**Comment by troyeguo** [comment]
Thanks for the reply, we did manage to reproduce this bug in an old Windows pc. We'll look into it.

**Comment by troyeguo** [comment]
> > Thanks for the reply, we did manage to reproduce this bug in an old Windows pc. We'll look into it.
> 
> Is there a progress? It happens for me too, I'm using win 10

This bug should have been fixed in 1.5.2.  It‘s related to epub.js which has been deprecated  in the latest version. Please let us know if this is still persisting.

**Comment by kinglouisph** [comment]
Looks like it's still occurring.

Is there a difference in the page turning with the arrow buttons and the arrow keys? The bug is probably there.

**Comment by kinglouisph** [comment]
Ignore previous reply, haven't got the update

**Comment by kinglouisph** [comment]
Seems to be fixed.
