### ISSUE TITLE
停止朗读文字

### ISSUE THREAD

**Issue by alterkeyy** [troyeguo/koodo-reader#646]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

选中一些文字后，如果点击朗读文字，无法在停止，希望可以加入取消朗读的功能

### Details

如题

**Comment by troyeguo** [comment]
我这里无法复现这个问题，读完就会自动停止。如果是bug请重新作为bug提交。
