### ISSUE TITLE
m1 cannot open Koodo after installation

### ISSUE THREAD

**Issue by qyqx** [troyeguo/koodo-reader#647]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

15.0

### Bug Detail

After installation, when you open app, show "file damaged".

### Screenshots (Optional)

<img width="259" alt="image" src="https://user-images.githubusercontent.com/105941/205610879-bd1dcd79-13ae-4cfc-933c-940eeb04d039.png">

**Comment by troyeguo** [comment]
请阅读帮助文档

**Comment by muava12** [comment]
how to fix this? still happen to me on m1 sonoma
