### ISSUE TITLE
Cannot read archives created using 7-Zip (Both .7z and .zip)

### ISSUE THREAD

**Issue by nicovarley** [troyeguo/koodo-reader#649]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] #650

### Brief Introduction

Similar to this completed roadmap task: Add format support to cbz, cbt, cbr fb2, doc, docx, chm, html, rtf

It does not seem to understand archive files created using the software 7-Zip.

### Details

**### Using 7-Zip Archive Software**:
Folder -> Archive into .7z -> Folder.7z -> Rename folder to .cb7 -> Open with Koodo (not recognised) -> Instantly closes the window and fails

Folder -> Archive into .7z -> Folder.7z -> Rename folder to .cbz -> Open with Koodo -> Opens as normal, stuck on loading indefinitely

Folder -> Archive into .zip -> Folder.zip -> Rename folder to .cbz -> Open with Koodo -> Opens as normal, stuck on loading indefinitely

**### Using Windows 11 OS Archive Software**:
Folder -> Archive into .zip -> Folder.zip -> Rename folder to .cbz -> Open with Koodo -> Opens as normal, reads as normal

**### Extra Information About 7-Zip**: 
As far as I know, 7-Zip is quite popular on the Western internet and it offers better (still lossless) compression than PKZip and WinRAR, so support would be lovely! Though unnecessary as for now as items can be extracted and rezipped using the standard OS archiver. Due to worse compression rates with that, I think supporting 7-Zip would be great for large libraries of cbz and cb7 files. Just in case you've not encountered it before, here's the website for it, it's fully open source software: https://www.7-zip.org/download.html.

Also, thank you so much I can't believe how amazing this e-book reader is. I'm so happy I found out about it!

**Comment by troyeguo** [comment]
Thanks for the advice, cb7 is not supported yet due to technique issue. We will look into the situation where cbz file compressed with 7-zip can't be opened.

**Comment by nicovarley** [comment]
Thank you so much!

**Comment by Zopolis4** [comment]
I'm having the same issue with a .cbr file, it never loads. I can open it with .7z and I see a bunch of .cbz files.

**Comment by troyeguo** [comment]
Sorry, we're having problems to reproduce this bug. Can you send us an cbz file compressed with 7-zip which can't be opened with Koodo?

**Comment by troyeguo** [comment]
Also, is it possible that you're directly compressing a folder containing images into zip file instead of images themselves?

**Comment by nicovarley** [comment]
I have tried with a subfolder within the archive, and that failed as you said above. However, I am able to get this behaviour every time when zipping the images directly. Git won't let me upload the .cb[?] format directly so here's a google drive link: https://drive.google.com/file/d/14nl-ocSVi-UBelrqUNS1BjNpY8jQFKia/view?usp=sharing

**Comment by troyeguo** [comment]
cb7 is not supported due to technique issue as i said above. I was actually expecting an cbz file compressed with 7-zip which can't be opened with Koodo. You can compress the cb* file into an zip file and then drag it into the textbox.

**Comment by Zopolis4** [comment]
Every comic i've gotten via Omnibus isin't able to be opened, maybe that has something to do with it/should help in reproducing the problem.

**Comment by troyeguo** [comment]
> Every comic i've gotten via Omnibus isin't able to be opened, maybe that has something to do with it/should help in reproducing the problem.

Can you send us a copy or a web link where i can download it.

**Comment by nicovarley** [comment]
Thank you, would be nice to support 7z format in the future as it does save a lot of space on big libraries but just re-archiving to zip is completely fine so no point in keeping this open. Thanks!
