### ISSUE TITLE
提一些建议

### ISSUE THREAD

**Issue by cantonadong** [troyeguo/koodo-reader#65]
首先非常感谢作者能做这一款应用，一直在找Windows阅读EPUB的软件。
提一些小建议，希望可以考虑：

1. 加快启动速度，现在不知道为啥启动都要loading一下
2. 提升EPUB打开速度，现在打开14m的有些延迟感
3. 增加翻页效果，可以是模拟，或者就就是横划都行
4. 简化画线交互，横划后，默认高亮黄色，可同界面输入评论，移出焦点就保存。可切换颜色，或删除标记。现在的交互太复杂。
5. 支持导出画线和评论。
6. 可固定目录、添加书签按钮。可参考多看和微信读书。
7. 可更换字体、缩放大小。
8. 可直接复制图片到剪贴板

可以多参考NeatReader、多看、微信读书的体验和交互，谢谢。

**Comment by cantonadong** [comment]
1. 支持导出画线和评论到有道笔记
2. 支持在空白区域评论和标记（屏幕上画图，类似OneNote那种）
3. 支持划线区域快速复制
4. 支持在图片上右键复制、导出
5.

**Comment by troyeguo** [comment]
感谢您的建议，可能不同的人有不同的阅读习惯，无法完全满足所有人的要求，关于字体和图片的需求，koodo reader已经支持，您的部分要求后续可能会以付费功能的形式推出，希望您到时候能支持。
