### ISSUE TITLE
希望增加书籍批量处理功能

### ISSUE THREAD

**Issue by summerdshaa** [troyeguo/koodo-reader#660]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

批量处理包括：批量选中后进行删除、书架移动等

### 细节描述

无

**Comment by troyeguo** [comment]
左上角有选择按钮
