### ISSUE TITLE
关于翻译功能: "翻译引擎选择下拉框"遮挡文字

### ISSUE THREAD

**Issue by chunis** [troyeguo/koodo-reader#662]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

关于翻译功能的小问题

### 细节描述

非常感谢软件作者的付出! :+1:  最近发现一个小问题:

目前的翻译窗口当内容太多占用到最下面一行时, "翻译引擎选择下拉框"会遮挡一些文字 导致无法显示.
这个问题当 https://github.com/troyeguo/koodo-reader/issues/473 解决后可以避免. 或者也可以考虑将"翻译引擎选择下拉框"放到和"目标语言"同一行的位置.

**Comment by troyeguo** [comment]
您使用的是1.5.0版吗？可以截图说明一下吗？

**Comment by chunis** [comment]
是的，1.5.0版。
截图如下。那个“Bing”选择框会遮挡后面的内容：
![Capture d’écran du 2022-12-17 18-24-50](https://user-images.githubusercontent.com/462643/208237592-8ee975a5-5ce0-4e78-84a7-f41e04dc3ba9.png)
谢谢。

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至最新版
