### ISSUE TITLE
请问如何安装web版本？我在windows2008上用yarn安装失败了。。。

### ISSUE THREAD

**Issue by snow2zhou** [troyeguo/koodo-reader#67]

**Comment by troyeguo** [comment]
开发方面的问题请参考环境要求，自行解决，部分依赖可能需要科学上网才能正常安装。

**Comment by snow2zhou** [comment]
不是，我是想安装web版本的，就是安装好后，可以用浏览器打开，请问要怎么安装？下载那个版本？

**Comment by snow2zhou** [comment]
安装好后，就像这个网址一样：https://reader.960960.xyz/

**Comment by troyeguo** [comment]
> 不是，我是想安装web版本的，就是安装好后，可以用浏览器打开，请问要怎么安装？下载那个版本？

开发部署的问题太复杂，请自行解决。本人没有在windows 服务器上开发部署的经验，建议您使用vercel来部署项目。

**Comment by snow2zhou** [comment]
好的，谢谢。
