### ISSUE TITLE
导入epub时提示失败

### ISSUE THREAD

**Issue by wsbhacker** [troyeguo/koodo-reader#676]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

导入epub图书时提示导入失败

### 图书文件(可选的)

[test.zip](https://github.com/troyeguo/koodo-reader/files/10327521/test.zip)

**Comment by troyeguo** [comment]
图书已损坏，其他epub阅读器也无法打开
