### ISSUE TITLE
feat: web版增加对mobi格式的阅读支持

### ISSUE THREAD

**Issue by snow2zhou** [troyeguo/koodo-reader#68]
## Brief Introduction (这是一个怎样的功能？)
web版增加对mobi格式的阅读支持

## Details (详细解释)
方便阅读。

**Comment by troyeguo** [comment]
技术原因无法实现，暂时无法实现这个功能。

**Comment by snow2zhou** [comment]
好的。
我把web版安装好了，但是用不同的浏览器打开，不能够同步书籍，上传的书籍只能在上传的那个浏览器里才能看到。。。
能上传一次，所有浏览器都能都同步看到吗？

**Comment by troyeguo** [comment]
这个是一个本地阅读器，不提供同步功能，后续可能推出收费同步功能
