### ISSUE TITLE
图书目录错误，翻页空白

### ISSUE THREAD

**Issue by qpshot** [troyeguo/koodo-reader#684]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

图书目录有点奇怪，直接翻页是空白

### 图书文件(可选的)

[霍布斯鲍姆年代四部曲（套装共4册） 《革命的年代：1789—1848》《资本的年代：1848～1875》《帝国的年代：1875—1914》《极端的年代：1914—1991》 by [英] 艾瑞克·霍布斯鲍姆 (z-lib.org).zip](https://github.com/troyeguo/koodo-reader/files/10345110/4.1789.1848.1848.1875.1875.1914.1914.1991.by.z-lib.org.zip)

**Comment by troyeguo** [comment]
这是epub.js的问题，后期会考虑替换掉的

**Comment by troyeguo** [comment]
请升级至最新版
