### ISSUE TITLE
翻译框显示“出错了”，无法翻译（包括其他语言）

### ISSUE THREAD

**Issue by guanxiaofeiguanxiaofei** [troyeguo/koodo-reader#689]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

初次使用翻译功能一切正常，当电脑断网重连后，翻译框显示“出错了”，尝试切换其他语言，切换Google，以及重启koodo后，仍无效，也许这是一个显示bug。

### 截图或录像(可选的)

<img width="537" alt="Snipaste_2023-01-06_15-24-36" src="https://user-images.githubusercontent.com/116361250/210952187-b59e9681-c401-4c92-b36d-27c8bec44fbe.png">
<img width="550" alt="Snipaste_2023-01-06_15-24-57" src="https://user-images.githubusercontent.com/116361250/210952193-a9524349-83bc-4a91-85c7-e26d9f0f75a6.png">

**Comment by luojunhui1** [comment]
遇到了同样的问题

**Comment by huajianxiaowanzi** [comment]
同样

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复

**Comment by Tamrac-web** [comment]
遇到同样的问题，但没有显示任何错误，翻译框里只显示空白。

**Comment by Tamrac-web** [comment]
> 感谢您的反馈，会在下个版本修复

非常感谢开发者！我想如果可以加入沉浸式翻译功能就非常完美了。让原文和翻译同时存在，这样对学习英语有很大的帮助！
例子：沉浸式翻译插件

**Comment by troyeguo** [comment]
请升级至最新版

**Comment by Tamrac-web** [comment]
非常感谢，希望您生活愉快工作顺利！


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YainHolmes** [comment]
1.5.1也还是这样兄弟解决了没有

**Comment by fromchinasrookie** [comment]
已经2024年了。翻译还是这样子。版本号1.5.1
