### ISSUE TITLE
dropbox無法備份

### ISSUE THREAD

**Issue by xiaoao19** [troyeguo/koodo-reader#69]
This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |           |
| App Version (应用版本)      |           |

---

**Comment by troyeguo** [comment]
感谢您的反馈，已经向dropbox提交了api申请，您可以再尝试一下。
