### ISSUE TITLE
希望增加电子书图片旋转90°/180°/270°进行显示功能

### ISSUE THREAD

**Issue by nemoiwkryang** [troyeguo/koodo-reader#692]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

如题，有时在电子书中可能有图片与正常阅读的方向不同，例如图片被逆时针旋转了90°，可能会用到这个功能

### Details

比如这样
![image](https://user-images.githubusercontent.com/111504576/211197160-4b77d9e7-4b86-49c3-817e-e13afb0a79a6.png)
正常情况下应该是
![image](https://user-images.githubusercontent.com/111504576/211197180-2175dadc-6e31-4084-888f-645cb3439e04.png)
这种情况下移动端设备可以比较容易的旋转设备方向来看，但是对电脑不便于这样操作
能否增加此功能？类似于Windows的照片应用的旋转选项
![image](https://user-images.githubusercontent.com/111504576/211197110-5ec2fa5f-a8de-4034-b4dd-cbd311648c8d.png)

**Comment by troyeguo** [comment]
这个功能已支持
![image](https://user-images.githubusercontent.com/13820674/211267697-8a1f6954-db60-4b7b-9bc2-77b91bf299e0.png)

**Comment by nemoiwkryang** [comment]
啊啊，是我的问题，之前没有仔细看，被白色背景的图片盖住了，不好意思
能否给这几个图标加上一圈黑边？这样即使是白色背景也能容易看见，谢谢

**Comment by troyeguo** [comment]
感谢您的建议，会考虑的
