### ISSUE TITLE
1.5.1 Windows 版本 摸鱼模式不透明了

### ISSUE THREAD

**Issue by sangshuduo** [troyeguo/koodo-reader#693]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.5.1

### Bug Detail

Windows 版本摸鱼模式不透明，之前是透明的，没找到有什么地方可以配置

**Comment by troyeguo** [comment]
请检查阅读背景是否关闭

**Comment by troyeguo** [comment]
![image](https://user-images.githubusercontent.com/13820674/211477090-c6686ee9-2d6c-4bcc-a5a8-9dc398d5382a.png)

**Comment by sangshuduo** [comment]
![image](https://user-images.githubusercontent.com/825729/211485685-4b5c0029-0362-4180-8eee-6b0e4129237a.png)

验证了无论是否关闭这个选项都没有透明

**Comment by troyeguo** [comment]
之前的版本是正常吗？windows 10 上试过吗？

**Comment by sangshuduo** [comment]
> 之前的版本是正常吗？windows 10 上试过吗？

昨天升级前还是正常的，升级了之后就不能透明了，另外试了回退到几个之前的版本也不再透明，所以感觉不是版本问题，不确定是不是有和渲染相关的 dll 问题或者有什么其他设置。
不记得最早装 koodo reader 是在 10 还是 11，手上没有 10 的环境了

**Comment by troyeguo** [comment]
这是黑夜模式的问题，您在设置里改成白天模式应该就可以了，会在下个版本修复这个问题的，1.5.1版本开始外观默认改成了追随系统，升级过1.5.1就会有影响。

**Comment by sangshuduo** [comment]
> 这是黑夜模式的问题，您在设置里改成白天模式应该就可以了，会在下个版本修复这个问题的，1.5.1版本开始外观默认改成了追随系统，升级过1.5.1就会有影响。

好的，确实改成白天就可以了，期待下一个版本
