### ISSUE TITLE
选择对应目录小节跳转错误

### ISSUE THREAD

**Issue by lxymahatma** [troyeguo/koodo-reader#696]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1 最新稳定版

### 我遇到的问题

选择第一章里的Anatomy of a Simple Program小节的Classes小节，会跳转到第三章的Classes小节 （并且在目录里的C#的#号显示不出来变成了C）

### 图书文件(可选的)

[OReilly.Programming.C#.10.2022.8.zip](https://github.com/troyeguo/koodo-reader/files/10383679/OReilly.Programming.C.10.2022.8.zip)

**Comment by troyeguo** [comment]
感谢您的反馈

**Comment by troyeguo** [comment]
请升级至最新版
