### ISSUE TITLE
Sliding animation not working for epub

### ISSUE THREAD

**Issue by blastentwice** [troyeguo/koodo-reader#697]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.51

### Bug Detail

Hi.

I've tried running the app through windows, linux and web and for some reason the sliding animation doesn't work for me. I was hoping to get the same effect as #558 (minus their bug) but it just changes pages without animation regardless if sliding animation was on or off.

Thank You!

**Comment by troyeguo** [comment]
Due to techinique issue, slilding animation is not supported in epub files.

**Comment by troyeguo** [comment]
Please update to the latest version
