### ISSUE TITLE
有考慮i18n加上繁體中文的支援嗎?

### ISSUE THREAD

**Issue by playercd8** [troyeguo/koodo-reader#7]
例如 \src\assets\locales\tw\translation.json

{
  "Download Demo Book": "下載範例圖書",
  "All Books": "全部圖書",
  "Recent Books": "最近閱讀",
  "My Bookmarks": "我的書籤",
  "My Notes": "我的筆記",
  "My Digests": "我的書摘",
  "My Shelves": "我的書架",
  "Sort": "排序",
  "Authorizing": "授權中，請稍候",
  "Downloading": "下載中，請稍候",
  "Uploading": "上傳中，請稍候",
  "Import from Local": "從本機導入",
  "Backup and Restore": "備份和恢復",
  "Search My Library": "搜索我的書庫",
  "Card Mode": "卡片模式",
  "List Mode": "列表模式",
  "Work": "工作學習",
  "Entertainment": "休閒娛樂",
  "Study": "生活百科",
  "Author": "作者",
  "Reading Time": "已讀",
  "Content": "目錄",
  "Bookmark": "書籤",
  "Single-Page Mode": "單頁模式",
  "Double-Page Mode": "雙頁模式",
  "Background Color": "背景顏色",
  "Font Size": "字體大小",
  "Font Family": "字體",
  "Default": "預設",
  "Small": "小",
  "Medium": "中",
  "Large": "大",
  "Extra Large": "特大",
  "Ultra Large": "超大",
  "Reading Option": "閱讀選項",
  "Current Progress": "當前進度",
  "Exit": "結束閱讀",
  "Empty Shelf Title": "書架名為空",
  "Enter Fullscreen": "進入全螢幕",
  "Exit Fullscreen": "退出全螢幕",
  "Add Bookmark": "添加書籤",
  "Add to Shelf": "添加到書架",
  "New Shelf": "新建",
  "New": "新建書架",
  "Copy Successfully": "複製成功",
  "Cancel": "取消",
  "Confirm": "確認",
  "Delete": "刪除",
  "Delete This Book": "刪除這本書",
  "Edit Book": "編輯圖書",
  "Edit Successfully": "編輯成功",
  "Book Name": "書名",
  "Sort by Date": "按添加時間",
  "Descending Order": "倒序",
  "Ascending Order": "正序",
  "Sort by Name": "按名稱",
  "Copy Link Successfully": "鏈接複製成功",
  "Add Successfully": "添加成功",
  "Select": "選擇",
  "Coming Soon": "敬請期待",
  "Authorize Successfully": "授權成功",
  "Authorize Failed": "授權失敗",
  "You can turn off this tab now": "您可以關閉此標籤頁了",
  "Do you want to backup or restore?": "您想要備份還是恢復?",
  "Where is your data?": "您的資料保存在哪裡?",
  "Where to keep your data?": "您想把資料存在哪裡?",
  "I want to backup": "我要備份",
  "I want to restore": "我要還原",
  "Backup Successfully": "備份成功",
  "Restore Successfully": "還原成功",
  "Try refresh or restart": "重新整理後生效",
  "Wrong bookmark": "書籤出問題了",
  "Last Step": "上一步",
  "Next Step": "下一步",
  "Go To": "點擊前往",
  "Delete from Shelf": "從書架刪除本書",
  "Delete Successfully": "刪除成功",
  "This action will delete all the notes, bookmarks and digests of this book": "同時刪除本書所有的書籤，筆記，書摘",
  "This action won't delete the original book": "僅從此書架中刪除本書，原圖書不受影響",
  "From": "來自",
  "Duplicate Book": "圖書重複",
  "Unknown": "未知",
  "Minute": "分鐘",
  "Empty": "書籤為空",
  "Less": "收起",
  "More": "顯示筆記出處",
  "Pick Up Color": "選擇顏色",
  "Highlight Successfully": "高亮成功",
  "Take Notes": "記筆記",
  "Collect": "摘錄",
  "Highlight": "高亮",
  "Copy": "複製",
  "Bind": "綁定",
  "Token": "憑證",
  "Token Info": "請複製以下鏈接到瀏覽器打開，登錄授權後，您將獲得一串代碼，請將代碼填入以下輸入框即可完成綁定",
  "Copy Link": "複製鏈接",
  "Copy Token": "複製憑證",
  "Copied": "已複製",
  "Hi! Stranger": "你好啊！朋友",
  "Skip": "不再提示",
  "Local": "本機",
  "Line Height": "行間距",
  "Empty Library": "圖書庫為空",
  "Click the top-right button to add books": "請點擊右上角的導入圖書按鈕添加圖書",
  "Empty Reading Records": "您沒有閱讀記錄",
  "Click on any book to read": "點擊任意一本書開始閱讀",
  "Empty Bookmark": "您的書籤為空",
  "Move your mouse on the top edge of the reader": "在閱讀器界面，將滑鼠游標移至上邊緣處，在彈出的選單欄中添加書籤",
  "Empty Note": "您的筆記為空",
  "Select any text and click the Add-Note button on the popup Menu": "在閱讀器界面，選中文字後，在彈出的對話框中添加筆記",
  "Empty Digest": "您的書摘為空",
  "Select any text and click the Collect button on the popup Menu": "在閱讀器界面，選中文字後，在彈出的對話框中點擊摘錄",
  "Empty Shelf": "您的書架為空",
  "Move your mouse on the top of any book": "將滑鼠游標移動到任意書本上方，在彈出的菜單中點擊加號添加到書架",
  "This is a free and open-source Epub reader": "這是一個免費開源的Epub閱讀器",
  "Koodo Reader works on multiple platforms with backup and restore support": "Koodo Reader同時支持桌面版和網頁版，您所有的資料都可以導入導出和支持多端同步",
  "For better reading experience": "只為最好的閱讀體驗",
  "Supports for theme changing, reading history, book managerment, shelf managerment and more": "主題切換，閱讀歷史，圖書管理，書架管理，更多功能等你探索",
  "Fluent and easy operation": "簡單流暢的操作方式",
  "Move your mouse to the edge of the reader to trigger menu,use mouse wheel and keyborad to switch pages": "鼠標移至邊緣彈出選單，使用滑鼠滾輪或鍵盤的上下左右按鍵控制翻頁",
  "Go to Add your first book": "快去添加您的第一本書吧",
  "That's all for the tutorial": "介紹完畢",
  "Download failed,network problem or no backup": "下載失敗，網路出錯或者沒有找到備份",
  "Upload failed, check your connection": "上傳失敗，請檢查網路連接"
}

**Comment by troyeguo** [comment]
感谢您提供的翻译，会在下个版本中支持繁体中文的
