### ISSUE TITLE
坚果云webdav，进行备份前，密码输错后自动上传备份，然后卡在一个界面，下次点击备份时，还是进入上传备份界面，无法重新输入的密码？

### ISSUE THREAD

**Issue by 913650629** [troyeguo/koodo-reader#70]
在请稍后之前，会出现网络错误，连接不上服务器，关闭软件重新打开后，点击我要备份，直接进入上传模式，陷入循环。
![image](https://user-images.githubusercontent.com/66675245/106829398-072f5680-66c7-11eb-924c-a0c0d6eb0ad9.png)

**Comment by 913650629** [comment]
正确输入密码后，备份成功，进行回复时出现问题、
![image](https://user-images.githubusercontent.com/66675245/106830234-9e48de00-66c8-11eb-82af-63fb1c3e950c.png)

**Comment by troyeguo** [comment]
感谢您的反馈，webdav备份功能刚上线，确实可能出现这些问题，第二张图的问题，退出软件，重新进入就好了。

**Comment by troyeguo** [comment]
会在下个版本修复这些问题的
