### ISSUE TITLE
目录希望能够定位到当前章节

### ISSUE THREAD

**Issue by elianbeyond** [troyeguo/koodo-reader#703]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

1.5.1最新稳定版  目录正常提取，但是看的过程中点击左侧目录不能定位到当前章节，需要从第一章翻下去。
如果是bug，希望大佬了解一下，如果没有这个功能很期待开发完善。

### 细节描述

![image](https://user-images.githubusercontent.com/68109437/212506321-3f150adb-9b8a-484b-bda4-9e7c9447a309.png)

**Comment by troyeguo** [comment]
请升级至最新版
