### ISSUE TITLE
使用网页版，无法正常打开txt格式书籍；客户端版本正常。

### ISSUE THREAD

**Issue by laofour** [troyeguo/koodo-reader#706]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

网页版

### 我遇到的问题

使用网页版，无法正常打开本地txt格式书籍，显示为一片空白，该文档可通过其他软件正常打开；使用edge、chrome、firefox都是这样，txt文档无论文件大小都是这样；客户端版本一切正常。

**Comment by troyeguo** [comment]
感谢您的反馈，现在已经恢复了。
