### ISSUE TITLE
字体渲染问题2

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#71]
有一款小众的epub阅读软件Justread，它的宋体显示的时候比koodo显示的宋体清晰一些（字体稍黑也不晕影），这个软件不知是否是基于electron（软件开发者已不维护），不知道koodo能否借鉴一下Justread在这方面完善下。左为koodo，右为Justread

![image](https://user-images.githubusercontent.com/57058325/106860717-ba1ba680-66ff-11eb-84cf-1e9e3054a135.png)

**Comment by troyeguo** [comment]
Justread 我没有找到宋体的选项，只有一个Noto Serif看起来比较像宋体，我给koodo的文字加上font-weight:bold样式之后，看起来会好一些，后续会增加这个样式选项的。
<img width="243" alt="dfsa" src="https://user-images.githubusercontent.com/13820674/106866272-38c81200-6707-11eb-9974-abeec32cdf59.PNG">

**Comment by actforjason** [comment]
我在系统里安装了其他宋体（思源宋体），看起来字体好多了。加粗应该不用了，字体可以安装个粗体的。
![image](https://user-images.githubusercontent.com/57058325/106871587-58facf80-670d-11eb-911d-230a7f2d1059.png)

**Comment by actforjason** [comment]
可能系统自带的宋体不适合阅读
