### ISSUE TITLE
某些word格式文件无法导入

### ISSUE THREAD

**Issue by SkylenGu-Git** [troyeguo/koodo-reader#710]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

某些word格式文件无法导入，且没有任何反应或提示。
附件中有该文档。

### 图书文件(可选的)

[胡雪岩官商智慧大全.zip](https://github.com/troyeguo/koodo-reader/files/10527887/default.zip)

**Comment by troyeguo** [comment]
Koodo不支持doc，只支持docx
