### ISSUE TITLE
Some book covers do not show.

### ISSUE THREAD

**Issue by robertsouza2007** [troyeguo/koodo-reader#714]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.5.1

### Bug Detail

When I add books, some covers do not show. I have selected the option to turn first page into the thumbnail cover, but it does not work in some cases no  matter what.

**Comment by troyeguo** [comment]
we will add cover support to mobi, azw3 and comic books in the next update.

**Comment by troyeguo** [comment]
Please update to the latest version and reimport the book
