### ISSUE TITLE
使用 epub  文件 ，底部 【本章页数，章节数】显示不正确

### ISSUE THREAD

**Issue by subtle99** [troyeguo/koodo-reader#717]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

使用 epub  文件 ，底部 【本章页数，章节数】显示不正确

### 截图或录像(可选的)

![koodo bug](https://user-images.githubusercontent.com/59327126/217104136-fd42a2b6-f121-486b-b1f9-2b4d398257e3.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至最新版
