### ISSUE TITLE
列表模式点红心标记，切换到封面模式红心没有改变

### ISSUE THREAD

**Issue by subtle99** [troyeguo/koodo-reader#718]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

列表模式点红心标记，切换到封面模式红心没有改变

**Comment by troyeguo** [comment]
不好意思，我这里无法复现，您可以提供一下您的操作录像吗？

**Comment by subtle99** [comment]
列表模式-选中红心：
![列表模式-选中红心](https://user-images.githubusercontent.com/59327126/218381131-142d2ba7-0c18-44aa-abdb-2b345e9840b7.png)
封面模式-没有红心：
![封面模式-没有红心](https://user-images.githubusercontent.com/59327126/218381152-468be036-d58f-4057-830d-a9a1d66cca17.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至最新版
