### ISSUE TITLE
目录记忆或定位

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#72]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |     Windows      |
| App Version (应用版本)      |      1.2.0     |

---

## 问题
书籍重新打开后会返回到之前阅读的记忆位置，但是目录还是初始状态，希望目录具有记忆功能，或有个按键定位当前阅读章节在目录中的对应位置（类似歌单中的定位当前歌曲功能）。
如果可以的话希望添加目录编辑功能。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑在后续版本中增加这个功能的。

**Comment by PhysicsOfCondensedMatter** [comment]
> 感谢您的建议，会考虑在后续版本中增加这个功能的。

兄弟，我也在反馈这个问题，我也需要这个功能，都一年了，你们不加吗

**Comment by troyeguo** [comment]
功能已支持，请更新最新开发版。
