### ISSUE TITLE
希望能支持更多朗读引擎，比如edge的朗读引擎

### ISSUE THREAD

**Issue by wsy1074** [troyeguo/koodo-reader#723]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

现在的在线朗读引擎已经非常好用了，希望能接入或者允许自定义

### 细节描述

无

**Comment by troyeguo** [comment]
技术原因无法实现
