### ISSUE TITLE
希望导入图书的时候可以根据当前书架分类导入到对应书架

### ISSUE THREAD

**Issue by magicdmer** [troyeguo/koodo-reader#727]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

版本：1.5.1稳定版
描述：导入或者拖拽导入图书的时候希望根据当前选择的书架分类，自动将书籍加入到对应分类书架中

### 细节描述

导入或者拖拽导入图书的时候希望根据当前选择的书架分类，自动将书籍加入到对应分类书架中

**Comment by troyeguo** [comment]
感谢您的建议，会考虑的

**Comment by troyeguo** [comment]
请升级至最新版
