### ISSUE TITLE
希望能添加对windows for arm的支持

### ISSUE THREAD

**Issue by fkiliver** [troyeguo/koodo-reader#728]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

项目已经有macos上的arm支持，能否添加对windows for arm的支持

### 细节描述

希望添加对windows for arm的支持

**Comment by troyeguo** [comment]
感谢您的建议，会考虑的

**Comment by troyeguo** [comment]
请升级至最新版，已经支持
