### ISSUE TITLE
操作上出现了严重的延迟

### ISSUE THREAD

**Issue by haoxiaoyueh** [troyeguo/koodo-reader#729]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.2

### 我遇到的问题

对于一些较大的txt文件，我每进行一次操作就要响应非常漫长的时间，我认为这种情况是不正常的。我单单只是点击了一次全屏它就要卡顿半分钟，我甚至连笔记都做得很艰难，这严重地影响着我的使用体验，我在低一级的稳定版本就遇到了这个问题，而在这个新的测试版本中问题仍未被解决，我希望能尽快改善这种情况，让我能阅读的更加流畅。

### 图书文件(可选的)

[我打造了旧日支配者神话.zip](https://github.com/troyeguo/koodo-reader/files/10777185/default.zip)

**Comment by troyeguo** [comment]
主要还是分章算法的问题，这本书只分出了3章，导致一章的文字太多就变卡了。会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至最新版

**Comment by haoxiaoyueh** [comment]
从644章之后又出现了这种情况下，分不出章节，全攒到一起了
![分不出章节了](https://user-images.githubusercontent.com/113106402/226164834-cf842ae2-71c0-4054-b5d7-5d9e9492ac2c.png)

**Comment by VerVer-X** [comment]
用的是1.74稳定版，正在看epub格式的书，章节一多起来，不管是打开书本时、对目标字段全文搜索，甚至切换上下页都很慢，搜索时有时能卡一分钟，内存条64G DDr4的
![Image](https://github.com/user-attachments/assets/2cde2619-0c88-4add-bd40-fc9602f115d0)
