### ISSUE TITLE
希望基于文件目录同步而不是备份

### ISSUE THREAD

**Issue by xiaoao19** [troyeguo/koodo-reader#73]
您好，我尝试了dropbox，现在似乎可以了。但是需要授权完整目录访问权限而不是指定目录，我就放弃了。

这两天我在尝试joplin基于文件夹的同步，用 syncthing同步到局域网设备+ 用dropbox同步到云端。

这样笔记本系统就完美实现了开源数据私有和跨平台云同步。

我也是电子书阅读的重度使用者，希望koodo-reader 能参考joplin这种基于文件目录的同步（包括电子书、进度、读书笔记），而不是备份一个zip。

我不是技术人员 ，可能表述准确度有点问题，希望能说明白，谢谢，期待koodo越来越好。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑在后续版本中增加这个功能

**Comment by xiaoao19** [comment]
在新功能出现前 我想尝试手动基于缓存同步  windows系统的缓存目录我已经找到了 能告诉我mac的缓存在哪里吗 谢谢

**Comment by troyeguo** [comment]
> 在新功能出现前 我想尝试手动基于缓存同步 windows系统的缓存目录我已经找到了 能告诉我mac的缓存在哪里吗 谢谢

我没用过mac，google了一下，应该是这个目录：~/Library/Application/koodo-reader

**Comment by xiaoao19** [comment]
測試mac和windows缓存用syncthing同步成功
两个电脑的图书 进度 书摘 笔记 都能同步显示
就是缓存文件夹隐藏比较深 不太好找
期待新版本 期待新版可以自定义同步文件夹 像joplin这种形式 比较简单
谢谢
