### ISSUE TITLE
Epub文件中的图片无法加载

### ISSUE THREAD

**Issue by HFE-Omega** [troyeguo/koodo-reader#736]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

打开一本轻小说,插图无法加载,少部分封面可以显示

### 截图或录像(可选的)

![JMKDT3H4V)D$@HT8OXPR{(M](https://user-images.githubusercontent.com/101941617/222102152-e4c2f903-7eb2-444f-9b40-1b7c76facc88.png)

### 图书文件(可选的)

[01 - 凉宫春日的忧郁.zip](https://github.com/troyeguo/koodo-reader/files/10859398/01.-.zip)

**Comment by troyeguo** [comment]
这本书制作得不太复合epub规范，只能用calibre转换之后，才能正常显示

**Comment by troyeguo** [comment]
请升级至1.5.3，已经修复了

**Comment by HFE-Omega** [comment]
> 请升级至1.5.3，已经修复了

感谢!
