### ISSUE TITLE
从本地导入文件过大卡住没反应

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#74]
epub文件才20M，导入的时候就一直“请稍等”，很长时间没反应，也没等出个结果

![image](https://user-images.githubusercontent.com/57058325/107122234-79738700-68d1-11eb-81d5-d5f78ba705f1.png)

**Comment by actforjason** [comment]
其他大的有的能导入，不过加载很慢，文件本身没问题

**Comment by actforjason** [comment]
又试了下都能导进去了，我重新复制了下文件（原来手机上没事），可能文件出问题了。
不过大文件第一次进去还是很卡，得退出重进

**Comment by troyeguo** [comment]
感谢您的反馈
