### ISSUE TITLE
听书时没有段落高亮

### ISSUE THREAD

**Issue by king4107** [troyeguo/koodo-reader#745]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

听书时没有段落高亮

### 细节描述

听书时没有段落高亮

**Comment by troyeguo** [comment]
感谢您的建议，会考虑添加的

**Comment by king4107** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by king4107** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
