### ISSUE TITLE
关于隐藏图书的功能

### ISSUE THREAD

**Issue by QIeliBEieR** [troyeguo/koodo-reader#747]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

能不能在全部图书模式下，添加一个单独设置某本书的显示与否的功能。简单点说，在全部图书这个界面下，我能让把某些书不显示，具体到某个具体的分类，或者显示隐藏书籍的时候才全部显示。

### 细节描述

在全部图书下，在书籍的详细页里增加 隐藏功能，并在全部图书旁边增加显示隐藏文件

**Comment by troyeguo** [comment]
后续会增加隐藏添加到书架的图书的功能，一定程度上可以实现这个需求

**Comment by troyeguo** [comment]
请升级至最新版
