### ISSUE TITLE
1.5.2 breaks epub files on linux.

### ISSUE THREAD

**Issue by rago666** [troyeguo/koodo-reader#749]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Other Linux distribution

### App Version

1.5.2

### Bug Detail

Version 1.5.2 breaks epub files on linux (Fedora 37). Tried both flatpak & native rpm package. Nor images or text render properly.  

### Screenshots (Optional)

Version 1.5.1
![Screenshot from 2023-03-16 18-28-30](https://user-images.githubusercontent.com/51720144/225620580-efe73f6f-a332-46a6-a4ca-464e0861f742.png)

![Screenshot from 2023-03-16 18-28-43](https://user-images.githubusercontent.com/51720144/225620937-7a8ea90c-d2a2-441b-be71-fbb053c65693.png)

Version 1.5.2
![Screenshot from 2023-03-16 18-27-10](https://user-images.githubusercontent.com/51720144/225621071-8314f756-a79c-45cc-bd97-e8017814e6f7.png)
![Screenshot from 2023-03-16 18-44-34](https://user-images.githubusercontent.com/51720144/225621122-9deae05a-5b11-47b1-a447-fdd540de352b.png)

### Files (Optional)

[Redemption.zip](https://github.com/troyeguo/koodo-reader/files/10990865/Redemption.zip)

**Comment by troyeguo** [comment]
Please update to 1.5.3
