### ISSUE TITLE
书籍内交叉引用

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#75]
点击引用（注释）的上标会弹出“使用浏览器打开”，但这个其实只是书籍内的链接，并非网页超链接。正常情况下，这里应该不弹出这个提示。

![image](https://user-images.githubusercontent.com/57058325/107139988-1417a880-695a-11eb-9e2f-94a00cd970a8.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中解决这个问题
