### ISSUE TITLE
Flatpak version can't use natively installed fonts.

### ISSUE THREAD

**Issue by rago666** [troyeguo/koodo-reader#750]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Other Linux distribution

### App Version

1.5.2

### Bug Detail

Can't use already installed fonts in flatpak. This is not a flatpak limitation because flatpak apps like onlyoffice can use native fonts

### Screenshots (Optional)

![Screenshot from 2023-03-16 18-26-49](https://user-images.githubusercontent.com/51720144/225623095-90eef1c6-85a9-4443-9a0c-12f6aa58c87a.png)

**Comment by troyeguo** [comment]
Thanks for the feedback, we will look into it

**Comment by troyeguo** [comment]
Tested on 1.5.4 flatpak version, works fine to me
OS: Ubuntu 20
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/ee4b8e44-64ea-41a5-80f2-035936e17e7d)

**Comment by signdo** [comment]
@troyeguo
Hello!
When I placed some fonts in the `~/.var/app/io.github.troyeguo.koodo-reader/.local/share/fonts` directory, the presence of these fonts was not recognized in the books and Settings.

Some people don't want to grant the Flatpak application permission to read all files in the home directory, and they don't want to install certain copyright-restricted fonts (such as FangSong, KaiTi from Windows) on the system or in the home directory. So I think this application should consider reading the font directory in its own directory.

**Comment by troyeguo** [comment]
We will add support to import fonts in the future.
