### ISSUE TITLE
分章问题还没完全解决

### ISSUE THREAD

**Issue by haoxiaoyueh** [troyeguo/koodo-reader#752]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.3 开发版

### 我遇到的问题

在更新之后分章还是有点问题，还是这本书，在644章之后就分不出来了

### 截图或录像(可选的)

![分不出章节了](https://user-images.githubusercontent.com/113106402/226164972-6843f211-7115-48b9-91b3-692e744ad37c.png)

### 图书文件(可选的)

[我打造了旧日支配者神话.zip](https://github.com/troyeguo/koodo-reader/files/11010576/default.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的
