### ISSUE TITLE
Windows的客户端在阅读epub时目录跳转功能有问题，然而同一本书在网页版是可以正常跳转的

### ISSUE THREAD

**Issue by radombb** [troyeguo/koodo-reader#757]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.53

### 我遇到的问题

我尝试了便携版和压缩包版本，1.53版，无法跳转指定章节。网页版则正常工作。
虽然issue列表中有同样的问题，但似乎并没有解决。

### 图书文件(可选的)

[巷说百物语全集(套装共5册) (京极夏彦) (Z-Library).zip](https://github.com/troyeguo/koodo-reader/files/11040363/5.Z-Library.zip)

**Comment by troyeguo** [comment]
我这里测试便携版可以正常跳转，您可以检查一下设置里的版本信息是否是1.5.3。
