### ISSUE TITLE
章节标题中有引号的，无法识别此章节

### ISSUE THREAD

**Issue by hsgehsge** [troyeguo/koodo-reader#759]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

章节标题中有引号的，无法识别此章节，其他标点符号是否有此问题暂未发现

### 截图或录像(可选的)

![QQ图片20230325113456](https://user-images.githubusercontent.com/128877898/227689912-51ce9e94-c0f8-4487-b0e6-fcbec053eb7e.png)

### 图书文件(可选的)

[《海南1939》 作者：哥是出来打酱油的.zip](https://github.com/troyeguo/koodo-reader/files/11067895/1939.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的
