### ISSUE TITLE
Publish Koodo-Reader on Docker Hub

### ISSUE THREAD

**Issue by AmadeusGraves** [troyeguo/koodo-reader#761]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Would it be possible to publish Koodo-Reader on Docker Hub?

### Details

I currently have CasaOS installed, this system supports the installation of docker images that are published on Docker Hub.
Other applications like Yatch also have the same problem. Would it be possible to publish Koodo-Reader on Docker Hub?

CasaOS also includes the update of the containers, the problem that Koodo-Reader also presents is that you always have to do the update manually and always bringing you the project from GitHub when it would be easier for the user to have it in Docker Hub and use Watchtower or as I mentioned before, CasaOS. 

I'll leave here some links explaining how to synchronize Github with Docker Hub.

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
https://docs.docker.com/docker-hub/repos/#pushing-a-docker-container-image-to-docker-hub

**Comment by troyeguo** [comment]
Sorry, we don't maintain third-party distribution platform other than github and sourceforge. You can already find some unofficial koodo images on docker hub
