### ISSUE TITLE
章节正确，目录能打开，但是无章节内容，页码错误

### ISSUE THREAD

**Issue by borpubi** [troyeguo/koodo-reader#763]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.2  1.5.3 都有问题

### 我遇到的问题

1. 47.3MB的mobi电子书，打开缓慢。
2. 新添加时，章节定位在书的最后页面。
3. 章节内容丢失。
4. 总页码错误。

### 图书文件(可选的)

文件太大，无法上传，请稳步百度网盘：
链接: https://pan.baidu.com/s/1GSP0KPu_RMOgJI9nT1Y82w 提取码: 1jpz 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by troyeguo** [comment]
打开缓慢的问题会不断优化的，和图书体积，电脑性能有关。无法复现第2和3的问题。koodo支持本章的页码，不支持总页码

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的
