### ISSUE TITLE
点击下一章节和上一章节没有成功且阅读进度一直是0

### ISSUE THREAD

**Issue by chloechen900822** [troyeguo/koodo-reader#765]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.3

### 我遇到的问题

![image](https://user-images.githubusercontent.com/120442641/229049410-117a236b-99c9-42e0-aee2-05645544c831.png)

**Comment by chloechen900822** [comment]
web app都没有问题，网页都有问题

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by chloechen900822** [comment]
[pg63935-images.zip](https://github.com/troyeguo/koodo-reader/files/11133916/pg63935-images.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的
