### ISSUE TITLE
设置书签后,点击下一页或者其他离开书签页，书签就不见了

### ISSUE THREAD

**Issue by chloechen900822** [troyeguo/koodo-reader#767]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.3

### 我遇到的问题

https://user-images.githubusercontent.com/120442641/229082222-3b7ae0c3-6f98-4098-b5d2-96bc2dcfe022.mp4

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by chloechen900822** [comment]
[pg63935-images.zip](https://github.com/troyeguo/koodo-reader/files/11133904/pg63935-images.zip)

**Comment by chloechen900822** [comment]
请问找到问题了吗？

**Comment by troyeguo** [comment]
不好意思现在才回复，确实存在这个问题，会在下个版本修复的

**Comment by chloechen900822** [comment]
请问可以开放kookit.min.js的源码吗?

**Comment by troyeguo** [comment]
> 请问可以开放kookit.min.js的源码吗?

这个库只是在 https://github.com/johnfactotum/foliate-js 这个项目基础上做了简单的包装，没有多少开源的价值。

**Comment by happyscene** [comment]
> > 请问可以开放kookit.min.js的源码吗?
> 
> 这个库只是在 https://github.com/johnfactotum/foliate-js 这个项目基础上做了简单的包装，没有多少开源的价值。

很有价值，求开源。让大家学习一下，也利于其他小团队使用和推广这个项目
