### ISSUE TITLE
我的书架-全部图书，书本显示会重复或缺失

### ISSUE THREAD

**Issue by cherylyang718** [troyeguo/koodo-reader#771]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.5.1

### Bug Detail

页面：我的书架-全部图书
问题1：同一本图书会在【全部图书】上显示两个图标，点击该图书的菜单按钮，页面上会出现两个一样的菜单
问题2：有的图书导入后，有时会在【全部图书】中看不到，但子书架里显示是有该图书的
注：进入自定义的子书架，数据目前均显示正常

### Screenshots (Optional)

![Koodo_Reader_JqZqi82x27](https://user-images.githubusercontent.com/34498962/229761397-8eb4ad9c-32ec-46d3-b21f-bebf7b721ac3.png)

**Comment by troyeguo** [comment]
这个问题应该已经在1.5.3中修复了
