### ISSUE TITLE
firefox上无法翻页，翻页故障

### ISSUE THREAD

**Issue by tt8659** [troyeguo/koodo-reader#774]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Firefox

### Koodo Reader 版本

1.5.3

### 我遇到的问题

firefox上无法翻页

**Comment by troyeguo** [comment]
不建议在火狐浏览器使用，暂时没有适配除chromium类浏览器之外其他浏览器的计划
