### ISSUE TITLE
书名较长的书导入进去后打开是空白页

### ISSUE THREAD

**Issue by chloechen900822** [troyeguo/koodo-reader#775]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.3

### 我遇到的问题

书名较长的书(或有特殊符号的书名)导入进去后打开是空白页

### 截图或录像(可选的)

Uploading 20230410_134826.mp4…

### 图书文件(可选的)

[pg17474.zip](https://github.com/troyeguo/koodo-reader/files/11188030/pg17474.zip)

**Comment by troyeguo** [comment]
我这里测试可以打开和阅读，不过章节切换有点问题

**Comment by troyeguo** [comment]
已修复
