### ISSUE TITLE
希望朗读速度 可以改变 

### ISSUE THREAD

**Issue by xiaoao19** [troyeguo/koodo-reader#78]
1、朗读速度 希望可以调整 2-3倍可能才比较适合经过训练的耳朵 ，盲人可以5-6倍
2、希望有男生朗读 音高低一点听久了不累
3、mobi导入似乎兼容性不太好 我两次都看不到mobi的图片

**Comment by xiaoao19** [comment]
4、希望可以选项中可选 显示总页数  这样好让我知道读书进度 现在只显示每章的第几页 不知道离看完还多少页

**Comment by troyeguo** [comment]
感谢您的反馈，会考虑在后续版本增加这些功能
