### ISSUE TITLE
Hide Scrollbar

### ISSUE THREAD

**Issue by Overlord-Sergio** [troyeguo/koodo-reader#781]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Option to hide the scrollbar

### Details

I want to hide Scrollbar, It's distracting.
![image](https://user-images.githubusercontent.com/21261074/231617440-7f6a2a73-6073-42aa-b7a5-4973a35e5914.png)

**Comment by troyeguo** [comment]
Thanks for the advice, we'll look into this feature.

**Comment by troyeguo** [comment]
sidebar has been moved away from the text

**Comment by Overlord-Sergio** [comment]
Thank you :) I wanted to hide the scrollbar completely as I use my mouse scroll wheel instead. But this is great too, much better :)
