### ISSUE TITLE
无法用电脑端正常浏览cbz文件

### ISSUE THREAD

**Issue by vivianbaby0925** [troyeguo/koodo-reader#782]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

用网页版只能单页形式浏览cbz文件。请问如何才能两侧都显示漫画呢？
<img width="944" alt="image" src="https://user-images.githubusercontent.com/130791295/232132343-1550121d-ff87-4264-8e0c-fdc1304f1901.png">

而电脑端无法正常浏览同一个cbz文件，出现的是图片无法打开的图标。
如图。
<img width="932" alt="image" src="https://user-images.githubusercontent.com/130791295/232132195-b6d75cfd-e4ed-4053-b040-b7c926364839.png">

谢谢

**Comment by troyeguo** [comment]
网页版是和仓库代码同步的，所以能打开，可以升级到1.5.3开发版。1.5.1稳定版还是基于几个月前的代码。建议漫画使用单页模式或者滚动模式。双页模式由于技术原因，暂时无法支持

**Comment by vivianbaby0925** [comment]
感谢您的快速解答。我下载了1.5.3的版本现在电脑版也可以阅读了。谢谢
