### ISSUE TITLE
摘录在文字里删除后左菜单依然有

### ISSUE THREAD

**Issue by actforjason** [troyeguo/koodo-reader#79]
![image](https://user-images.githubusercontent.com/57058325/107845973-f09da380-6e1a-11eb-92e9-40d8d8ab07ac.png)

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本中修复这个问题。

**Comment by troyeguo** [comment]
您方便加一下QQ群吗，方便后续交流，群号：683775813
