### ISSUE TITLE
mobi格式和azw3格式大文件导入和打开非常慢

### ISSUE THREAD

**Issue by 894238940** [troyeguo/koodo-reader#793]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.5.4

### Bug Detail

mobi格式和azw3格式大文件导入和打开非常慢超过20mb大小以上的文件打开和导入非常慢每次打开都需要5分钟左右，导入大文件格式也是非常慢要5分钟左右，打开时一直提示在加载中，不过最后都能打开就是了

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本优化的，麻烦您提供一下电子书

**Comment by troyeguo** [comment]
请升级至最新开发版，并使用预缓存功能
