### ISSUE TITLE
ctrl+滚轮调整字体大小

### ISSUE THREAD

**Issue by AppleRabbitDENG** [troyeguo/koodo-reader#795]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

现在调整字体大小/行间距之类需要手动调整并且重启才能看到。能否支持实时调整呢？

### 细节描述

交互与calibre看epub电子书一致即可。谢谢

**Comment by troyeguo** [comment]
感谢您的建议，会考虑增加这个功能的

**Comment by AppleRabbitDENG** [comment]
谢谢
