### ISSUE TITLE
suggestion:adding definitions button to define the word from merrium webster or Cambridge dictionary or collins dictionary or vocubulary

### ISSUE THREAD

**Issue by DLRAM** [troyeguo/koodo-reader#797]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

建议添加定义按钮，提供在线词典或翻译服务。

### Details

,谢谢您的建议！作为一名AI语言模型，我无法实现新功能或按钮，但我可以建议您一些工具，以实现您所需的功能：  1. 关于Merriam-Webster的定义，您可以访问他们的网站www.merriam-webster.com或下载他们的应用程序。他们提供免费的词典服务，其中包括清晰的定义，同义词和用法示例。  2. 关于Cambridge Dictionary的定义，您可以访问他们的网站dictionary.cambridge.org或下载他们的应用程序。他们提供免费的词典服务，其中包括清晰的定义，发音和用法示例。  3. 关于Collins Dictionary的定义，您可以访问他们的网站www.collinsdictionary.com或下载他们的应用程序。他们提供免费的词典服务，其中包括清晰的定义，同义词和用法示例。  4. 如果您需要将单词翻译成中文，您可以使用在线翻译工具，例如Google翻译，百度翻译或有道翻译器。这些工具可以将英语单词翻译成中

**Comment by troyeguo** [comment]
目前已经支持google和bing翻译
