### ISSUE TITLE
无法打开epub文件,不知道是不是不兼容m1芯片.

### ISSUE THREAD

**Issue by jiangxiaoxu** [troyeguo/koodo-reader#80]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |     macOS 11.2.1 M1版      |
| App Version (应用版本)      |     1.2.1      |

---

无法打开epub文件,不知道是不是不兼容m1芯片.

**Comment by troyeguo** [comment]
您可以描述的再具体一点吗，是点击图书没反应，还是图书打开白屏，有什么错误提示吗，我没在mac上做过测试，也无法确定是不是兼容性问题

**Comment by jiangxiaoxu** [comment]
> 您可以描述的再具体一点吗，是点击图书没反应，还是图书打开白屏，有什么错误提示吗，我没在mac上做过测试，也无法确定是不是兼容性问题

是打开图书的时候白屏 整个软件页面都是白的.

**Comment by troyeguo** [comment]
1.2.0版本也存在这个问题吗？1.2.1版本更改了文件的存储方式，不知道是不是这个原因

**Comment by troyeguo** [comment]
您方便加一下QQ群吗，方便后续交流，群号：683775813
