### ISSUE TITLE
Build for Linux 32 bit

### ISSUE THREAD

**Issue by artenax** [troyeguo/koodo-reader#800]
Hello.
I made a build for Linux 32 bit. You can download it [here](https://github.com/artenax/koodo-reader/releases/).
Report any problems to my [Issues](https://github.com/artenax/koodo-reader/issues).
I don't plan to update it because the compilation was not easy.

**Comment by artenax** [comment]
How to automate deb packaging? You don't have it in the manual.

**Comment by troyeguo** [comment]
We will add 32 bit support for linux in the future. It's configured in package.json
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/4efa9649-3c8d-4bdd-853a-bf4bf3885956)

**Comment by troyeguo** [comment]
Please update to latest version

**Comment by artenax** [comment]
Thank you for the build. I checked, it works. I mentioned that it is better to download from you now.
