### ISSUE TITLE
希望增加批量删除和批量转移到其他书架的功能

### ISSUE THREAD

**Issue by iyinyin8** [troyeguo/koodo-reader#805]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

已导入的图书，进行分类整理时支持批量转移到其他书架，支持批量删除操作

### 细节描述

今日我想把之前导入的图书做一个分类整理，发现难度很大。
我的目的是把曾经已导入过的图书批量转到新建的书架，但是在新建的书架通过“导入图书”按钮，在批量导入时遇到以前导入过的会跳过，并且曾经旧的导入图书需要一个一个点击弹出菜单选择删除，没有找到批量操作的地方。

我阅读了官网的开发计划，发现曾经有个“批量操作图书”的记录标注为“完成开发”，但是从1.5.1更换为1.5.4并没有找到其他批量操作功能，似乎以前的“批量操作”只是支持图书的导入，并没有导入后的维护功能。

阅读器除了阅读体验外，资源库的管理功能做好了体验提升也很大，希望koodo后续越来越好

**Comment by troyeguo** [comment]
这个功能已经开发完了，点击图书列表左上角的选择按钮就行

**Comment by iyinyin8** [comment]
> 这个功能已经开发完了，点击图书列表左上角的选择按钮就行

抱歉，“选择”两字跟其他按钮相比太不起眼了，找一圈都没注意到(lll￢ω￢)
