### ISSUE TITLE
笔记中输入带声调的拼音字母，显示错误

### ISSUE THREAD

**Issue by neochen6** [troyeguo/koodo-reader#806]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.5.4（包括1.5.1）

### Bug Detail

在笔记中输入ó显示ò，输入ò显示ó，其他的带声调的拼音字母(āáǎà、ōǒ、ēéěè、īí ǐ ì、ūúǔù、ǖǘǚǜ)是正确的

### Screenshots (Optional)

![示例1](https://github.com/troyeguo/koodo-reader/assets/38391124/7b7551f0-24c8-474e-a63f-8648af833be4)
![示例2](https://github.com/troyeguo/koodo-reader/assets/38391124/3c57e6d7-02d5-4f6f-b63c-a559593c8392)

**Comment by troyeguo** [comment]
这里没法复现这个问题，猜测可能和字体有关

**Comment by troyeguo** [comment]
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/e4039c1f-dc09-4169-95fd-9beb5535f38f)
