### ISSUE TITLE
个别 epub 文件不能修改文字颜色

### ISSUE THREAD

**Issue by sangshuduo** [troyeguo/koodo-reader#808]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.4

### 我遇到的问题

修改后 load 一下又变回黑色

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件，可能是图书的内置样式，不支持修改的

**Comment by sangshuduo** [comment]
那算了，文件看完已经删了，记得是个尺寸很大（100M+）的 epub，但不是图片，文字是可以选的
