### ISSUE TITLE
Icon and Highlight Misalignment in Minimized Sidebar.

### ISSUE THREAD

**Issue by 0xNOY** [troyeguo/koodo-reader#809]
<details>
<summary>Pre-confirmation</summary>

### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

</details>

### Operating system or browser

Arch Linux

### App Version

1.5.4

### Bug Detail

The issue is as described in the title and screenshot.
Regardless of the selected item, the highlight is misaligned to the right.

The application was installed using `yay` from the [AUR package](https://aur.archlinux.org/packages/koodo-reader-bin).

### Screenshots

![koodo-reader-menu-deviated](https://github.com/troyeguo/koodo-reader/assets/37609107/3f27fcfb-5295-4d13-a318-b242fe22460d)

**Comment by troyeguo** [comment]
Thanks for the feedback, we will fix it in the next update

**Comment by troyeguo** [comment]
Please update to latest version
