### ISSUE TITLE
TXT目录

### ISSUE THREAD

**Issue by hsgehsge** [troyeguo/koodo-reader#810]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.4

### 我遇到的问题

在修复了之前提起的目录名称中有引号无法显示的问题后，1.5.4的目录又有这样的问题：会有一些正文内容被当做了章节名，我还没能总结出具体规律，第XX集这种被当做目录的情况出现的比较多，还有一些数字、这样的格式，测试文件已上传

### 截图或录像(可选的)

![001](https://github.com/troyeguo/koodo-reader/assets/128877898/92be4ebf-9c4b-4b79-aabd-5a8207898f54)
![002](https://github.com/troyeguo/koodo-reader/assets/128877898/2fcbbd29-bb29-46ee-8d4c-8abe9117e5ab)
![003](https://github.com/troyeguo/koodo-reader/assets/128877898/91cd79f4-09a1-4c91-a64d-4418437a4292)
![004](https://github.com/troyeguo/koodo-reader/assets/128877898/1b1b2db7-e2af-4444-a650-4743033853d6)

### 图书文件(可选的)

[《海南1939》 作者：哥是出来打酱油的.zip](https://github.com/troyeguo/koodo-reader/files/11499684/1939.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，txt的目录识别还在完善中，匹配的算法还需要提升

**Comment by troyeguo** [comment]
已在最新开发版修复
