### ISSUE TITLE
change the font of book on the reader 

### ISSUE THREAD

**Issue by bigsbug** [troyeguo/koodo-reader#812]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

setting the font for books 

### Details

I want to change the font of the book [pdf type] but there are not any features to achieve this requirement, in the book library we have a font setting but it only affects the book library and not the book font

**Comment by troyeguo** [comment]
Sorry, the font of pdf file is configurable. That's just how this format works.

**Comment by bigsbug** [comment]
@troyeguo Sorry, I'm a bit confused about how we can configure it. Can we do it through Koodo? or do we need to change it to use other apps?

**Comment by troyeguo** [comment]
> @troyeguo Sorry, I'm a bit confused about how we can configure it. Can we do it through Koodo? or do we need to change it to use other apps?

The font of pdf file is NOT configurable. My bad
