### ISSUE TITLE
听书功能异常

### ISSUE THREAD

**Issue by ZhuchaWenjiu** [troyeguo/koodo-reader#816]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.1

### 我遇到的问题

使用听书功能时会将每页读两遍，但是翻页正常，视频中的字体太大是因为想让他快速读完，并且也尝试了其他的分页形式，单页和滚动都试了

When using the listening function, each page will be read twice, but the page turning is normal, the font in the video is too large because I want it to read quickly, and I also tried other pagination forms, single page and scrolling

### 截图或录像(可选的)

https://github.com/troyeguo/koodo-reader/assets/44519689/9cd18ea2-4a0e-4149-b3c2-3ccfd5458359

### 图书文件(可选的)

[密室黄金时代的杀人_雪之馆与六种诡计_日_鸭崎暖炉_著_肥斑马_译_Z_Library.zip](https://github.com/troyeguo/koodo-reader/files/11563882/_._._._._._._Z_Library.zip)

**Comment by troyeguo** [comment]
升级到1.5.6之后也存在这个问题吗

**Comment by ZhuchaWenjiu** [comment]
> 升级到1.5.6之后也存在这个问题吗

最新的开发版1.5.5这个问题依然存在

**Comment by troyeguo** [comment]
不好意思，我在1.5.5上这里复现不了。会持续关注这个问题的。

**Comment by apnpc** [comment]
尊敬的开发者，您好！
同上的问题，我在 1.5.5 版本 也遇到了。
具体表现：
- 在读完一页时，翻页正常。√
- 朗读功能会重复朗读上一页内容。X

另外还存在一个翻页问题。
具体表现：当阅读到下一章时，无法回到上一章节。
- 鼠标翻页无效。X
- 翻页回退按钮（左按钮）无效 。X
- 下一页按钮正常。√

**Comment by troyeguo** [comment]
> 尊敬的开发者，您好！ 同上的问题，我在 1.5.5 版本也遇到了。 具体表现：
> 
> * 在读完一页时，翻页正常。√
> * 朗读功能会重复朗读上一页内容。X
> 
> 另外还存在一个翻页问题。 具体表现：当阅读到下一章时，无法回到上一章节。
> 
> * 鼠标返回上一页无效。X
> * 翻页回退按钮（左按钮）无效 。X
> * 下一页按钮正常。√
>   ![Animation](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)

麻烦您提供一下电子书文件

**Comment by apnpc** [comment]
> > 尊敬的开发者，您好！ 同上的问题，我在 1.5.5 版本也遇到了。 具体表现：
> > 
> > * 在读完一页时，翻页正常。√
> > * 朗读功能会重复朗读上一页内容。X
> > 
> > 另外还存在一个翻页问题。 具体表现：当阅读到下一章时，无法回到上一章节。
> > 
> > * 鼠标返回上一页无效。X
> > * 翻页回退按钮（左按钮）无效 。X
> > * 下一页按钮正常。√
> >   ![Animation](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> >         
> >           [
> >             
> >           
> >               ![Animation](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> >             ](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> >           
> >           
> >             
> >               
> >                 
> >               
> >               
> >                 
> >                 
> >               
> >             
> >             [
> >               
> >                 
> >               
> >             ](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> 
> 麻烦您提供一下电子书文件

[Docker Jin Jie Yu Shi Zhan - Hua Wei dockerShi Jian Xiao Zu.zip](https://github.com/troyeguo/koodo-reader/files/11712194/Docker.Jin.Jie.Yu.Shi.Zhan.-.Hua.Wei.dockerShi.Jian.Xiao.Zu.zip)

**Comment by troyeguo** [comment]
> 在最近使用过程中，听书功能会卡顿在标题处，不会继续往下，需要关闭再打开才会继续
感谢您的反馈，翻页异常还有听书时卡在标题处的问题确实存在，会在下个版本修复的。

**Comment by troyeguo** [comment]
请升级至1.5.6

**Comment by ZhuchaWenjiu** [comment]
非常感谢

**Comment by troyeguo** [comment]
> > > 尊敬的开发者，您好！ 同上的问题，我在 1.5.5 版本也遇到了。 具体表现：
> > > 
> > > * 在读完一页时，翻页正常。√
> > > * 朗读功能会重复朗读上一页内容。X
> > > 
> > > 另外还存在一个翻页问题。 具体表现：当阅读到下一章时，无法回到上一章节。
> > > 
> > > * 鼠标返回上一页无效。X
> > > * 翻页回退按钮（左按钮）无效 。X
> > > * 下一页按钮正常。√
> > >   ![Animation](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >         
> > >           [
> > >             
> > >           
> > >               ![Animation](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >             ](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >           
> > >           
> > >             
> > >               
> > >                 
> > >               
> > >               
> > >                 
> > >                 
> > >               
> > >             
> > >             [
> > >               
> > >                 
> > >               
> > >             ](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >           
> > >         
> > >   ```
> > >       [
> > >         
> > >       
> > >           ![Animation](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >         ](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >       
> > >       
> > >         
> > >           
> > >             
> > >           
> > >           
> > >             
> > >             
> > >           
> > >         
> > >         [
> > >           
> > >             
> > >           
> > >         ](https://user-images.githubusercontent.com/39884597/243108647-b55d21e5-5a14-450b-8f55-450ec86c56fe.gif)
> > >   ```
> > 
> > 
> > 麻烦您提供一下电子书文件
> 
> 在最近使用过程中，听书功能会卡顿在标题处，不会继续往下，需要关闭再打开才会继续

**Comment by user201905** [comment]
1.6.5 版本。 TXT 遇到换新章节时，听书会停止，需关闭“开启听书”再重新“开启听书”，又能听到本章结束。
