### ISSUE TITLE
Contents DISAPPEAR halfway through the chapter In "scrolling mode" in macOS Ventura

### ISSUE THREAD

**Issue by AgrMayank** [troyeguo/koodo-reader#818]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

macOS 12

### App Version

1.5.1, 1.5.5

### Bug Detail

The contents of the chapter disappear around halfway through when reading in the scrolling mode!
Sometimes I need to click on the scrolling mode again and the rest of the contents reappear, but this workaround doesn't always work. 

Also, the chapters take a LOT of time to update after clicking on the arrow buttons.

I'm using the latest M2 Pro MacBook running macOS Ventura!

### Screenshots (Optional)

<img width="1512" alt="SCR-20230526-pfst" src="https://github.com/troyeguo/koodo-reader/assets/26793209/c62a3829-51d2-4b53-9177-141df21437a4">

**Comment by troyeguo** [comment]
The contents  is actually not disappearing, just the height of the page is way beyond its content. We will fix it in the next update. The progress bellow is actually the progrss of the whole book not current chapter.

**Comment by AgrMayank** [comment]
> The contents  is actually not disappearing, just the height of the page is way beyond its content. 

They are disappearing actually. I opened the same chapter in another ebook reader, and it had the full contents. 
This issues is especially happening when there is an image in the chapter! The contents just disappear after the first image.
Btw, this is mostly happening with .epub books and less with .mobi ones.


> We will fix it in the next update.

Thanks!!!


> The progress bellow is actually the progrss of the whole book not current chapter. 

Yes. So sometimes, it works fine, but sometimes when the contents disappearing, the nav bar is just stuck at the start, even if I'm in the middle of the book.


Note - the above issues only happen in scroll mode.

**Comment by troyeguo** [comment]
Please send us the ebook file for testing. Also the progress bar and percentage is not designed to change as you read. They will update only when you navigate to a different chapter.

**Comment by troyeguo** [comment]
> They are disappearing actually. I opened the same chapter in another ebook reader, and it had the full contents.
This issues is especially happening when there is an image in the chapter! The contents just disappear after the first image.
Btw, this is mostly happening with .epub books and less with .mobi ones.
Please send us the ebook files for testing. We can't reproduce it.

**Comment by AgrMayank** [comment]
> The progress bar and percentage is not designed to change as you read. They will update only when you navigate to a different chapter.

Yes, so they don't update at all sometimes on changing chapters. Also, one more related bug is, I see the previous chapter name in the header. eg. I see Chapter 3 in the header when switching to Chapter 4. These don't happen always but are present in some ebooks.

**Comment by AgrMayank** [comment]
> > They are disappearing actually. I opened the same chapter in another ebook reader, and it had the full contents.
> > This issues is especially happening when there is an image in the chapter! The contents just disappear after the first image.
> > Btw, this is mostly happening with .epub books and less with .mobi ones.
> 
> Please send us the ebook files for testing. We can't reproduce it.

Sure. 
EPUB -> https://file.io/0vkIM5ddBnNJ

BTW, I've also tried converting the epub again with calibre, but no matter if I use parameters or not, the result is the same.

**Comment by troyeguo** [comment]
> > > They are disappearing actually. I opened the same chapter in another ebook reader, and it had the full contents.
> > > This issues is especially happening when there is an image in the chapter! The contents just disappear after the first image.
> > > Btw, this is mostly happening with .epub books and less with .mobi ones.
> > 
> > 
> > Please send us the ebook files for testing. We can't reproduce it.
> 
> Sure. EPUB -> https://file.io/0vkIM5ddBnNJ
> 
> BTW, I've also tried converting the epub again with calibre, but no matter if I use parameters or not, the result is the same.

Sorry, we haven't download it just in time and it's been deleted. you can compress it into zip file, and drag it here to upload.
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/44b45f4e-d3c9-450e-8772-d4075d0425e0)

**Comment by AgrMayank** [comment]
Sorry about that. I should've done so from the start. Here you go - [Sword Art Online - Volume 01 - Aincrad [Yen Press][Kobo].epub.zip](https://github.com/troyeguo/koodo-reader/files/11642011/Sword.Art.Online.-.Volume.01.-.Aincrad.Yen.Press.Kobo.epub.zip)

**Comment by troyeguo** [comment]
Thanks, we can confirm this bug and we will fix it in the next update

**Comment by AgrMayank** [comment]
> Thanks, we can confirm this bug and we will fix it in the next update

Thanks!!! That'd be really awesome since I don't want to switch to other e-readers. Will be eagerly waiting for the update :)

**Comment by troyeguo** [comment]
please update to 1.5.6

**Comment by AgrMayank** [comment]
This issue is mostly fixed now. Thanks!
