### ISSUE TITLE
起始都在文章内的 超链接 跳转无法运作

### ISSUE THREAD

**Issue by sunyink** [troyeguo/koodo-reader#819]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.5 dev

### 我遇到的问题

你好，Koodo Reader简洁凝练我很喜欢。在使用中我发现有些小说epub会在文内添加看起来像**超链接**的一行字，该链接**目标是跳转到该小说文件内部**后面的某部分，它被用在目录和特殊索引上。**但Koodo Reader无法响应打开操作**，鼠标移动上去会变成超链接的手指图标，但点击无反应。
我找了一个例子，并尝试自行研究：
1、如下图，将链接点住拖动到资源管理器形成.url文件，发现被识别成file:///D:/Users/123/Desktop/Koodo-Reader-1.5.5-x64-Win/resources/app.asar/build/index_split_496.html#id_DiErZhang_RenWuSheDingCaoAn
2、app.asar文件我无法正确打开，研究中断...

### 截图或录像(可选的)

![QQ截图20230528095950](https://github.com/troyeguo/koodo-reader/assets/37411580/71423dff-4e92-48db-84b8-b3b90d940f9d)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复这个问题的

**Comment by csjtl** [comment]
我也遇到了，试了1.5.2后的版本都不行，1.5.2的听书只有中文。

**Comment by troyeguo** [comment]
请升级至1.5.6
