### ISSUE TITLE
方向键问题

### ISSUE THREAD

**Issue by MRSHU1** [troyeguo/koodo-reader#826]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.51稳定版

### 我遇到的问题

1.滚动翻页模式下，有时候方向左右键能够切换上下章，此时按上下键不是滚动进度条，同样也是切换上下章。过了一会，上下键可以滚动进度条了，但是左右键无法切换上下章。试了几次都是这样，不知道是本身设置就是这样，还是存在bug。
2.开发版1.55用了，打开书籍直接白屏了，过了一会自动切换为稳定版了。

**Comment by troyeguo** [comment]
请升级至1.5.6
