### ISSUE TITLE
有epub电子书无法导入，也无任何提示

### ISSUE THREAD

**Issue by backdreamliu** [troyeguo/koodo-reader#828]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.5

### 我遇到的问题

部分电子书导入无反应。比如这本：
https://www.aliyundrive.com/s/YPcF3PWFUtC
这里我也上传了文件，请帮忙看看。

### 图书文件(可选的)

[九天-黑山老鬼.zip](https://github.com/troyeguo/koodo-reader/files/11684200/-.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by Tina-Tolle** [comment]
> 我今天安装使用一个小时，就看一本书，然后看书过程中卡了，我就自然关闭软件，再次打开软件，打开同一本书EPUB，是空白，加载不出来？这个一个小时的体验很棒，谢谢你的辛勤付出。

**Comment by Tina-Tolle** [comment]
> 感谢您的反馈，会在下个版本修复的

我今天安装使用一个小时，就看一本书，然后看书过程中卡了，我就自然关闭软件，再次打开软件，打开同一本书EPUB，是空白，加载不出来？这个一个小时的体验很棒，谢谢你的辛勤付出。

**Comment by troyeguo** [comment]
> > 感谢您的反馈，会在下个版本修复的
> 
> 我今天安装使用一个小时，就看一本书，然后看书过程中卡了，我就自然关闭软件，再次打开软件，打开同一本书EPUB，是空白，加载不出来？这个一个小时的体验很棒，谢谢你的辛勤付出。

请问这个问题是可以100%复现的吗？可以提供一下复现的录像吗？可以使用Win+G进行录屏

**Comment by troyeguo** [comment]
请升级至1.5.6
