### ISSUE TITLE
打开软件后界面无内容显示

### ISSUE THREAD

**Issue by waahaa** [troyeguo/koodo-reader#83]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |   win10 19041.685        |
| App Version (应用版本)      |   1.2.2        |

---

## Expected behavior (期望行为)

正常显示
## Current behavior (当前行为)
打开软件后界面无内容显示

![无标题](https://user-images.githubusercontent.com/41323324/108492742-7b314780-72e0-11eb-9198-521ada406f2c.png)

**Comment by troyeguo** [comment]
您好，请问之前的版本也存在这个问题吗，您可以尝试删除koodo-reader这个文件夹，位于C:\Users\您的用户名\AppData\Roaming\koodo-reader，看看是否还存在这个问题。

**Comment by waahaa** [comment]
> 您好，请问之前的版本也存在这个问题吗，您可以尝试删除koodo-reader这个文件夹，位于C:\Users\您的用户名\AppData\Roaming\koodo-reader，看看是否还存在这个问题。

之前用的是1.2.0版本，不存在这个问题，删除koodo-reader后软件已正常显示，thx
