### ISSUE TITLE
双页模式下，高亮操作失效。

### ISSUE THREAD

**Issue by AsterShion** [troyeguo/koodo-reader#835]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.5开发版

### 我遇到的问题

双页模式下，对PDF文件（文档型非扫描版）进行高亮操作，提示添加成功，但是对应文字并未高亮。

同样的操作，在单页显示模式下，可以正常进行高亮。

### 图书文件(可选的)

[Ou Li Juan Pin Du Gu Shi Ci - Ou Li Juan.pdf](https://github.com/troyeguo/koodo-reader/files/11721150/Ou.Li.Juan.Pin.Du.Gu.Shi.Ci.-.Ou.Li.Juan.pdf)

**Comment by troyeguo** [comment]
请升级至1.5.6
