### ISSUE TITLE
1.5.5版本epub双页模式第一页是空白页，1.5.1版本没有问题

### ISSUE THREAD

**Issue by code-hasaki** [troyeguo/koodo-reader#838]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.5

### 我遇到的问题

1.5.5版本epub双页模式第一页是空白页，1.5.1版本没有问题。比如看完了上一个章节进入当前章节有ABCDE五页，正常双页模式是AB一组，翻页CD一组，再翻页E空白一组，再翻页下一个章节。现在出现的问题是进入当前章节后，空白和A一组，翻页BC一组，再翻页DE一组，再翻页E空白一组，再翻页下一个章节（这里有两个问题，首先是空白页不应该是第一页，其次E页在翻页的过程中出现了两次）。跨章节翻页的时候经常出现这个问题。

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
这页空白是图书本身样式设置的，webkit-column-break-before: always，理论上不是bug
