### ISSUE TITLE
增删图书时，喜爱按钮没有及时更新

### ISSUE THREAD

**Issue by lluckyboi** [troyeguo/koodo-reader#844]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

稳定版 1.5.1

### Bug Detail

增删图书后，喜爱按钮位置未更新

点击其他页面后返回全部图书页面才会刷新

### Screenshots (Optional)

![uTools_1687107359628](https://github.com/troyeguo/koodo-reader/assets/53268752/d2e1ee2f-bc1b-47b6-90f3-128e5f7c7201)
![uTools_1687107382613](https://github.com/troyeguo/koodo-reader/assets/53268752/9260236d-be97-473c-9b85-80fc482896f0)

**Comment by troyeguo** [comment]
请升级至最新开发版
