### ISSUE TITLE
Support for vim keyboard shortcuts

### ISSUE THREAD

**Issue by guidomz** [troyeguo/koodo-reader#847]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

It would be helpful if I can use vim keyboard shortcuts to navigate through the pages, instead of being dependent on the mouse or touchpad.

### Details

I searched this repository for "vim". However, non-english results were shown and I only speak english.

**Comment by troyeguo** [comment]
We have already supported keyboard shortcuts for navigation. You can check out our document for more info. Not sure what's the difference between vim keyboard shortcuts and our current keyboard shortcuts.
https://troyeguo.notion.site/Koodo-Reader-Document-9c767af3d66c459db996bdd08a34c34b

**Comment by troyeguo** [comment]
We plan to add support to customize keyboard shorts in the future. Hope that will suffice your requirements.

**Comment by guidomz** [comment]
Will be looking forward to the implementation. Thanks.
