### ISSUE TITLE
增加图书的完整阅读时间统计

### ISSUE THREAD

**Issue by little1tow** [troyeguo/koodo-reader#849]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

增加图书的完整阅读时间统计

### 细节描述

目前只统计了单次阅读时间，并未统计整本书的阅读时间，希望这个功能可以完善一下

**Comment by troyeguo** [comment]
这个功能已经有了，在左侧面板的封面旁边

**Comment by hanxirui** [comment]
> 这个功能已经有了，在左侧面板的封面旁边

1.7.2版本依然没有这个功能； 依然统计的是单次阅读时间。
