### ISSUE TITLE
中文状态下菜单栏显示英文

### ISSUE THREAD

**Issue by ScienceZone** [troyeguo/koodo-reader#85]
运行环境：windows10。一直以来本软件启动速度速度比较慢，喜欢便携版，就下载啦便携版使用，但是不喜欢单文件版本，总觉得可能单文件的程序相当于一个压缩包，运行时可能涉及“解压”，所以启动速度可能更慢（其实实际怎样我并不懂），所以将单文件的便携版解压后直接当绿色软件用了，但是存在一个问题，之前的版本不存在，就是在中文模式下，菜单栏居然是英文的！希望查证修复一下！还有个问题就是希望能对epub支持添加高亮和下划线等操作（本软件加载epub文件的速度可真慢），可能的话期待有ipad版本赶快出现，这样作比较就更方便了，谢谢！

**Comment by ScienceZone** [comment]
似乎下划线和高亮是可以添加的，得点一下“摘录”，有点不太人性化，相比其他软件多了一步

**Comment by troyeguo** [comment]
我实际测试中，安装版其实会比便携版启动速度更快，菜单栏的英文问题会在后续版本中优化的，ipad版开发成本和难度太大，暂时没有这个计划。
