### ISSUE TITLE
怎么能没有章节选啊？

### ISSUE THREAD

**Issue by haoxiaoyueh** [troyeguo/koodo-reader#854]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.6

### 我遇到的问题

整本书只分出了两个章节，这个有点太离谱了，很严重的bug

### 截图或录像(可选的)

![1](https://github.com/troyeguo/koodo-reader/assets/113106402/e417fed3-a8a8-4097-be4c-e95bc4498bb2)
![2](https://github.com/troyeguo/koodo-reader/assets/113106402/26e7a504-7de2-4497-9dc5-4eeaa047e153)

### 图书文件(可选的)

[我打造了旧日支配者神话.zip](https://github.com/troyeguo/koodo-reader/files/11867589/default.zip)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的。由于经常对分章算法进行修改，难免出现疏漏，请见谅
