### ISSUE TITLE
请问这个项目如何自建web端看书啊？

### ISSUE THREAD

**Issue by venus1982518** [troyeguo/koodo-reader#86]

**Comment by troyeguo** [comment]
这个项目不提供开发部署方面的指导，请自行解决，本项目使用vercel进行网页版部署

**Comment by troyeguo** [comment]
首先需要您下载项目到本地，安装好node和yarn的环境，在根目录下，打开命令行工具，输入 yarn，等待依赖安装完毕之后，输入 yarn build，完成之后，会在根目录下生成build文件夹，里面包含用于网页版部署的文件，然后您可以使用宝塔之类的工具，把build文件夹下的文件上传到网站的根目录。如果您觉得麻烦还可以使用docker进行部署，或者直接使用vercel，netlify之类的静态网站部署服务，先将本项目fork到自己账号下，再登录这些网站直接导入项目，就可以完成自动部署。

**Comment by venus1982518** [comment]
好的,多谢啦.
目前还是用的calibre自带的服务端,感觉还是少点什么.

**Comment by yanickxia** [comment]
@venus1982518 参考 docker-compose 可以快速启动一个 WEB 版本

**Comment by likepoems** [comment]
> 首先需要您下载项目到本地，安装好node和yarn的环境，在根目录下，打开命令行工具，输入 yarn，等待依赖安装完毕之后，输入 yarn build，完成之后，会在根目录下生成build文件夹，里面包含用于网页版部署的文件，然后您可以使用宝塔之类的工具，把build文件夹下的文件上传到网站的根目录。如果您觉得麻烦还可以使用docker进行部署，或者直接使用vercel，netlify之类的静态网站部署服务，先将本项目fork到自己账号下，再登录这些网站直接导入项目，就可以完成自动部署。

请问这个项目在打包后就可以直接部署吗，dist应该是前端打包文件，没有服务端吗
