### ISSUE TITLE
翻译功能不可用

### ISSUE THREAD

**Issue by ruixuan658** [troyeguo/koodo-reader#862]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.5.1

### Bug Detail

翻译功能不可用

### Screenshots (Optional)

![image](https://github.com/troyeguo/koodo-reader/assets/60544711/479c72b3-5abe-442e-91c4-fe25d3e94a97)

**Comment by troyeguo** [comment]
请升级至最新开发版
