### ISSUE TITLE
epub最後一行被擋住

### ISSUE THREAD

**Issue by FiveCirclesTheorem** [troyeguo/koodo-reader#863]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.6

### 我遇到的问题

epub最後一行被擋住

### 截图或录像(可选的)

![螢幕擷取畫面 2023-07-08 214938](https://github.com/troyeguo/koodo-reader/assets/31173224/e1cb4ce2-5e5b-4c19-9bad-7625b9f15233)

**Comment by troyeguo** [comment]
感谢您的反馈，这个问题和滚动模式有关，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至1.5.7
