### ISSUE TITLE
Blockquotes breaking.

### ISSUE THREAD

**Issue by manish-003** [troyeguo/koodo-reader#874]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.5.6

### Bug Detail

blockquotes breaking, leaving page

### Screenshots (Optional)

![Screenshot 2023-07-21 111140](https://github.com/troyeguo/koodo-reader/assets/74863905/3db8d6f5-cda5-4276-b743-af11cba22228)

**Comment by troyeguo** [comment]
Please send us the book file for testing.

**Comment by manish-003** [comment]
[filefortesting.zip](https://github.com/troyeguo/koodo-reader/files/12136278/filefortesting.zip)

**Comment by troyeguo** [comment]
Please update to 1.5.7
