### ISSUE TITLE
Copy Link functionality;

### ISSUE THREAD

**Issue by sunlightspectre** [troyeguo/koodo-reader#876]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

When right-clicking on an embedded link, allow for copying the link to clipboard.

### Details

Copying embedded links is beneficial for multiple reasons:

- It allows readers to check the validity of the link for security purposes,
- It allows music, audio, or content links to be played separately or at leisure,
- It allows reader control over when/what method embedded links are used.

Recommendation: Right clicking an embedded link without any highlighting, or only highlighting the embedded link - 
Copies the link to clipboard, or offers a prompt to do so.

Complaint: Hey, speaking of, what is with programs trying to communicate in hieroglyphs these days?
At least offer the kindness of a hover-tool-tip, especially since it seems nobody agrees on what each hieroglyph means anymore.
Some of us older folk prefer words. They're really good, and can be used by translators and for accessibility purposes, too!
That's my humble plea. Please consider it...

**Comment by troyeguo** [comment]
Thanks for the advice, we will add it in the next update.

**Comment by sunlightspectre** [comment]
Thanks so much! Best of luck with everything!
