### ISSUE TITLE
v1.5.6部分epub电子书修改字体和颜色没反应

### ISSUE THREAD

**Issue by TellMEwhen** [troyeguo/koodo-reader#878]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.6

### 我遇到的问题

部分epub格式电子书，不能修改字体和颜色
换成1.5.1没有问题，但是1.5.1翻页的时候会卡屏

**Comment by troyeguo** [comment]
请升级至1.5.7
