### ISSUE TITLE
空格键不能翻页

### ISSUE THREAD

**Issue by aimingoo** [troyeguo/koodo-reader#879]
### I've already installed the latest developer version of Koodo Reader, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Chrome/Edge

### App Version

1.5.5

### Bug Detail

1.5.5和1.5.6两个版本中，空格键翻页不能使用。在之前的版本中是可用的。疑似与如下特性修复有关（v1.5.5）

* Shortcut not working in some scenerios

操作系统是win7。

**Comment by troyeguo** [comment]
技术原因，后续不再支持空格翻页，请使用方向键
