### ISSUE TITLE
图书导出按钮错位无法点击

### ISSUE THREAD

**Issue by BOOGAY** [troyeguo/koodo-reader#880]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.6

### 我遇到的问题

图书右上角三个点选择导出时二级菜单错位无法点击

### 截图或录像(可选的)

![_20230723222041](https://github.com/troyeguo/koodo-reader/assets/49016778/c5aedcc7-9e28-41b4-96da-fd25940d04ab)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至1.5.7
