### ISSUE TITLE
最新1.5.6版，按“最近阅读排序”无法正确排序

### ISSUE THREAD

**Issue by crystalxpcn** [troyeguo/koodo-reader#883]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.6

### 我遇到的问题

从稳定版覆盖升级到最新1.5.6版后，发现按“最近阅读排序”无法正确排序，刚刚阅读的书，无法排序到最前面。

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复的

**Comment by troyeguo** [comment]
请更新至最新开发版
