### ISSUE TITLE
希望尽快加入导出书摘和笔记功能

### ISSUE THREAD

**Issue by xiaoao19** [troyeguo/koodo-reader#89]
windows下设置koodo默认打开epub
双击打开第一个文件时 比导入慢 
有的甚至一直没反应
双击打开第二个文件时 就不可以了
好像提示只能一个窗口

希望尽快加入导出书摘和笔记功能，txt或html或者md文件比较好兼容，这个功能很重要！不然本软件是个封闭软件，与开源跨平台云同步有冲突

谢谢您！
基于文件同步功能上线很快，请继续加油！

## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |           |
| App Version (应用版本)      |           |

---

**Comment by troyeguo** [comment]
感谢您的建议，导出笔记书摘功能之前已经有人提过多次了，目前需求太多，开发时间有限，只能保证会在后续版本推出。

**Comment by simonecho** [comment]
> 感谢您的建议，导出笔记书摘功能之前已经有人提过多次了，目前需求太多，开发时间有限，只能保证会在后续版本推出。

或者换个思路把所有摘要和笔记存储到特定的txt、md或其他文本格式文档里，告诉大伙文件目录和名称，就可以手动导入到Onenote等笔记应用实现云存储，具体看看哪个实现起来更容易吧

**Comment by troyeguo** [comment]
已支持导出为excel，请升级最新开发版，更多格式导出会在后续支持
