### ISSUE TITLE
增加鼠标点击拖动时不自动弹出功能菜单，而是右键弹出功能

### ISSUE THREAD

**Issue by HanaChigusa** [troyeguo/koodo-reader#891]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

我阅读电子书习惯把鼠标放在文本上点击然后拖动，这样可以专注于某句话。
不想次次都弹出功能菜单。

### 细节描述

阅读器设置 设置一个选项：可以选择右键才弹出功能菜单。

**Comment by troyeguo** [comment]
最新开发版已经支持
![image](https://github.com/troyeguo/koodo-reader/assets/13820674/7fca0fb6-5a6d-4a3a-a978-235230442d3e)
