### ISSUE TITLE
使用键盘快捷键翻页速度慢

### ISSUE THREAD

**Issue by AllForLandlord** [troyeguo/koodo-reader#895]
### 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.7

### 我遇到的问题

在阅读epub书籍页面，使用键盘翻页的速度不稳定，有时候正常，有时候较慢，比如按下“下”键要等几秒才会翻到下一页，我的内存·和CPU占用都不超过40%，所以不是配置问题。
如果用鼠标点击页面左右下角的小箭头来翻页则完全没问题。
预缓存也不能改善该问题。

### 图书文件(可选的)

[转生成蜘蛛又怎样！ 06.zip](https://github.com/troyeguo/koodo-reader/files/12209280/06.zip)

**Comment by troyeguo** [comment]
我这里测试翻页是正常的，如果短时间内快速点击方向键，发现存在延迟问题，这是正常现象。如果是间隔一段时间，翻页还是存在这个问题，麻烦提供一下操作录像，最好再发一下您的图书库备份

**Comment by AllForLandlord** [comment]
> 我这里测试翻页是正常的，如果短时间内快速点击方向键，发现存在延迟问题，这是正常现象。如果是间隔一段时间，翻页还是存在这个问题，麻烦提供一下操作录像，最好再发一下您的图书库备份

原来如此，我说的就是短时间快速点击以后会出现卡顿现象，请问为什么用快捷键的话会卡顿呢？用鼠标快速点页面下方左右两边的箭头来翻页不会出现卡顿现象

**Comment by troyeguo** [comment]
这是因为对快捷键翻页时间间隔做了限制。主要是为了解决之前epub.js的bug。会在后续版本放开这个限制的。

**Comment by AllForLandlord** [comment]
> 这是因为对快捷键翻页时间间隔做了限制。主要是为了解决之前epub.js的bug。会在后续版本放开这个限制的。

了解了，谢谢！祝您生活愉快～
