### ISSUE TITLE
更多格式的支持

### ISSUE THREAD

**Issue by yep96** [troyeguo/koodo-reader#9]
windows端的阅读器大多只支持部分格式，而且界面不好看。不知道这款阅读器能不能美而全

**Comment by troyeguo** [comment]
您好！
支持更多格式目前来说难度会比较大，因为其他常见的电子书格式如mobi，txt等没有比较好的JavaScript插件提供解析支持，自己也没有开发这种插件的能力，给您带来的不便，敬请见谅。

**Comment by youtiaoguagua** [comment]
> 您好！
> 支持更多格式目前来说难度会比较大，因为其他常见的电子书格式如mobi，txt等没有比较好的JavaScript插件提供解析支持，自己也没有开发这种插件的能力，不过可以通过格式转换的方式间接提供支持，但不知道转换效果会怎么样，目前还不能给出肯定的答复。

pdf应该好好考虑一下😊

**Comment by troyeguo** [comment]
目前已经增加了对epub,pdf,mobi,azw3,txt的支持
