### ISSUE TITLE
Icon有白色边角

### ISSUE THREAD

**Issue by Yuriuh** [troyeguo/koodo-reader#90]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) | macOS Big Sur 11.2 |
| App Version (应用版本)      | 1.2.2 |

---

## Expected behavior (期望行为)
Dock 上的 Icon 没有白色边角

## Current behavior (当前行为)
Dock 上的 Icon 有白色边角
<img width="155" alt="koodo-icon-issue" src="https://user-images.githubusercontent.com/33216220/109918588-3058fc00-7cf2-11eb-9f4b-7a71b2036c1b.png">

**Comment by troyeguo** [comment]
感谢您的反馈，会在后续版本修复这一问题
