### ISSUE TITLE
plz let web version allow restores via back up files / 求让网页版的koodo reader 允许恢复备份

### ISSUE THREAD

**Issue by newbienoobplayer** [troyeguo/koodo-reader#901]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes
- [X] Yes

### 简单介绍

the .exe version of the koode reader is glitching on my computer and I am unable to completely delete it and reinstall it so could you allow the web version to be able to allow restore settings and books via back up files 
![image](https://github.com/troyeguo/koodo-reader/assets/138718840/01685d39-8473-47ce-aa4d-8e9e7bd3b290)
thank you！

软件版的阅读器一直在电脑上抽风，我却无法将其完全删除并重新安装，所以可以让网页版的koodo reader 允许恢复备份的功能吗？
![image](https://github.com/troyeguo/koodo-reader/assets/138718840/0527cd5e-7ee3-4f42-8ed3-de84f6359ac1)
谢谢您！

### 细节描述

as above

如上

**Comment by troyeguo** [comment]
网页版因为技术原因，暂不支持恢复备份，您可以详细描述一下软件版的问题吗？

**Comment by newbienoobplayer** [comment]
当我删除旧版koodo reader 的 本体文件的时候，我在GitHub 下载的最新版依旧有着用户数据，但是我已经把旧版的文件都删了

**Comment by troyeguo** [comment]
> 当我删除旧版koodo reader 的 本体文件的时候，我在GitHub 下载的最新版依旧有着用户数据，但是我已经把旧版的文件都删了

您可以下载安装这个版本：https://github.com/troyeguo/koodo-reader/releases/download/v1.5.7/Koodo-Reader-1.5.7.exe
然后正常卸载，卸载过程中，会询问是否删除用户数据。

**Comment by newbienoobplayer** [comment]
成功了，谢谢！，希望koodo reader 越做越好
