### ISSUE TITLE
首行缩进把代码块也首行缩进了

### ISSUE THREAD

**Issue by m2cc** [troyeguo/koodo-reader#907]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

首行缩进，应该不影响代码缩进，代码保持自身缩进

### 细节描述

首行缩进，应该不影响代码缩进，代码保持自身缩进

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件

**Comment by m2cc** [comment]
> 麻烦您提供一下电子书文件
任何一本程序代码的书都可以，github不支持epub格式的文件上传
![截图_选择区域_20230814181614](https://github.com/troyeguo/koodo-reader/assets/17061984/a4d3c9d7-8a58-4e55-8249-e0769e3d7b3c)
![截图_选择区域_20230814181634](https://github.com/troyeguo/koodo-reader/assets/17061984/0a2158b3-0491-4ddc-8f6e-94b04b7df984)

**Comment by troyeguo** [comment]
您可以将图书压缩为zip格式再上传

**Comment by m2cc** [comment]
> 您可以将图书压缩为zip格式再上传

[Let's Go - Alex Edwards.zip](https://github.com/troyeguo/koodo-reader/files/12471827/Let.s.Go.-.Alex.Edwards.zip)
差点忘了这事，麻烦您看一下

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by troyeguo** [comment]
请升级至1.5.9版
