### ISSUE TITLE
PDF笔记和摘要

### ISSUE THREAD

**Issue by simonecho** [troyeguo/koodo-reader#91]

**Comment by troyeguo** [comment]
感谢您的建议，会考虑在后续版本中增加这个功能

**Comment by troyeguo** [comment]
请更新到最新的1.3.5版

**Comment by simonecho** [comment]
appreciate




丁飞己

高等教育学博士研究生

华东师范大学教育学部高等教育研究所

上海市普陀区中山北路3663号,200062

电话：(+86)13818050642

 

Ding Fei-ji

PhD Candidate of Higher Education

Faculty of Education, East China Normal University

No. 3663,Zhong Shan Bei Road, Putuo District,Shanghai,China, 200062

Tel: (+86)13818050642

发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | Troye ***@***.***> |
| 日期 | 2021年11月29日 20:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [troyeguo/koodo-reader] PDF笔记和摘要 (#91) |

请更新到最新的1.3.5版

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by complyue** [comment]
我用 1.3.9 好像已经支持起来了，感谢！

不过好像还没有侧边栏列出所有高亮进行导航的支持，类似 Apple Preview 支持的这样：

![image](https://user-images.githubusercontent.com/15646573/174288839-661daaa3-c73c-4de8-baf5-79b223a5ecf9.png)

希望能增加，谢谢！

**Comment by simonecho** [comment]
新版已经ok，略微有点卡顿

从 Windows 版邮件发送

发件人: Compl Yue
发送时间: 2022年6月17日 19:23
收件人: troyeguo/koodo-reader
抄送: simonecho; Author
主题: Re: [troyeguo/koodo-reader] PDF笔记和摘要 (#91)

我用 1.3.9 好像已经支持起来了，感谢！
不过好像还没有侧边栏列出所有高亮进行导航的支持，类似 Apple Preview 支持的这样：

希望能增加，谢谢！

**Comment by complyue** [comment]
> 新版已经ok，略微有点卡顿

1.4.4  版pdf界面还是没找见呢?

![image](https://user-images.githubusercontent.com/15646573/174757227-b4b30a7e-039b-4f2f-887d-8d7ca51f3428.png)

**Comment by troyeguo** [comment]
不好意思，pdf阅读器暂时没有支持这个功能的计划。您可以在我的笔记和我的高亮查看
