### ISSUE TITLE
强迫症表示页面缩放229就很😣

### ISSUE THREAD

**Issue by Z-fly** [troyeguo/koodo-reader#92]
![image](https://user-images.githubusercontent.com/10470892/110407980-cfe60800-80bf-11eb-8eb6-053e8d4a525d.png)

**Comment by Z-fly** [comment]
现在是200% 210% 220% 229% 240% 250%

**Comment by troyeguo** [comment]
感谢您的建议，会考虑在后续版本中增加自定义缩放比例
