### ISSUE TITLE
在目录栏高亮显示目前的章节

### ISSUE THREAD

**Issue by 7777777lai** [troyeguo/koodo-reader#924]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

在目录栏高亮显示目前的章节

### 细节描述

在目录栏高亮显示目前的章节。
看书看到一半，下一章，经常忘记自己现在是哪一章，目录栏也没有显示，得多点几章才能找对章节
拿了别的阅读器的例子，希望不会介意。
![QQ截图20230827001954](https://github.com/troyeguo/koodo-reader/assets/46947901/49a95bc7-e19c-470b-be6b-c8ecbdc9b955)
![QQ截图20230827002054](https://github.com/troyeguo/koodo-reader/assets/46947901/3816e743-afaa-4112-8c21-04a5d4cd5b09)

**Comment by troyeguo** [comment]
这个功能已经在最新开发版支持了
