### ISSUE TITLE
A required privilege is not by client error

### ISSUE THREAD

**Issue by yobee-buddha** [troyeguo/koodo-reader#931]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 10 and below

### App Version

1.5.7

### Bug Detail

I am getting **a required privilege is not held by client** error when i ever try to start the program in my windows 10.
I tried both stable and developer version still getting the issue.

**Comment by troyeguo** [comment]
Can you send us some screenshots?

**Comment by yobee-buddha** [comment]
Sorry for late reply..

The issue got solved by installing koodo reader through winget.

But now new issue popped up. it installed successfully but when i run it it will open and white blank screen shows and after some seconds its close automatically.

Ss is attached to the comment.

Sorry if i need to create new issue post for this new issue please tell.


![koodo reader ss](https://github.com/troyeguo/koodo-reader/assets/93067788/91cae31b-e324-4973-a4ef-98a478d85458)

**Comment by yobee-buddha** [comment]
Just an update 
I uninstalled the koodo reader using winget and installed new fresh install from website and install it it successfully installed this time and it run successfully after showing blank screen loading time but now the program is running successfully.
Thanks for this great tool.
