### ISSUE TITLE
导入 txt 会自动生成不明文件

### ISSUE THREAD

**Issue by newbienoobplayer** [troyeguo/koodo-reader#936]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7 开发版

### 我遇到的问题

导入 txt 的时候电脑,在自带的Download 文件夹内会主动生成一个 book 文件夹 并且里面会有刚刚 导入的书 的 File 文件

### 截图或录像(可选的)

![Screenshot (515)](https://github.com/troyeguo/koodo-reader/assets/138718840/2bac866a-d4a4-4e75-ab3b-a69f3eff58f5)
![Screenshot (516)](https://github.com/troyeguo/koodo-reader/assets/138718840/14ddd437-c5db-431a-8ce1-07407d086092)
![Screenshot (517)](https://github.com/troyeguo/koodo-reader/assets/138718840/1d295700-b173-4a49-8d6e-ae502d9f94fa)
![Screenshot (518)](https://github.com/troyeguo/koodo-reader/assets/138718840/bb449646-6f6c-4b40-8bbe-20bc21a16965)

### 图书文件(可选的)

[book.zip](https://github.com/troyeguo/koodo-reader/files/12539277/book.zip)

**Comment by troyeguo** [comment]
请检查设置里的数据存储位置，现在设置的是否就是Download文件夹

**Comment by newbienoobplayer** [comment]
请问这个存储的是什么数据,影响看书进度吗?

**Comment by troyeguo** [comment]
koodo整个图书库都存储在这个位置，koodo默认会把导入的图书复制到图书库中，作为打开图书时的首选来源。如果不想复制，可以在设置里开启以引用的方式打开图书

**Comment by newbienoobplayer** [comment]
懂了,谢谢
