### ISSUE TITLE
双页视图下的pdf文件, 右侧页面无法显示高亮标记. 

### ISSUE THREAD

**Issue by ctdiesgi** [troyeguo/koodo-reader#938]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 10 及以下

### Koodo Reader 版本

1.5.1

### 我遇到的问题

平台: Thinkpad T480  windows10专业版
描述: 打开pdf文件, 并启用双页视图. 对右侧页面进行高亮标记之后, 右侧页面中的文字并不会进行高亮显示, 但在应用home页面的"我的高亮"中会有此次的操作记录. 

### 截图或录像(可选的)

![Uploading koodo-高亮不显示.gif…]()

**Comment by ctdiesgi** [comment]
![koodo-高亮不显示](https://github.com/troyeguo/koodo-reader/assets/42275720/09787e89-766d-4b5d-9631-14cc72ccf470)

**Comment by troyeguo** [comment]
麻烦您提供一下电子书文件，可以将图书压缩为zip格式上传到github

**Comment by ctdiesgi** [comment]
[JavaScript高级程序设计（第4版） (Matt Frisbie) (Z-Library).zip](https://github.com/troyeguo/koodo-reader/files/12596843/JavaScript.4.Matt.Frisbie.Z-Library.zip)

**Comment by troyeguo** [comment]
这个问题已经在最新开发版修复了

**Comment by troyeguo** [comment]
请升级至1.5.9版
