### ISSUE TITLE
最小化主程序界面时，阅读界面不应随之最小化

### ISSUE THREAD

**Issue by jianguyuxing** [troyeguo/koodo-reader#94]
## Brief Introduction (介绍)

点击书架所在的程序主界面上的最小化按钮时，阅读书籍的界面不应该被最小化。目前一点击主界面的最小化按钮时，阅读界面也会随之最小化。

## Motivation (动机)
 觉得主界面和阅读书籍界面同时打开影响视觉，需要最小化主界面。

**Comment by troyeguo** [comment]
感谢您的建议，会考虑在后续版本增加这个功能
