### ISSUE TITLE
打开默认全屏阅读模式. 希望更改后下次能按照更改后的窗口大小进行阅读

### ISSUE THREAD

**Issue by longshensanjie** [troyeguo/koodo-reader#95]
问题场景描述:
便携版体验的时候有个小问题, 就是添加的书籍每次打开都会默认全屏阅读模式, 对于小屏还行, 大屏的话每次打开全屏模式看不一定是很好的体验 (又或者例如需要一边看书另一边写文档的需求场景) 修改窗口大小后下次打开还是会默认全屏阅读, 于是现在就是需要每次打开书籍都得调整适合自己观看的窗口大小, 有点蛋疼

建议和需求:
至少希望能够调整窗口阅读空间大小后, 下次进来就是上次设置后的窗口阅读空间大小而不是默认全屏, 当然如果在外面还有其他的默认可选的几种观看模式设置那就更好了

**Comment by troyeguo** [comment]
感谢您的建议，会考虑在后续版本中增加这个功能的
