### ISSUE TITLE
翻译功能出错

### ISSUE THREAD

**Issue by YainHolmes** [troyeguo/koodo-reader#959]
### I've already installed the latest developer version of Koodo Reader from Github Release, this problem still exsits

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### I've already read the document, still can't solve it.

- [X] Yes

### Operating system or browser

Windows 11

### App Version

1.5.1

### Bug Detail

翻译出错啊，用google就是一片空白，用bing直接显示出错了，翻译就从来没有有用过

**Comment by troyeguo** [comment]
请升级最新开发版
