### ISSUE TITLE
mac下的图标四个角有白边，不知道是不是我这边特例

### ISSUE THREAD

**Issue by Z-fly** [troyeguo/koodo-reader#96]
![image](https://user-images.githubusercontent.com/10470892/110911821-236d8580-834e-11eb-9100-bc57480ca4b0.png)

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/110913399-0fc31e80-8350-11eb-9094-76dbb61108ec.png)
我看其他图标都是好的

**Comment by Z-fly** [comment]
还有个BUG就是，最小化后，按Alt+Tab切到图标时，会唤起窗口，但此时窗口无法控制。

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/110919523-523c2980-8357-11eb-9eab-d936fac6ea75.png)
这个地方没有关闭按钮，所以建议加一个

**Comment by Z-fly** [comment]
这些就是我使用下来的反馈

**Comment by troyeguo** [comment]
> ![image](https://user-images.githubusercontent.com/10470892/110913399-0fc31e80-8350-11eb-9094-76dbb61108ec.png)
> 我看其他图标都是好的，所以问一下

感谢您的反馈，会在后续版本中修复这个问题

**Comment by troyeguo** [comment]
> 还有个BUG就是，最小化后，按Alt+Tab切到图标时，会唤起窗口，但此时窗口无法控制。

没太明白您的意思，您可以再说的详细一点吗

**Comment by troyeguo** [comment]
> ![image](https://user-images.githubusercontent.com/10470892/110919523-523c2980-8357-11eb-9eab-d936fac6ea75.png)
> 这个地方没有关闭按钮，所以建议加一个

这个弹窗，点击书籍中其他位置后会自动隐藏

**Comment by Z-fly** [comment]
> > 还有个BUG就是，最小化后，按Alt+Tab切到图标时，会唤起窗口，但此时窗口无法控制。
> 
> 没太明白您的意思，您可以再说的详细一点吗


https://user-images.githubusercontent.com/10470892/110922836-28850180-835b-11eb-9efb-95af4b899b3b.mp4

**Comment by Z-fly** [comment]
> 这个弹窗，点击书籍中其他位置后会自动隐藏

我这里看，必须滚动页面才能隐藏

**Comment by troyeguo** [comment]
> > > 还有个BUG就是，最小化后，按Alt+Tab切到图标时，会唤起窗口，但此时窗口无法控制。
> > 
> > 
> > 没太明白您的意思，您可以再说的详细一点吗
> 
>  1.mp4

不好意思，我在windows上没办法复现这个bug，暂时也没有mac电脑可以调试这个bug。

**Comment by troyeguo** [comment]
> > 这个弹窗，点击书籍中其他位置后会自动隐藏
> 
> 我这里看，必须滚动页面才能隐藏

请问您是在用滚动模式吗，这个模式还存在一些bug，双页模式下也无法自动隐藏吗？

**Comment by Z-fly** [comment]
> > > > 还有个BUG就是，最小化后，按Alt+Tab切到图标时，会唤起窗口，但此时窗口无法控制。
> > > 
> > > 
> > > 没太明白您的意思，您可以再说的详细一点吗
> > 
> > 
> > 1.mp4
> 
> 不好意思，我在windows上没办法复现这个bug，暂时也没有mac电脑可以调试这个bug。

这个先放着吧，反正也不是啥恶性bug。我上面的说的弹窗加个关闭按钮，如果愿意做的话，软件用起来就更方便了。

**Comment by Z-fly** [comment]
> > > 这个弹窗，点击书籍中其他位置后会自动隐藏
> > 
> > 
> > 我这里看，必须滚动页面才能隐藏
> 
> 请问您是在用滚动模式吗，这个模式还存在一些bug，双页模式下也无法自动隐藏吗？

哦哦，双页模式点击其他地方就隐藏了

**Comment by troyeguo** [comment]
> > > > > 还有个BUG就是，最小化后，按Alt+Tab切到图标时，会唤起窗口，但此时窗口无法控制。
> > > > 
> > > > 
> > > > 没太明白您的意思，您可以再说的详细一点吗
> > > 
> > > 
> > > 1.mp4
> > 
> > 
> > 不好意思，我在windows上没办法复现这个bug，暂时也没有mac电脑可以调试这个bug。
> 
> 这个先放着吧，反正也不是啥恶性bug。我上面的说的弹窗加个关闭按钮，如果愿意做的话，软件用起来就更方便了。

感谢您的建议，会考虑增加这个功能的
