### ISSUE TITLE
多选/框选功能

### ISSUE THREAD

**Issue by Listen72** [troyeguo/koodo-reader#960]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

书籍多选/框选功能

### 细节描述

可以一次性选择多本书籍进行统一操作(例如统一放入一个书架,统一删除等)

**Comment by troyeguo** [comment]
目前已经支持，图书上右键点击多选
