### ISSUE TITLE
优化书籍分类

### ISSUE THREAD

**Issue by 12135huying** [troyeguo/koodo-reader#962]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

在将书籍添加到具体书架上后，删除在"全部图书"中的显示，便于在书籍过多时对书籍进行分类，或者在“全部图书”中将已分类的图书进行标记，类似于Z-library对已下载的图书进行标记一样

### 细节描述

很感谢这个项目，如果能优化这个问题，会更好

**Comment by troyeguo** [comment]
设置中可以开启隐藏添加到书架的图书
