### ISSUE TITLE
Windows11中：翻页动画、设置高亮再删掉、鼠标滚轮卡顿感

### ISSUE THREAD

**Issue by iperfectionism** [troyeguo/koodo-reader#966]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.51

### 我遇到的问题

1.翻页动画设置了，实际没有任何用处。
重新打开，重启都没有任何变化。

2.鼠标滑过设置高亮后，再点击高亮删除高亮没有任何改变，没有任何提示，删不掉高亮
重新打开软件，再试一遍就可以了，但看着看着，随机出现这个问题

3.用鼠标滚轮翻页，有轻微的不同步和卡顿（滚轮转了一圈实际页数没动，然后再转就跟着动两页或者多页）

### 截图或录像(可选的)

[2023-10-15 10-51-40.zip](https://github.com/troyeguo/koodo-reader/files/12908504/2023-10-15.10-51-40.zip)

设置高亮的问题，随机出现，视频中没录

**Comment by troyeguo** [comment]
建议升级到最新开发版，再尝试
