### ISSUE TITLE
MOBI文件图片不加载&滚动模式下无法滚动

### ISSUE THREAD

**Issue by Z-fly** [troyeguo/koodo-reader#97]
![image](https://user-images.githubusercontent.com/10470892/111066247-e7c2ef00-84f8-11eb-9260-f5a52171ac08.png)
点开图书后卡在这里，无法滚动。
win下最新版
[测试图书.zip](https://github.com/troyeguo/koodo-reader/files/6136531/default.zip)

**Comment by Z-fly** [comment]
点击目录后可以滚动。

**Comment by troyeguo** [comment]
您好，我在window上测试没有问题的，可能是乌合之众这本书，没有解析出章节，导致一个章节中的文字太多，解析时出现了卡顿。

**Comment by Z-fly** [comment]
> 您好，我在window上测试没有问题的，可能是乌合之众这本书，没有解析出章节，导致一个章节中的文字太多，解析时出现了卡顿。

你那边图片是正常加载的吗？

**Comment by Z-fly** [comment]
https://user-images.githubusercontent.com/10470892/111067126-a3861d80-84fd-11eb-970b-256540f72978.mp4

**Comment by troyeguo** [comment]
这两本书貌似不包含图片，Koodo不能解析封面图片，只能解析图书内部的图片

**Comment by Z-fly** [comment]
> 这两本书貌似不包含图片，Koodo不能解析封面图片，只能解析图书内部的图片

知道了

**Comment by Z-fly** [comment]
我这里在滚动模式下，一点开就卡住了。
明天用mac打开试试。

**Comment by troyeguo** [comment]
> 我这里在滚动模式下，一点开就卡住了。
> 明天用mac打开试试。

这可能和电脑性能有关，这种情况建议您暂时不要用Koodo阅读这本书，等待软件后续更新，优化分章解析算法

**Comment by Z-fly** [comment]
> 这两本书貌似不包含图片，Koodo不能解析封面图片，只能解析图书内部的图片

是什么原因导致不能解析封面图片呢？

**Comment by troyeguo** [comment]
> > 这两本书貌似不包含图片，Koodo不能解析封面图片，只能解析图书内部的图片
> 
> 是什么原因导致不能解析封面图片呢？

Koodo 解析mobi文件依赖第三方库，这个库不支持解析封面，我暂时也没有能力去重写这个库。
