### ISSUE TITLE
部分小说会出现章节错乱的情况

### ISSUE THREAD

**Issue by newbienoobplayer** [troyeguo/koodo-reader#973]
### 我已经从 Github Release 安装了最新开发版的 Koodo Reader，这个问题仍然存在

- [X] Yes

### 我已经搜索了已有的 issue 列表，没有找到类似的 issue

- [X] Yes

### 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决

- [X] Yes

### 操作系统或浏览器

Windows 11

### Koodo Reader 版本

1.5.7 开发版

### 我遇到的问题

如题,部分小说会出现章节错乱的情况,不显示章节

### 截图或录像(可选的)

![image](https://github.com/troyeguo/koodo-reader/assets/138718840/12cbb708-72b6-4e6b-b4a0-bf5452e2c994)
![image](https://github.com/troyeguo/koodo-reader/assets/138718840/0318b94c-f73d-4c7e-b61b-4faedf323ed3)

### 图书文件(可选的)

[[唐家三少]唯我独仙69.txt](https://github.com/troyeguo/koodo-reader/files/13073290/69.txt)
[生肖守护神_二改版_加料_无绿_全本109333.txt](https://github.com/troyeguo/koodo-reader/files/13073309/_._._._.109333.txt)

**Comment by troyeguo** [comment]
感谢您的反馈，会在下个版本修复的

**Comment by newbienoobplayer** [comment]
请问大概什么时候更新下个版本?
