### ISSUE TITLE
A config option to open or not the "sides" when hovering the window edges

### ISSUE THREAD

**Issue by dxps** [troyeguo/koodo-reader#974]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

A configuration option to open or not the sidebars when hovering the edges of the window.

### Details

This is a great epub reader! I simply love it.

I am having just one small wish about it: is there an option to open the "sides" only when clicking the "menu button" and not have them automatically open when hovering the edges?

Is there an quick / workaround option to do it? If yes, I'd play with the code locally.
I haven't seen it in the roadmap. 

Thanks!

**Comment by troyeguo** [comment]
You can turn on prevent accidental trigger in the Setting

**Comment by dxps** [comment]
Oh, that is fantastic! 🥳 Excellent job! 👏 

I was just looking into the _Reading options_, available when the book is open. 🤦‍♂️ 

For others that may have the same question, the application (not reading) settings is where this option is available, as shown below:

![image](https://github.com/troyeguo/koodo-reader/assets/14140226/cd369f22-2646-4f6f-bac8-2561712d1a8f)

**Comment by dxps** [comment]
@troyeguo Thanks again for the feedback! 🙏 
Btw, you may want to rename that to _Settings_ (the plural form, as it reflects the context).

**Comment by troyeguo** [comment]
> @troyeguo Thanks again for the feedback! 🙏 Btw, you may want to rename that to _Settings_ (the plural form, as it reflects the context).

Thanks for the advice, we will rename it in the next update.
