### ISSUE TITLE
希望去除阅读时窗口四周实线。

### ISSUE THREAD

**Issue by lumit66** [troyeguo/koodo-reader#978]
### 我已经阅读了 Koodo Reader 的开发计划，没有找到类似的需求

- [X] Yes

### 这个 issue 没有同时提多个需求.

- [X] Yes

### 简单介绍

我不知道是我设置问题（设置没找到）还是bug问题，打开图书就会出现如图。
![image](https://github.com/troyeguo/koodo-reader/assets/120006851/12afaf0e-e92d-4205-a67c-399b7cd7885e)

### 细节描述

我不知道是我设置问题（设置没找到）还是bug问题，打开图书就会出现如图。
![image](https://github.com/troyeguo/koodo-reader/assets/120006851/12afaf0e-e92d-4205-a67c-399b7cd7885e)

**Comment by troyeguo** [comment]
这个是仿真背景，可以在右边菜单关闭
