### ISSUE TITLE
Arrow key togglable changes

### ISSUE THREAD

**Issue by Rikki3x7** [troyeguo/koodo-reader#983]
### I've read Koodo Reader's roadmap, there is no similar feature.

- [X] Yes

### This issue only requests one feature.

- [X] Yes

### Brief Introduction

Add an option in settings to make the arrow keys like the mouse wheel.

### Details

Right now, on scroll mode of an .epub, the up/down arrow goes to the previous/next chapter. It'd be really nice if we could have the option to change it to scroll like the scroll wheel.

**Comment by troyeguo** [comment]
This feature has been implemented in the latest developer version.
